(()=>{
'use strict';

const firebaseConfig={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466',measurementId:'G-1MZS4J9Y4Z'};
firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
db.settings({experimentalForceLongPolling:true,useFetchStreams:false});
const inventoryRef=db.collection('inventario').doc('principal');

const E=id=>document.getElementById(id);
const r3=n=>Math.round((Number(n||0)+Number.EPSILON)*1000)/1000;
const n2=n=>Number(Number(n||0).toFixed(2));
const money=n=>'$'+Number(n||0).toFixed(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#39;'}[c]));
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const stampDate=v=>{if(!v)return null;if(v.toDate)return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d;};
const formatDate=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return v||'';return new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'}).replace(/\./g,'');};
const toast=t=>{const x=E('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__v2toast);window.__v2toast=setTimeout(()=>x.classList.remove('show'),2200);};

const GROUPS={mariscos:'Mariscos',verduras:'Verduras y frescos',salsas:'Salsas y líquidos',desechables:'Desechables',refrescos:'Refrescos'};
const ITEMS={
  fish:{name:'Filete de pescado',group:'mariscos',unit:'lb',purchaseUnit:'lb',factor:1,min:1},
  shrimp:{name:'Camarón',group:'mariscos',unit:'lb',purchaseUnit:'lb',factor:1,min:1},
  octopus:{name:'Tentáculo de pulpo',group:'mariscos',unit:'lb',purchaseUnit:'lb',factor:1,min:.5},
  tomato:{name:'Tomate',group:'verduras',unit:'oz',purchaseUnit:'lb',factor:16,min:8},
  onion:{name:'Cebolla morada',group:'verduras',unit:'oz',purchaseUnit:'lb',factor:16,min:6},
  cucumber:{name:'Pepino',group:'verduras',unit:'pzas',purchaseUnit:'pzas',factor:1,min:1},
  cilantro:{name:'Cilantro',group:'verduras',unit:'oz',purchaseUnit:'manojo',factor:2,min:2},
  lime:{name:'Limón natural',group:'verduras',unit:'pzas',purchaseUnit:'pzas',factor:1,min:6},
  avocado:{name:'Aguacate',group:'verduras',unit:'pzas',purchaseUnit:'pzas',factor:1,min:2},
  lemonJuice:{name:'Jugo de limón',group:'salsas',unit:'fl oz',purchaseUnit:'botella 32 fl oz',factor:32,min:12},
  clamato:{name:'Clamato',group:'salsas',unit:'fl oz',purchaseUnit:'botella 32 fl oz',factor:32,min:12},
  ketchup:{name:'Ketchup',group:'salsas',unit:'fl oz',purchaseUnit:'botella',factor:20,min:6},
  valentina:{name:'Salsa Valentina',group:'salsas',unit:'fl oz',purchaseUnit:'botella',factor:12.5,min:4},
  english:{name:'Salsa inglesa',group:'salsas',unit:'fl oz',purchaseUnit:'botella',factor:5,min:1.5},
  maggi:{name:'Maggi',group:'salsas',unit:'fl oz',purchaseUnit:'botella',factor:3.38,min:1},
  tomatoSauce:{name:'Salsa de tomate para aderezar',group:'salsas',unit:'fl oz',purchaseUnit:'fl oz',factor:1,min:0},
  tomatoPuree:{name:'Puré de tomate',group:'salsas',unit:'fl oz',purchaseUnit:'fl oz',factor:1,min:0},
  containerHalf:{name:'Contenedor ceviche ½ lb',group:'desechables',unit:'pzas',purchaseUnit:'pzas',factor:1,min:6},
  containerLb:{name:'Contenedor ceviche 1 lb',group:'desechables',unit:'pzas',purchaseUnit:'pzas',factor:1,min:6},
  lidCeviche:{name:'Tapa ceviche · ½ lb / 1 lb',group:'desechables',unit:'pzas',purchaseUnit:'pzas',factor:1,min:10},
  container12:{name:'Contenedor cóctel 12 oz',group:'desechables',unit:'pzas',purchaseUnit:'pzas',factor:1,min:6},
  lid12:{name:'Tapa cóctel 12 oz',group:'desechables',unit:'pzas',purchaseUnit:'pzas',factor:1,min:6},
  spoon:{name:'Cuchara',group:'desechables',unit:'pzas',purchaseUnit:'paquete 100',factor:100,min:15},
  napkins:{name:'Servilletas',group:'desechables',unit:'pzas',purchaseUnit:'paquete',factor:120,min:20},
  tostada:{name:'Tostadas',group:'desechables',unit:'pzas',purchaseUnit:'paquete',factor:22,min:10},
  coca:{name:'Coca-Cola',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  cokezero:{name:'Coke Zero',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  sprite:{name:'Sprite',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  drpepper:{name:'Dr Pepper',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  bigred:{name:'Big Red',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  fanta:{name:'Fanta',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4},
  manzanita:{name:'Manzanita',group:'refrescos',unit:'pzas',purchaseUnit:'pzas',factor:1,min:4}
};

const PRODUCTS={
  fish:{id:'manual_fish',name:'Ceviche de pescado',short:'Pescado',kind:'ceviche',recipeType:'fish',price:15},
  shrimp:{id:'manual_shrimp',name:'Ceviche de camarón',short:'Camarón',kind:'ceviche',recipeType:'shrimp',price:20},
  mixed:{id:'manual_mixed',name:'Ceviche mixto',short:'Mixto',kind:'ceviche',recipeType:'mixed',price:25},
  cocktailShrimp:{id:'manual_cocktail_shrimp',name:'Cóctel de camarón',short:'Cóctel camarón',kind:'cocktail',price:10},
  cocktailFishShrimp:{id:'manual_cocktail_fish_shrimp',name:'Cóctel pescado + camarón',short:'Cóctel pescado + camarón',kind:'cocktail',price:0,incompleteRecipe:true}
};
const EXTRA_TYPES=['fish','shrimp','mixed','cocktailShrimp'];
const SODAS=['','coca','cokezero','sprite','drpepper','bigred','fanta','manzanita'];
const COMMON_PER_LB={tomato:1.6,cucumber:1/6,onion:.8,cilantro:.2,lemonJuice:2.4,clamato:1.4,avocado:.25};
const PROTEINS={mixed:{fish:.25,shrimp:.1875},fish:{fish:.5},shrimp:{shrimp:.5}};
const SHRIMP_COCKTAIL_PER_12OZ={shrimp:.1875,onion:.5,cilantro:.1,avocado:.25,tomatoSauce:2.173,tomatoPuree:1.087,clamato:.652,lemonJuice:.065,english:.011,maggi:.011,container12:1,lid12:1,spoon:1,napkins:2};

let orders=[],movements=[];
let inv={items:{},purchasePrices:{},minStock:{},tracked:[],prepExtra:{},preparedStock:{}};
let orderView='today',editOrderId='',orderKind='delivery';

function nextSaturday(){const d=new Date(),add=(6-d.getDay()+7)%7;d.setDate(d.getDate()+add);return localDay(d);}
function displayQty(key,internal){const x=ITEMS[key];if(!x)return `${n2(internal)}`;const q=r3(Number(internal||0)/Number(x.factor||1));return `${n2(q)} ${x.purchaseUnit}`;}
function internalQtyFromPurchase(key,qty){return r3(Number(qty||0)*Number(ITEMS[key]?.factor||1));}
function priceFor(key){return Number(inv.purchasePrices?.[key]||0);}
function minFor(key){return Number(inv.minStock?.[key]??ITEMS[key]?.min??0);}
function tracked(key){return (inv.tracked||[]).includes(key)||Number(inv.items?.[key]||0)>0||priceFor(key)>0;}
function add(out,key,value){if(!(Number(value)>0))return;out[key]=r3(Number(out[key]||0)+Number(value));}

function cevichePackaging(pounds,out){const p=Math.max(0,Number(pounds||0)),whole=Math.floor(p+1e-9),rem=r3(p-whole),half=rem>0?1:0;add(out,'containerLb',whole);add(out,'containerHalf',half);add(out,'lidCeviche',whole+half);}
function buildRecipe(productKey,qty,sodaKey=''){
  const p=PRODUCTS[productKey]||PRODUCTS.mixed,out={};
  if(p.kind==='ceviche'){
    Object.entries(PROTEINS[p.recipeType]||{}).forEach(([k,v])=>add(out,k,v*qty));
    Object.entries(COMMON_PER_LB).forEach(([k,v])=>add(out,k,v*qty));
    cevichePackaging(qty,out);add(out,'spoon',qty);add(out,'napkins',2*qty);
    if(sodaKey&&ITEMS[sodaKey])add(out,sodaKey,1);
    return out;
  }
  if(productKey==='cocktailShrimp')Object.entries(SHRIMP_COCKTAIL_PER_12OZ).forEach(([k,v])=>add(out,k,v*qty));
  else{add(out,'container12',qty);add(out,'lid12',qty);add(out,'spoon',qty);add(out,'napkins',2*qty);}
  return out;
}

function productFromOrder(o){const saved=String(o?.manualProductType||o?.productType||'');if(PRODUCTS[saved])return saved;const item=o?.items?.[0]||{},id=String(item.productId||'').toLowerCase(),name=String(item.name||'').toLowerCase();if(id.includes('cocktail_fish_shrimp')||((name.includes('cóctel')||name.includes('coctel'))&&name.includes('pescado')&&name.includes('camar')))return 'cocktailFishShrimp';if(id.includes('cocktail_shrimp')||id==='cc12'||id==='cc16'||((name.includes('cóctel')||name.includes('coctel'))&&name.includes('camar')))return 'cocktailShrimp';if(id.includes('manual_fish')||id==='fp5'||id==='fp1'||(name.includes('ceviche')&&name.includes('pescado')&&!name.includes('mixto')))return 'fish';if(id.includes('manual_shrimp')||id==='fc5'||id==='fc1'||(name.includes('ceviche')&&name.includes('camar')&&!name.includes('mixto')))return 'shrimp';return 'mixed';}
function qtyFromOrder(o){const p=PRODUCTS[productFromOrder(o)];if(p?.kind==='cocktail')return Math.max(0,Number(o.cocktailQty||o.quantity||o.items?.[0]?.qty||0));if(Number(o.pounds)>0)return Number(o.pounds);const item=o.items?.[0]||{};if(Number(item.qty)>0){if(['fp5','fc5','fm5'].includes(String(item.productId)))return .5*Number(item.qty);return Number(item.qty);}return 0;}
function titleFromOrder(o){return o.productName||o.items?.[0]?.name||PRODUCTS[productFromOrder(o)]?.name||'Pedido';}
function packagingForOrder(o){const out={};const pkey=productFromOrder(o),p=PRODUCTS[pkey],qty=qtyFromOrder(o);if(o.manualOrder&&qty>0){if(p.kind==='ceviche')cevichePackaging(qty,out);else{add(out,'container12',qty);add(out,'lid12',qty);}return out;}(o.items||[]).forEach(item=>{const id=String(item.productId||'').toLowerCase(),name=String(item.name||'').toLowerCase(),q=Math.max(0,Number(item.qty||0));if(!q)return;if(['fp5','fc5','fm5','op5','oc5'].includes(id)){add(out,'containerHalf',q);add(out,'lidCeviche',q);}else if(['fp1','fc1','fm1','op1','oc1'].includes(id)){add(out,'containerLb',q);add(out,'lidCeviche',q);}else if(id.includes('cocktail')||['cc12','cc16','cm12','cm16'].includes(id)||name.includes('cóctel')||name.includes('coctel')){add(out,'container12',q);add(out,'lid12',q);}else if(id==='promo_constructor'||id==='promo_hambre'){add(out,'containerLb',q);add(out,'lidCeviche',q);add(out,'container12',q);add(out,'lid12',q);}else if(id==='promo_camaradas'){add(out,'containerLb',2*q);add(out,'lidCeviche',2*q);add(out,'container12',2*q);add(out,'lid12',2*q);}});return out;}
function recipeForOrder(o){let out={};const stored=o?.recipe||{};Object.entries(stored).forEach(([k,v])=>{if(ITEMS[k])out[k]=r3(Number(v||0));});['container12','lid12','containerHalf','containerLb','lidCeviche'].forEach(k=>delete out[k]);const pack=packagingForOrder(o);Object.entries(pack).forEach(([k,v])=>add(out,k,v));if(!Object.keys(out).length&&o.manualOrder){out=buildRecipe(productFromOrder(o),qtyFromOrder(o),o.sodaKey||'');}return out;}
function remainingRecipe(o){const base=recipeForOrder(o),used=o?.prepConsumed||{},out={};Object.entries(base).forEach(([k,v])=>{const left=Math.max(0,r3(Number(v||0)-Number(used[k]||0)));if(left>0)out[k]=left;});return out;}
function pendingProductionOrders(){return orders.filter(o=>!o.deleted&&!o.directSale&&!['entregado','cancelado'].includes(String(o.status||''))&&!['listo','en_ruta'].includes(String(o.deliveryStatus||''))&&!o.inventoryConsumedAt);}
function pendingNeeds(){const out={};pendingProductionOrders().forEach(o=>Object.entries(remainingRecipe(o)).forEach(([k,v])=>add(out,k,v)));Object.entries(inv.prepExtra||{}).forEach(([pkey,qty])=>{if(!(Number(qty)>0)||!PRODUCTS[pkey])return;Object.entries(buildRecipe(pkey,Number(qty),'')).forEach(([k,v])=>add(out,k,v));});return out;}
function orderedSummary(){const out={};pendingProductionOrders().forEach(o=>add(out,productFromOrder(o),qtyFromOrder(o)));return out;}
function totalSummary(){const out={...orderedSummary()};Object.entries(inv.prepExtra||{}).forEach(([k,v])=>add(out,k,v));return out;}
function totalPrepLb(){const t=totalSummary();return r3(Number(t.fish||0)+Number(t.shrimp||0)+Number(t.mixed||0));}
function shortages(){const need=pendingNeeds(),rows=[];Object.entries(ITEMS).forEach(([k,item])=>{const have=r3(Number(inv.items?.[k]||0)),required=r3(Number(need[k]||0)),reserve=tracked(k)?internalQtyFromPurchase(k,minFor(k)):0,target=required>0?required:reserve,lack=r3(Math.max(0,target-have));if(lack>0&&(required>0||tracked(k)))rows.push({k,item,have,required,target,lack,reserveOnly:required<=0});});return rows;}
function recipeCost(recipe){let total=0,complete=true;Object.entries(recipe||{}).forEach(([k,v])=>{const item=ITEMS[k];if(!item)return;const price=priceFor(k);if(!(price>0)){complete=false;return;}total+=(Number(v||0)/Number(item.factor||1))*price;});return {cost:n2(total),complete};}

function showScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));window.scrollTo({top:0,behavior:'instant'});if(name==='deliveries')renderDeliveries();if(name==='buy')renderBuy();if(name==='prepare')renderPrepare();if(name==='money')renderMoney();if(name==='orders')renderOrders();}
document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go){showScreen(go.dataset.go);return;}const close=e.target.closest('[data-close]');if(close){E(close.dataset.close).hidden=true;return;}});

function renderHome(){const pending=pendingProductionOrders(),s=shortages(),salesToday=movements.filter(m=>m.type==='sale'&&m.day===localDay()).reduce((a,m)=>a+Number(m.total||0),0);E('sumOrders').textContent=String(pending.length);const lb=totalPrepLb(),cocktails=Number(totalSummary().cocktailShrimp||0)+Number(totalSummary().cocktailFishShrimp||0);E('sumPrep').textContent=`${n2(lb)} lb${cocktails?` + ${n2(cocktails)} cóct.`:''}`;E('sumBuy').textContent=String(s.length);E('sumSales').textContent=money(salesToday);}

function orderMatches(o){const status=String(o.status||'confirmado'),stage=String(o.deliveryStatus||'por_preparar'),day=String(o.deliveryDate||''),today=localDay();if(orderView==='completed')return status==='entregado';if(orderView==='cancelled')return status==='cancelado';if(status==='entregado'||status==='cancelado')return false;if(orderView==='upcoming')return day>today;return !day||day<=today;}
function renderOrders(){document.querySelectorAll('[data-order-view]').forEach(b=>b.classList.toggle('active',b.dataset.orderView===orderView));const list=orders.filter(o=>!o.deleted&&orderMatches(o));if(!list.length){E('ordersList').innerHTML='<div class="empty">No hay pedidos aquí.</div>';return;}E('ordersList').innerHTML=list.map(o=>{const stage=String(o.deliveryStatus||'por_preparar'),canEdit=o.manualOrder&&!o.inventoryConsumedAt&&!['listo','en_ruta','entregado','cancelado'].includes(stage)&&!['entregado','cancelado'].includes(String(o.status));const status=String(o.status||'confirmado'),badge=status==='entregado'?'ENTREGADO':status==='cancelado'?'CANCELADO':stage==='listo'?'LISTO':stage==='en_ruta'?'EN RUTA':'CONFIRMADO';return `<article class="order-card"><div class="order-date">${esc(formatDate(o.deliveryDate))}${o.time?` · ${esc(o.time)}`:''}</div><div class="row-head"><div><strong>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${PRODUCTS[productFromOrder(o)]?.kind==='cocktail'?'pza':'lb'}</strong><small>${esc(o.customer||'Cliente')}${o.phone?' · '+esc(o.phone):''}<br>${o.address?esc(o.address):''}${o.zip?' · '+esc(o.zip):''}<br>Venta ${money(o.total)}</small></div><span class="badge ${stage==='listo'?'ready':stage==='en_ruta'?'route':status==='entregado'?'done':''}">${badge}</span></div>${o.notes&&o.notes!=='Sin notas'?`<small>📝 ${esc(o.notes)}</small>`:''}${canEdit?`<div class="card-actions"><button class="secondary" data-edit-order="${esc(o.id)}">✏️ Editar</button><button class="danger" data-cancel-order="${esc(o.id)}">Cancelar</button></div>`:''}</article>`;}).join('');}
E('orderFilters').addEventListener('click',e=>{const b=e.target.closest('[data-order-view]');if(!b)return;orderView=b.dataset.orderView;renderOrders();});
E('ordersList').addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-order]');if(edit){openOrder(edit.dataset.editOrder);return;}const cancel=e.target.closest('[data-cancel-order]');if(cancel){const o=orders.find(x=>x.id===cancel.dataset.cancelOrder);if(!o)return;if(!confirm(`¿Cancelar el pedido de ${o.customer||'este cliente'}?`))return;await db.collection('pedidos').doc(o.id).update({status:'cancelado',deliveryStatus:'cancelado',cancelledAt:firebase.firestore.FieldValue.serverTimestamp()});toast('Pedido cancelado');}});

function fillSelects(){E('orderProduct').innerHTML=Object.entries(PRODUCTS).map(([k,p])=>`<option value="${k}">${esc(p.name)}</option>`).join('');E('inventoryItem').innerHTML=Object.entries(ITEMS).map(([k,x])=>`<option value="${k}">${esc(x.name)}</option>`).join('');E('purchaseItem').innerHTML=E('inventoryItem').innerHTML;E('orderSoda').innerHTML=SODAS.map(k=>`<option value="${k}">${k?esc(ITEMS[k].name):'Sin refresco'}</option>`).join('');const times=[];const fmt=m=>{let h=Math.floor(m/60),mi=m%60,p=h>=12?'p. m.':'a. m.';h=h%12||12;return `${h}:${String(mi).padStart(2,'0')} ${p}`;};for(let m=12*60;m<19*60;m+=20)times.push(`${fmt(m)}–${fmt(m+20)}`);E('orderTime').innerHTML=times.map(x=>`<option>${x}</option>`).join('');}
function setOrderKind(kind){orderKind=kind;document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===kind));document.querySelectorAll('.delivery-only').forEach(x=>x.style.display=kind==='delivery'?'':'none');updateOrderPreview();}
E('orderKindBtns').addEventListener('click',e=>{const b=e.target.closest('[data-kind]');if(b)setOrderKind(b.dataset.kind);});
function syncProductForm(resetPrice=false){const p=PRODUCTS[E('orderProduct').value]||PRODUCTS.mixed;if(p.kind==='cocktail'){E('orderQty').min='1';E('orderQty').step='1';if(Number(E('orderQty').value)<1)E('orderQty').value='1';}else{E('orderQty').min='.5';E('orderQty').step='.5';if(Number(E('orderQty').value)<.5)E('orderQty').value='1';}if(resetPrice)E('orderPrice').value=p.price||'';E('orderSoda').disabled=p.kind==='cocktail';if(p.kind==='cocktail')E('orderSoda').value='';updateOrderPreview();}
function updateOrderPreview(){const p=PRODUCTS[E('orderProduct').value]||PRODUCTS.mixed,qty=Number(E('orderQty').value||0),price=Number(E('orderPrice').value||0),recipe=buildRecipe(E('orderProduct').value,qty,E('orderSoda').value),c=recipeCost(recipe);E('orderPreview').innerHTML=`<b>${esc(p.name)}</b><br>${n2(qty)} ${p.kind==='cocktail'?'pza':'lb'} × ${money(price)} = <b>${money(qty*price)}</b><br>${c.complete?`Costo estimado ${money(c.cost)} · Utilidad ${money(qty*price-c.cost)}`:'Costo incompleto: faltan precios de compra en Inventario.'}`;}
['orderProduct','orderQty','orderPrice','orderSoda'].forEach(id=>E(id).addEventListener('input',()=>id==='orderProduct'?syncProductForm(true):updateOrderPreview()));
function openOrder(id=''){editOrderId=id;const o=orders.find(x=>x.id===id),pkey=o?productFromOrder(o):'mixed';E('orderModalTitle').textContent=id?'Editar pedido':'Ingresar pedido';E('orderProduct').value=pkey;E('orderCustomer').value=o?.customer||'';E('orderPhone').value=o?.phone||'';E('orderAddress').value=o?.address||'';E('orderZip').value=o?.zip||'';E('orderDate').value=o?.deliveryDate||nextSaturday();E('orderTime').value=o?.time||E('orderTime').options[0]?.value||'';E('orderQty').value=String(o?qtyFromOrder(o):1);E('orderPrice').value=String(o?.unitPrice??o?.items?.[0]?.unitPrice??PRODUCTS[pkey].price??'');E('orderPayment').value=o?.payment||'Al recibir';E('orderSource').value=o?.manualSource||'Facebook';E('orderSoda').value=o?.sodaKey||'';E('orderNotes').value=o?.notes&&o.notes!=='Sin notas'?o.notes:'';setOrderKind(o?.directSale?'direct':'delivery');syncProductForm(false);E('orderModal').hidden=false;}
E('newOrderBtn').onclick=()=>openOrder();
E('saveOrderBtn').onclick=async()=>{const pkey=E('orderProduct').value,p=PRODUCTS[pkey],qtyRaw=Number(E('orderQty').value||0),qty=p.kind==='cocktail'?Math.floor(qtyRaw):Math.round(qtyRaw*2)/2,price=Number(E('orderPrice').value||0),customer=E('orderCustomer').value.trim()||'Cliente',phone=E('orderPhone').value.trim(),address=E('orderAddress').value.trim(),zip=E('orderZip').value.trim(),deliveryDate=E('orderDate').value,time=E('orderTime').value;if(!(qty>0)||!(price>0))return alert('Revisa cantidad y precio.');if(orderKind==='delivery'&&(!phone||!address||!zip||!deliveryDate||!time))return alert('Completa teléfono, dirección, ZIP, día y horario.');if(orderKind==='delivery'){const conflict=orders.find(o=>!o.deleted&&o.id!==editOrderId&&o.status!=='cancelado'&&o.status!=='entregado'&&!o.directSale&&o.deliveryDate===deliveryDate&&o.time===time);if(conflict)return alert('Ese horario ya tiene otra entrega.');}const recipe=buildRecipe(pkey,qty,E('orderSoda').value),calc=recipeCost(recipe),total=n2(qty*price),cost=calc.complete?calc.cost:null,profit=calc.complete?n2(total-calc.cost):null,stamp=firebase.firestore.FieldValue.serverTimestamp(),data={customer,phone:orderKind==='direct'?'':phone,address:orderKind==='direct'?'':address,zip:orderKind==='direct'?'':zip,deliveryDate:orderKind==='direct'?localDay():deliveryDate,time:orderKind==='direct'?'Venta directa':time,payment:E('orderPayment').value,notes:E('orderNotes').value.trim()||'Sin notas',source:'app-clientes',manualSource:E('orderSource').value,items:[{productId:p.id,name:p.name,detail:p.kind==='cocktail'?`12 oz · ${qty} ${qty===1?'cóctel':'cócteles'}`:`${qty} ${qty===1?'libra':'libras'}`,qty,unitPrice:price,lineTotal:total}],recipe,total,cost,profit,costComplete:calc.complete&&!p.incompleteRecipe,manualOrder:true,manualProductType:pkey,productType:pkey,productName:p.name,quantity:qty,quantityUnit:p.kind==='cocktail'?'pza':'lb',pounds:p.kind==='ceviche'?qty:0,cocktailQty:p.kind==='cocktail'?qty:0,unitPrice:price,sodaKey:E('orderSoda').value||'',promoSodas:E('orderSoda').value?1:0};E('saveOrderBtn').disabled=true;try{if(editOrderId){await db.collection('pedidos').doc(editOrderId).update({...data,editedAt:stamp});toast('Pedido actualizado');}else if(orderKind==='direct'){await registerDirectSale(data,pkey,qty);}else{const ref=db.collection('pedidos').doc();await ref.set({id:ref.id,...data,status:'confirmado',deliveryStatus:'por_preparar',directSale:false,confirmedAt:stamp,createdAt:stamp,createdAtClient:new Date().toISOString()});toast('Pedido guardado');}E('orderModal').hidden=true;editOrderId='';}catch(err){console.error(err);alert(err.message||'No se pudo guardar.');}finally{E('saveOrderBtn').disabled=false;}};

async function registerDirectSale(data,pkey,qty){const ref=db.collection('pedidos').doc(),mr=db.collection('movimientos').doc(),stamp=firebase.firestore.FieldValue.serverTimestamp();await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.exists?s.data():{},items={...(d.items||{})},prepared={...(d.preparedStock||{})};if(Number(prepared[pkey]||0)>=qty){prepared[pkey]=r3(Number(prepared[pkey]||0)-qty);}else{const recipe=data.recipe||{},miss=Object.entries(recipe).filter(([k,v])=>ITEMS[k]&&Number(items[k]||0)<Number(v||0));if(miss.length)throw new Error('No alcanza el inventario para esta venta directa. Corrige Inventario real o prepara extra.');Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v||0));});}const order={id:ref.id,...data,status:'entregado',deliveryStatus:'entregado',directSale:true,createdAt:stamp,deliveredAt:stamp,routeDeliveredAt:stamp,createdAtClient:new Date().toISOString()};tx.set(inventoryRef,{items,preparedStock:prepared,updatedAt:stamp},{merge:true});tx.set(ref,order);tx.set(mr,{type:'sale',date:stamp,day:localDay(),name:`Venta directa · ${data.productName}`,orderId:ref.id,total:data.total,cost:data.cost,profit:data.profit,payment:data.payment,manualSource:data.manualSource});});toast('Venta directa registrada');}

function renderPrepare(){const ordered=orderedSummary(),total=totalSummary(),prepared=inv.preparedStock||{};const orderLb=r3(Number(ordered.fish||0)+Number(ordered.shrimp||0)+Number(ordered.mixed||0)),extraLb=r3(Number(inv.prepExtra?.fish||0)+Number(inv.prepExtra?.shrimp||0)+Number(inv.prepExtra?.mixed||0)),totalLb=r3(orderLb+extraLb);E('prepTotals').innerHTML=`<div class="prep-summary-box"><small>PEDIDOS ENCARGADOS</small><b>${n2(orderLb)} lb</b></div><div class="prep-summary-box"><small>PREPARACIÓN EXTRA</small><b>${n2(extraLb)} lb</b></div><div class="prep-summary-box"><small>TOTAL A PREPARAR</small><b>${n2(totalLb)} lb</b></div>`;E('extraInputs').innerHTML=EXTRA_TYPES.map(k=>`<label class="extra-item"><span>${esc(PRODUCTS[k].short)}</span><input data-extra-key="${k}" type="number" min="0" step="${PRODUCTS[k].kind==='cocktail'?'1':'.5'}" value="${n2(inv.prepExtra?.[k]||0)}"></label>`).join('')+`<div class="extra-item full"><span>Extra ya preparado disponible</span><small>${EXTRA_TYPES.map(k=>`${esc(PRODUCTS[k].short)}: ${n2(prepared[k]||0)} ${PRODUCTS[k].kind==='cocktail'?'pza':'lb'}`).join(' · ')}</small></div>`;const list=pendingProductionOrders();E('prepareOrders').innerHTML=list.length?list.map(o=>`<article class="order-card"><div class="row-head"><div><strong>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${PRODUCTS[productFromOrder(o)]?.kind==='cocktail'?'pza':'lb'}</strong><small>${esc(o.customer||'Cliente')} · ${esc(formatDate(o.deliveryDate))} ${o.time?`· ${esc(o.time)}`:''}</small></div><span class="badge">CONFIRMADO</span></div><div class="card-actions"><button class="primary" data-prepared-order="${esc(o.id)}">✓ Ya quedó preparado</button></div></article>`).join(''):'<div class="empty">No hay pedidos pendientes de preparar.</div>';}
E('saveExtraBtn').onclick=async()=>{const next={};document.querySelectorAll('[data-extra-key]').forEach(i=>{const p=PRODUCTS[i.dataset.extraKey],raw=Math.max(0,Number(i.value||0));next[i.dataset.extraKey]=p.kind==='cocktail'?Math.floor(raw):Math.round(raw*2)/2;});await inventoryRef.set({prepExtra:next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});toast('Preparación extra guardada');};
E('prepareExtraBtn').onclick=async()=>{const extra={...(inv.prepExtra||{})},active=Object.entries(extra).filter(([k,v])=>PRODUCTS[k]&&Number(v)>0);if(!active.length)return alert('No tienes preparación extra marcada.');const recipe={};active.forEach(([k,v])=>Object.entries(buildRecipe(k,Number(v),'')).forEach(([ik,iv])=>add(recipe,ik,iv)));try{await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},prepared={...(d.preparedStock||{})},miss=Object.entries(recipe).filter(([k,v])=>ITEMS[k]&&Number(items[k]||0)<Number(v||0));if(miss.length)throw new Error('Faltan insumos registrados. Revisa COMPRAR antes de marcar el extra como preparado.');Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v||0));});active.forEach(([k,v])=>prepared[k]=r3(Number(prepared[k]||0)+Number(v)));const cleared={...(d.prepExtra||{})};active.forEach(([k])=>cleared[k]=0);tx.set(inventoryRef,{items,preparedStock:prepared,prepExtra:cleared,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});});toast('Extra preparado registrado');}catch(err){alert(err.message||'No se pudo registrar.');}};
E('prepareOrders').addEventListener('click',async e=>{const b=e.target.closest('[data-prepared-order]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.preparedOrder);if(!o)return;try{await markOrderPrepared(o);toast('Pedido listo para entregar');}catch(err){alert(err.message||'No se pudo preparar.');}});
async function markOrderPrepared(o){await db.runTransaction(async tx=>{const or=db.collection('pedidos').doc(o.id),os=await tx.get(or);if(!os.exists)throw new Error('El pedido ya no existe.');const current=os.data();if(current.inventoryConsumedAt||['listo','en_ruta','entregado'].includes(String(current.deliveryStatus||'')))return;const recipe=remainingRecipe({...current,id:o.id}),s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},miss=Object.entries(recipe).filter(([k,v])=>ITEMS[k]&&Number(items[k]||0)<Number(v||0));if(miss.length)throw new Error('Faltan insumos en el inventario real. Ve a COMPRAR y corrige lo que tienes.');Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v||0));});const stamp=firebase.firestore.FieldValue.serverTimestamp();tx.set(inventoryRef,{items,updatedAt:stamp},{merge:true});tx.update(or,{status:'confirmado',deliveryStatus:'listo',preparedAt:stamp,inventoryConsumedAt:stamp,routeUpdatedAt:stamp});});}

function renderBuy(){const rows=shortages();E('shortageCount').textContent=String(rows.length);E('shoppingList').innerHTML=rows.length?rows.map(x=>`<div class="shopping-row" data-buy-key="${x.k}"><div><strong>${esc(x.item.name)}</strong><small>${x.reserveOnly?`Mínimo deseado ${esc(displayQty(x.k,x.target))}`:`Necesitas ${esc(displayQty(x.k,x.required))}`} · Tienes ${esc(displayQty(x.k,x.have))}</small></div><div class="shopping-qty">Comprar ${esc(displayQty(x.k,x.lack))}</div></div>`).join(''):'<div class="empty">✅ No te falta comprar nada de lo calculado.</div>';E('inventoryList').innerHTML=Object.entries(GROUPS).map(([g,label])=>`<div class="inventory-group">${esc(label)}</div>${Object.entries(ITEMS).filter(([,x])=>x.group===g).map(([k,x])=>`<div class="inventory-row" data-inv-key="${k}"><div><strong>${esc(x.name)}</strong><small>Precio usual: ${priceFor(k)>0?`${money(priceFor(k))} / ${esc(x.purchaseUnit)}`:'sin precio'} · Mínimo: ${n2(minFor(k))} ${esc(x.purchaseUnit)}</small></div><b>${esc(displayQty(k,inv.items?.[k]||0))}</b></div>`).join('')}`).join('');}
E('shoppingList').addEventListener('click',e=>{const r=e.target.closest('[data-buy-key]');if(r)openPurchase(r.dataset.buyKey);});
E('inventoryList').addEventListener('click',e=>{const r=e.target.closest('[data-inv-key]');if(r)openInventory(r.dataset.invKey);});
E('reviewInventoryBtn').onclick=()=>openInventory(Object.keys(ITEMS)[0]);
E('registerPurchaseBtn').onclick=()=>openPurchase(shortages()[0]?.k||Object.keys(ITEMS)[0]);
function openInventory(key){E('inventoryItem').value=key;syncInventoryModal();E('inventoryModal').hidden=false;}
function syncInventoryModal(){const k=E('inventoryItem').value,x=ITEMS[k],internal=Number(inv.items?.[k]||0);E('inventoryQty').value=String(n2(internal/Number(x.factor||1)));E('inventoryPrice').value=priceFor(k)||'';E('inventoryMin').value=String(n2(minFor(k)));E('inventoryUnitHint').textContent=`(${x.purchaseUnit})`;E('inventoryPreview').innerHTML=`Tienes <b>${esc(displayQty(k,internal))}</b>. El precio es por <b>${esc(x.purchaseUnit)}</b>.`;}E('inventoryItem').addEventListener('change',syncInventoryModal);
E('saveInventoryBtn').onclick=async()=>{const k=E('inventoryItem').value,x=ITEMS[k],qty=Math.max(0,Number(E('inventoryQty').value||0)),price=Math.max(0,Number(E('inventoryPrice').value||0)),min=Math.max(0,Number(E('inventoryMin').value||0)),internal=internalQtyFromPurchase(k,qty),updates={};updates[`items.${k}`]=internal;updates[`purchasePrices.${k}`]=price;updates[`minStock.${k}`]=min;updates.tracked=firebase.firestore.FieldValue.arrayUnion(k);updates.updatedAt=firebase.firestore.FieldValue.serverTimestamp();await inventoryRef.update(updates);E('inventoryModal').hidden=true;toast('Inventario actualizado');};
function openPurchase(key){E('purchaseItem').value=key;E('purchaseQty').value='1';E('purchaseCost').value='';E('purchaseStore').value='';syncPurchaseModal();E('purchaseModal').hidden=false;}
function syncPurchaseModal(){const k=E('purchaseItem').value,x=ITEMS[k];E('purchaseUnit').value=x.purchaseUnit;const q=Number(E('purchaseQty').value||0),c=Number(E('purchaseCost').value||0);E('purchasePreview').innerHTML=`Se sumarán <b>${esc(displayQty(k,internalQtyFromPurchase(k,q)))}</b>${c>0?` · ${money(c)} total`:''}.`;}
['purchaseItem','purchaseQty','purchaseCost'].forEach(id=>E(id).addEventListener('input',syncPurchaseModal));
E('savePurchaseBtn').onclick=async()=>{const k=E('purchaseItem').value,x=ITEMS[k],qty=Number(E('purchaseQty').value||0),cost=Math.max(0,Number(E('purchaseCost').value||0)),store=E('purchaseStore').value.trim()||'Sin tienda';if(!(qty>0))return alert('Escribe cuánto compraste.');await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},prices={...(d.purchasePrices||{})},mr=db.collection('movimientos').doc(),stamp=firebase.firestore.FieldValue.serverTimestamp(),internal=internalQtyFromPurchase(k,qty);items[k]=r3(Number(items[k]||0)+internal);if(cost>0)prices[k]=n2(cost/qty);tx.set(inventoryRef,{items,purchasePrices:prices,tracked:firebase.firestore.FieldValue.arrayUnion(k),updatedAt:stamp},{merge:true});tx.set(mr,{type:'purchase',date:stamp,day:localDay(),name:x.name,itemKey:k,qty,unit:x.purchaseUnit,internalQty:internal,cost,store});});E('purchaseModal').hidden=true;toast('Compra registrada');};

function timeMinutes(v){const m=String(v||'').toLowerCase().match(/(\d{1,2}):(\d{2})\s*(a\.?\s*m\.?|p\.?\s*m\.?)?/);if(!m)return 9999;let h=+m[1],mi=+m[2],p=(m[3]||'').replace(/\s|\./g,'');if(p==='pm'&&h<12)h+=12;if(p==='am'&&h===12)h=0;return h*60+mi;}
function renderDeliveries(){const day=E('deliveryDate').value||localDay();E('deliveryDate').value=day;const list=orders.filter(o=>!o.deleted&&!o.directSale&&o.deliveryDate===day&&o.status!=='cancelado').sort((a,b)=>timeMinutes(a.time)-timeMinutes(b.time));E('deliveryList').innerHTML=list.length?list.map(o=>{const stage=o.status==='entregado'?'entregado':String(o.deliveryStatus||'por_preparar'),action=stage==='listo'?`<button class="primary" data-delivery-action="en_ruta" data-id="${o.id}">🛵 En ruta</button>`:stage==='en_ruta'?`<button class="primary" data-delivery-action="entregado" data-id="${o.id}">✅ Entregado</button>`:stage==='entregado'?'<span class="badge done">FINALIZADO</span>':'<span class="badge">FALTA PREPARAR</span>';return `<article class="delivery-card"><div class="delivery-time">${esc(o.time||'Sin horario')}</div><div class="row-head"><div><strong>${esc(o.customer||'Cliente')} · ${esc(titleFromOrder(o))}</strong><small>${esc(o.address||'')}${o.zip?' · '+esc(o.zip):''}<br>${o.phone?esc(o.phone):''}</small></div>${stage==='listo'?'<span class="badge ready">LISTO</span>':stage==='en_ruta'?'<span class="badge route">EN RUTA</span>':stage==='entregado'?'<span class="badge done">ENTREGADO</span>':''}</div><div class="card-actions"><button class="secondary" data-map="${esc(o.address||'')}">📍 Mapa</button>${action}</div></article>`;}).join(''):'<div class="empty">No hay entregas para este día.</div>';}
E('deliveryDate').addEventListener('change',renderDeliveries);
E('deliveryList').addEventListener('click',async e=>{const map=e.target.closest('[data-map]');if(map){window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(map.dataset.map)}`,'_blank');return;}const b=e.target.closest('[data-delivery-action]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.id);if(!o)return;if(b.dataset.deliveryAction==='en_ruta'){await db.collection('pedidos').doc(o.id).update({deliveryStatus:'en_ruta',routeUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()});toast('Pedido en ruta');}else await markDelivered(o);});
async function markDelivered(o){const existing=movements.find(m=>m.type==='sale'&&m.orderId===o.id),mr=existing?null:db.collection('movimientos').doc(),stamp=firebase.firestore.FieldValue.serverTimestamp();let cost=o.cost,profit=o.profit;if(cost==null){const c=recipeCost(recipeForOrder(o));if(c.complete){cost=c.cost;profit=n2(Number(o.total||0)-cost);}}await db.runTransaction(async tx=>{const or=db.collection('pedidos').doc(o.id),os=await tx.get(or);if(!os.exists)throw new Error('El pedido ya no existe.');tx.update(or,{status:'entregado',deliveryStatus:'entregado',deliveredAt:stamp,routeDeliveredAt:stamp});if(mr)tx.set(mr,{type:'sale',date:stamp,day:localDay(),name:titleFromOrder(o),orderId:o.id,total:Number(o.total||0),cost:cost??null,profit:profit??null,payment:o.payment||''});});toast('Entrega finalizada');}

function renderMoney(){const today=localDay(),sales=movements.filter(m=>m.type==='sale'),purchases=movements.filter(m=>m.type==='purchase'),salesToday=sales.filter(m=>m.day===today).reduce((a,m)=>a+Number(m.total||0),0),purchasesToday=purchases.filter(m=>m.day===today).reduce((a,m)=>a+Number(m.cost||0),0),profitToday=sales.filter(m=>m.day===today).reduce((a,m)=>a+(Number.isFinite(Number(m.profit))?Number(m.profit):Number(m.total||0)-Number(m.cost||0)),0),allSales=sales.reduce((a,m)=>a+Number(m.total||0),0);E('moneyMetrics').innerHTML=`<div class="money-box"><small>Ventas hoy</small><b>${money(salesToday)}</b></div><div class="money-box"><small>Compras hoy</small><b>${money(purchasesToday)}</b></div><div class="money-box"><small>Utilidad de ventas hoy</small><b>${money(profitToday)}</b></div><div class="money-box"><small>Ventas registradas</small><b>${money(allSales)}</b></div>`;E('moneyList').innerHTML=movements.slice(0,40).map(m=>{const d=stampDate(m.date),when=d?d.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'}):m.day||'';if(m.type==='sale')return `<div class="movement-row sale"><div><strong>Venta · ${esc(m.name||'Pedido')}</strong><small>${esc(when)}</small></div><div class="amount">${money(m.total)}</div></div>`;if(m.type==='purchase')return `<div class="movement-row purchase"><div><strong>Compra · ${esc(m.name||'Producto')}</strong><small>${esc(m.store||'')} · ${esc(when)}</small></div><div class="amount">-${money(m.cost)}</div></div>`;return '';}).join('')||'<div class="empty">Todavía no hay movimientos.</div>';}

function renderAll(){renderHome();renderOrders();renderPrepare();renderBuy();renderDeliveries();renderMoney();}
function init(){fillSelects();E('todayPill').textContent=new Date().toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short',year:'numeric'});E('deliveryDate').value=localDay();syncProductForm(true);E('app').hidden=false;E('appBoot').hidden=true;}

let inventoryReady=false,ordersReady=false,movementsReady=false,started=false;
function readyMaybe(){if(!started&&inventoryReady&&ordersReady&&movementsReady){started=true;init();renderAll();}else if(started)renderAll();}
inventoryRef.onSnapshot(async s=>{if(!s.exists){await inventoryRef.set({items:{},purchasePrices:{},minStock:{},tracked:[],prepExtra:{},preparedStock:{},updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return;}const d=s.data()||{};inv={items:{...(d.items||{})},purchasePrices:{...(d.purchasePrices||{})},minStock:{...(d.minStock||{})},tracked:[...(d.tracked||[])],prepExtra:{...(d.prepExtra||{})},preparedStock:{...(d.preparedStock||{})}};inventoryReady=true;E('syncBadge').textContent='En vivo';E('syncBadge').classList.add('ok');readyMaybe();},err=>{console.error(err);E('syncBadge').textContent='Sin conexión';});
db.collection('pedidos').onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const da=stampDate(a.createdAt)||new Date(a.createdAtClient||0),dbb=stampDate(b.createdAt)||new Date(b.createdAtClient||0);return dbb-da;});ordersReady=true;readyMaybe();},console.error);
db.collection('movimientos').orderBy('date','desc').limit(250).onSnapshot(s=>{movements=s.docs.map(d=>({id:d.id,...d.data()}));movementsReady=true;readyMaybe();},err=>{console.error(err);movements=[];movementsReady=true;readyMaybe();});

})();