(()=>{
'use strict';

const PROFILE=window.PANEL_PROFILE||{};
const ITEMS=PROFILE.items||{};
const PRODUCTS=PROFILE.products||{};
const PRODUCT_KEYS=Object.keys(PRODUCTS);
const ITEM_KEYS=Object.keys(ITEMS);
const $=id=>document.getElementById(id);
const $$=sel=>Array.from(document.querySelectorAll(sel));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[c]));
const n2=n=>Number(Number(n||0).toFixed(2));
const r3=n=>Math.round((Number(n||0)+Number.EPSILON)*1000)/1000;
const money=n=>'$'+Number(n||0).toFixed(2);
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const stampDate=v=>{if(!v)return null;if(typeof v.toDate==='function')return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d;};
const dayFrom=v=>{if(!v)return'';if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const d=stampDate(v);return d?localDay(d):'';};
const fmtDate=v=>{const s=dayFrom(v)||String(v||'');const m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return s;return new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'}).replace(/\./g,'');};
const fmtDateTime=v=>{const d=stampDate(v);return d?d.toLocaleString('es-MX',{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}):'';};
const normalize=s=>String(s||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const add=(out,key,val)=>{if(Number(val)>0)out[key]=r3(Number(out[key]||0)+Number(val));};

if(!window.firebase||!firebase.firestore){document.body.innerHTML='<div style="padding:30px;font:18px Arial">No se pudo cargar Firebase.</div>';return;}
if(!PROFILE.id){document.body.innerHTML='<div style="padding:30px;font:18px Arial">No se pudo cargar la configuración del negocio.</div>';return;}

const firebaseConfig={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466',measurementId:'G-1MZS4J9Y4Z'};
if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
try{db.settings({experimentalForceLongPolling:true,useFetchStreams:false});}catch(_){ }
const ordersRef=db.collection('pedidos');
const inventoryRef=db.collection('inventario').doc(PROFILE.inventoryDoc||'principal');
const movementsRef=db.collection('movimientos');
const FV=firebase.firestore.FieldValue;

let state={
  inv:{items:{},purchasePrices:{},stockMinimums:{},business:{}},
  orders:[],movements:[],view:'inicio',orderFilter:'pending',editOrderId:'',selectedPrepId:'',
  sync:{inventory:false,orders:false,movements:false,error:false}
};

const PAGE_TITLES={inicio:'Inicio',pedidos:'Pedidos',preparacion:'Preparación',inventario:'Inventario',compras:'Compras',entregas:'Entregas',dinero:'Dinero',recetas:'Recetas'};
const COMMON_UNITS=['lb','oz','pza','pzas','bolsa','paquete','caja','bote','botella','galón','litro','ml','fl oz'];

function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__panelToast);window.__panelToast=setTimeout(()=>t.classList.remove('show'),2400);}
function belongs(o){return PROFILE.id==='el-cubano'?(!o?.panelTenant||o.panelTenant==='el-cubano'):o?.panelTenant===PROFILE.id;}
function productFromOrder(o){const saved=String(o?.manualProductType||o?.productType||'');if(PRODUCTS[saved])return saved;if(typeof PROFILE.resolveProduct==='function'){try{const k=PROFILE.resolveProduct(o);if(PRODUCTS[k])return k;}catch(_){}}return PRODUCT_KEYS[0]||'';}
function qtyFromOrder(o){if(Number(o?.quantity)>0)return Number(o.quantity);if(typeof PROFILE.resolveQty==='function'){try{const q=Number(PROFILE.resolveQty(o));if(q>0)return q;}catch(_){}}const it=o?.items?.[0]||{};return Number(it.qty||it.quantity||1);}
function productUnit(p){return p?.unit||'pza';}
function titleFromOrder(o){return o?.productName||o?.items?.[0]?.name||PRODUCTS[productFromOrder(o)]?.name||'Pedido';}
function customerFromOrder(o){return o?.customer||o?.customerName||o?.name||'Cliente';}
function phoneFromOrder(o){return o?.phone||o?.customerPhone||o?.telefono||'';}
function addressFromOrder(o){return o?.address||o?.deliveryAddress||o?.direccion||'';}
function zipFromOrder(o){return o?.zip||o?.postalCode||'';}
function orderDay(o){return String(o?.deliveryDate||o?.date||o?.deliveryDay||'');}
function orderTime(o){return String(o?.time||o?.deliveryTime||'');}
function orderTotal(o){return Number(o?.total||o?.amount||0);}
function orderStatus(o){return normalize(o?.status||'confirmado');}
function deliveryStatus(o){return normalize(o?.deliveryStatus||'por_preparar').replace(/ /g,'_');}
function isCancelled(o){return ['cancelado','cancelled'].includes(orderStatus(o))||deliveryStatus(o)==='cancelado';}
function isDelivered(o){return ['entregado','delivered'].includes(orderStatus(o))||['entregado','delivered'].includes(deliveryStatus(o));}
function isReady(o){return ['listo','ready','en_ruta','onroute'].includes(deliveryStatus(o));}
function isPendingOrder(o){return !o.deleted&&!isCancelled(o)&&!isDelivered(o);}
function isProductionPending(o){return isPendingOrder(o)&&!o.directSale&&!isReady(o)&&!o.inventoryConsumedAt;}
function orderCreatedMs(o){return stampDate(o?.createdAt)?.getTime()||stampDate(o?.updatedAt)?.getTime()||0;}
function sortOrders(a,b){const da=orderDay(a)||'9999-99-99',dbb=orderDay(b)||'9999-99-99';return da.localeCompare(dbb)||orderTime(a).localeCompare(orderTime(b))||orderCreatedMs(b)-orderCreatedMs(a);}
function firstProduct(){return PRODUCT_KEYS[0]||'';}

function recipeFor(pkey,qty,soda=''){
  const out={};
  if(typeof PROFILE.buildRecipe==='function'){
    try{return PROFILE.buildRecipe(pkey,Number(qty||0),soda,add,r3)||{};}catch(_){ }
  }
  const p=PRODUCTS[pkey]||{};
  Object.entries(p.recipe||{}).forEach(([k,v])=>add(out,k,Number(v||0)*Number(qty||0)));
  return out;
}
function recipeForOrder(o){const saved={};Object.entries(o?.recipe||{}).forEach(([k,v])=>{if(ITEMS[k]&&Number(v)>0)saved[k]=r3(Number(v));});return Object.keys(saved).length?saved:recipeFor(productFromOrder(o),qtyFromOrder(o),o?.sodaKey||'');}
function internalUnitText(key,val){const item=ITEMS[key]||{},u=item.unit||item.purchaseUnit||'';return `${n2(val)} ${u}`.trim();}
function purchaseQtyText(key,internal){const item=ITEMS[key]||{},factor=Number(item.factor||1),u=item.purchaseUnit||item.unit||'';return `${n2(Number(internal||0)/factor)} ${u}`.trim();}
function currentQty(key){return r3(Number(state.inv.items?.[key]||0));}
function minimumQty(key){return r3(Number(state.inv.stockMinimums?.[key]||0));}
function purchasePrice(key){return Number(state.inv.purchasePrices?.[key]||0);}

function pendingNeeds(){const out={};state.orders.filter(isProductionPending).forEach(o=>Object.entries(recipeForOrder(o)).forEach(([k,v])=>add(out,k,v)));return out;}
function productionTotals(){const out={};state.orders.filter(isProductionPending).forEach(o=>add(out,productFromOrder(o),qtyFromOrder(o)));return out;}
function lowRows(){const needs=pendingNeeds();return ITEM_KEYS.map(k=>{const have=currentQty(k),min=minimumQty(k),need=Number(needs[k]||0),projected=r3(have-need),low=have<=min||have<need||projected<=min;return{k,item:ITEMS[k],have,min,need,projected,low};}).filter(x=>x.low).sort((a,b)=>(a.have-a.need)-(b.have-b.need));}
function shoppingRows(){const needs=pendingNeeds();return ITEM_KEYS.map(k=>{const have=currentQty(k),need=Number(needs[k]||0),min=minimumQty(k),target=Math.max(need,min),lack=r3(Math.max(0,target-have));return{k,item:ITEMS[k],have,need,min,lack};}).filter(x=>x.lack>0).sort((a,b)=>b.lack-a.lack);}
function missingForRecipe(recipe,items=state.inv.items||{}){return Object.entries(recipe||{}).filter(([k,v])=>ITEMS[k]&&Number(items[k]||0)+1e-9<Number(v||0)).map(([k,v])=>({k,name:ITEMS[k].name||k,need:Number(v),have:Number(items[k]||0)}));}

function setConnection(error=false){if(error)state.sync.error=true;const all=state.sync.inventory&&state.sync.orders&&state.sync.movements;const dot=$('connectionDot'),txt=$('connectionText'),pill=$('livePill');dot.classList.remove('ok','bad');if(state.sync.error){dot.classList.add('bad');txt.textContent='Error de conexión';pill.textContent='● Revisar conexión';pill.style.background='#ffebec';pill.style.color='#a9252a';}else if(all){dot.classList.add('ok');txt.textContent='Firebase conectado';pill.textContent='● En vivo';pill.style.background='';pill.style.color='';}else{txt.textContent='Conectando…';pill.textContent='● Conectando';}}
function setToday(){const d=new Date();$('todayText').textContent=d.toLocaleDateString('es-MX',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('deliveryDate').value=$('deliveryDate').value||localDay(d);}

function setView(name){if(!PAGE_TITLES[name])return;state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.viewPanel===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('pageTitle').textContent=PAGE_TITLES[name];closeSidebar();window.scrollTo({top:0,behavior:'instant'});if(name==='preparacion')renderPreparation();if(name==='entregas')renderDeliveries();if(name==='dinero')renderMoney();if(name==='recetas')renderRecipes();}
function openSidebar(){$('sidebar').classList.add('open');$('sidebarBackdrop').hidden=false;}
function closeSidebar(){$('sidebar').classList.remove('open');$('sidebarBackdrop').hidden=true;}

function renderBrand(){const b=state.inv.business||{};const name=b.name||PROFILE.name||'El Cubano';const short=name.replace(/^Ceviches\s*&\s*Cócteles\s*/i,'')||name;$('brandName').textContent=short;const logo=b.logoDataUrl||PROFILE.defaultLogo||'';const img=$('brandLogo');if(logo){img.src=logo;img.hidden=false;}else img.hidden=true;document.title=`Panel Operativo · ${short}`;}
function todayMovements(type){const day=localDay();return state.movements.filter(m=>movementType(m)===type&&movementDay(m)===day);}
function movementType(m){const t=normalize(m?.type||m?.kind||'');if(['sale','venta'].includes(t))return'sale';if(['purchase','compra'].includes(t))return'purchase';return t;}
function movementDay(m){return String(m?.day||dayFrom(m?.createdAt)||dayFrom(m?.timestamp)||'');}
function movementTotal(m){return Number(m?.total||m?.amount||m?.cost||0);}
function movementMs(m){return stampDate(m?.createdAt)?.getTime()||stampDate(m?.timestamp)?.getTime()||0;}

function renderDashboard(){const pending=state.orders.filter(isPendingOrder).length;const lows=lowRows();const sales=todayMovements('sale').reduce((s,m)=>s+movementTotal(m),0);const purchases=todayMovements('purchase').reduce((s,m)=>s+movementTotal(m),0);$('kpiSales').textContent=money(sales);$('kpiProfit').textContent=money(sales-purchases);$('kpiPending').textContent=String(pending);$('kpiLow').textContent=String(lows.length);setBadge('navOrdersBadge',pending);setBadge('navLowBadge',lows.length);
  const home=state.orders.filter(isPendingOrder).sort(sortOrders).slice(0,5);$('homeOrders').innerHTML=home.length?home.map(o=>`<div class="compact-row"><div><strong>${esc(customerFromOrder(o))}</strong><small>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${esc(productUnit(PRODUCTS[productFromOrder(o)]))}<br>${esc(fmtDate(orderDay(o)))} ${esc(orderTime(o))}</small></div><div class="right">${money(orderTotal(o))}</div></div>`).join(''):'<div class="empty-mini">No hay pedidos pendientes.</div>';
  $('homeLowStock').innerHTML=lows.length?lows.slice(0,6).map(x=>`<div class="compact-row"><div><strong>${esc(x.item.name||x.k)}</strong><small>Disponible: ${esc(purchaseQtyText(x.k,x.have))}${x.need>0?` · Necesario: ${esc(purchaseQtyText(x.k,x.need))}`:''}</small></div><div class="right" style="color:var(--red)">${esc(purchaseQtyText(x.k,Math.max(0,Math.max(x.need,x.min)-x.have)))}</div></div>`).join(''):'<div class="empty-mini">Inventario sin alertas.</div>';
}
function setBadge(id,n){const e=$(id);e.textContent=String(n);e.hidden=!(n>0);}

function statusInfo(o){if(isCancelled(o))return{label:'Cancelado',cls:'cancel'};if(isDelivered(o))return{label:'Entregado',cls:'done'};const ds=deliveryStatus(o);if(ds==='en_ruta'||ds==='onroute')return{label:'En ruta',cls:'route'};if(ds==='listo'||ds==='ready')return{label:'Listo',cls:'ready'};return{label:'Pendiente',cls:'pending'};}
function matchesOrderFilter(o){const f=state.orderFilter;if(f==='all')return true;if(f==='cancelled')return isCancelled(o);if(f==='delivered')return isDelivered(o);if(f==='ready')return !isDelivered(o)&&!isCancelled(o)&&isReady(o);return isPendingOrder(o)&&!isReady(o);}
function orderSearchMatch(o,q){if(!q)return true;const hay=[o.id,customerFromOrder(o),phoneFromOrder(o),titleFromOrder(o),addressFromOrder(o),zipFromOrder(o)].map(normalize).join(' ');return hay.includes(normalize(q));}
function renderOrders(){const q=$('orderSearch').value;const list=state.orders.filter(o=>!o.deleted&&belongs(o)&&matchesOrderFilter(o)&&orderSearchMatch(o,q)).sort(sortOrders);$('ordersList').innerHTML=list.length?list.map(o=>orderCard(o)).join(''):'<div class="empty-mini">No hay pedidos en esta vista.</div>';$$('#orderFilters button').forEach(b=>b.classList.toggle('active',b.dataset.orderFilter===state.orderFilter));}
function orderCard(o){const p=PRODUCTS[productFromOrder(o)]||{},st=statusInfo(o),canEdit=!isCancelled(o)&&!isDelivered(o)&&!o.inventoryConsumedAt&&!isReady(o);const phone=phoneFromOrder(o),addr=addressFromOrder(o);return `<article class="order-card">
<div class="order-main"><strong>${esc(customerFromOrder(o))}</strong><div class="order-meta"><span>Folio: ${esc(String(o.id||'').slice(-8))}</span><span>${esc(fmtDate(orderDay(o)))}</span><span>${esc(orderTime(o))}</span>${phone?`<span>${esc(phone)}</span>`:''}</div><div class="order-items">${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${esc(productUnit(p))}${addr?`<br><small>${esc(addr)} ${esc(zipFromOrder(o))}</small>`:''}</div></div>
<div><div class="order-status-row"><span class="badge ${st.cls}">${st.label}</span></div><div class="order-total">${money(orderTotal(o))}</div><div class="order-actions">${canEdit?`<button class="secondary-btn" data-edit-order="${esc(o.id)}">Editar</button><button class="danger-btn" data-cancel-order="${esc(o.id)}">Cancelar</button>`:''}${isProductionPending(o)?`<button class="primary-btn" data-prep-order="${esc(o.id)}">Preparar</button>`:''}</div></div>
</article>`;}

function fillOrderProducts(){const sel=$('orderProduct');sel.innerHTML=PRODUCT_KEYS.map(k=>`<option value="${esc(k)}">${esc(PRODUCTS[k].name||k)}</option>`).join('');}
function applyOrderProduct(resetPrice=false){const k=$('orderProduct').value||firstProduct(),p=PRODUCTS[k]||{};const step=Number(p.step||1);$('orderQty').step=String(step);$('orderQty').min=String(step);if(Number($('orderQty').value)<step)$('orderQty').value=String(step);if(resetPrice)$('orderPrice').value=Number(p.price||0)||'';renderOrderPreview();}
function renderOrderPreview(){const k=$('orderProduct').value,p=PRODUCTS[k]||{},qty=Number($('orderQty').value||0),price=Number($('orderPrice').value||0);$('orderPreview').innerHTML=`<b>${esc(p.name||'Producto')}</b><br>${n2(qty)} ${esc(productUnit(p))} × ${money(price)} = <b>${money(qty*price)}</b>`;}
function resetOrderForm(){state.editOrderId='';$('orderModalTitle').textContent='Nuevo pedido';$('orderProduct').value=firstProduct();$('orderQty').value=String(PRODUCTS[firstProduct()]?.step||1);$('orderCustomer').value='';$('orderPhone').value='';$('orderAddress').value='';$('orderZip').value='';$('orderDate').value=localDay();$('orderTime').value='12:00';$('orderPayment').value='Al recibir';$('orderNotes').value='';applyOrderProduct(true);}
function openOrderModal(id=''){resetOrderForm();if(id){const o=state.orders.find(x=>x.id===id);if(!o)return;state.editOrderId=id;$('orderModalTitle').textContent='Editar pedido';$('orderProduct').value=productFromOrder(o);$('orderQty').value=String(qtyFromOrder(o));$('orderPrice').value=String(Number(o.price||o.items?.[0]?.price||((orderTotal(o)/Math.max(1,qtyFromOrder(o)))||0)));$('orderCustomer').value=customerFromOrder(o);$('orderPhone').value=phoneFromOrder(o);$('orderAddress').value=addressFromOrder(o);$('orderZip').value=zipFromOrder(o);$('orderDate').value=orderDay(o)||localDay();$('orderTime').value=normalizeTimeForInput(orderTime(o));$('orderPayment').value=o.payment||'Al recibir';$('orderNotes').value=o.notes||'';applyOrderProduct(false);}$('orderModal').hidden=false;}
function normalizeTimeForInput(t){const s=String(t||'');if(/^\d{2}:\d{2}$/.test(s))return s;const m=s.match(/(\d{1,2}):(\d{2})\s*([ap])?/i);if(!m)return'12:00';let h=+m[1];const ap=(m[3]||'').toLowerCase();if(ap==='p'&&h<12)h+=12;if(ap==='a'&&h===12)h=0;return `${String(h).padStart(2,'0')}:${m[2]}`;}
async function saveOrder(){const pkey=$('orderProduct').value,p=PRODUCTS[pkey]||{},qty=Number($('orderQty').value||0),price=Number($('orderPrice').value||0),customer=$('orderCustomer').value.trim();if(!pkey||!(qty>0)||!customer){toast('Falta producto, cantidad o cliente.');return;}const total=n2(qty*price),recipe=recipeFor(pkey,qty,'');const data={panelTenant:PROFILE.id,manualOrder:true,panelEntry:true,manualProductType:pkey,productType:pkey,productName:p.name||pkey,quantity:qty,unit:productUnit(p),price,total,customer,phone:$('orderPhone').value.trim(),address:$('orderAddress').value.trim(),zip:$('orderZip').value.trim(),deliveryDate:$('orderDate').value,time:$('orderTime').value,payment:$('orderPayment').value,notes:$('orderNotes').value.trim(),items:[{name:p.name||pkey,qty,price,total}],recipe,updatedAt:FV.serverTimestamp()};try{if(state.editOrderId){await ordersRef.doc(state.editOrderId).update(data);toast('Pedido actualizado.');}else{const doc=ordersRef.doc();await doc.set({...data,id:doc.id,source:'app-clientes',status:'confirmado',deliveryStatus:'por_preparar',createdAt:FV.serverTimestamp()});toast('Pedido guardado.');}$('orderModal').hidden=true;}catch(e){console.error(e);toast('No se pudo guardar el pedido.');}}
async function cancelOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;if(!confirm(`¿Cancelar el pedido de ${customerFromOrder(o)}?`))return;try{await ordersRef.doc(id).update({status:'cancelado',deliveryStatus:'cancelado',cancelledAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()});toast('Pedido cancelado.');}catch(e){console.error(e);toast('No se pudo cancelar.');}}

function renderProductionSummary(){const totals=productionTotals();const pieces=Object.entries(totals).filter(([k,v])=>PRODUCTS[k]&&Number(v)>0).map(([k,v])=>`${PRODUCTS[k].short||PRODUCTS[k].name}: ${n2(v)} ${productUnit(PRODUCTS[k])}`);const orders=state.orders.filter(isProductionPending);const needs=pendingNeeds();const missing=Object.entries(needs).filter(([k,v])=>currentQty(k)<Number(v)).length;$('productionSummary').innerHTML=`<div class="prod-stat"><small>PEDIDOS POR PREPARAR</small><b>${orders.length}</b></div><div class="prod-stat"><small>PRODUCCIÓN</small><b>${esc(pieces.join(' · ')||'Sin producción')}</b></div><div class="prod-stat"><small>FALTANTES</small><b>${missing}</b></div>`;}
function renderPreparation(){renderProductionSummary();const list=state.orders.filter(isProductionPending).sort(sortOrders);if(!list.length){state.selectedPrepId='';$('prepOrders').innerHTML='<div class="empty-mini">No hay pedidos por preparar.</div>';$('prepDetail').className='prep-detail empty-state';$('prepDetail').innerHTML='<div class="empty-icon">✓</div><h3>Producción al día</h3><p>No tienes pedidos pendientes de preparación.</p>';return;}if(!list.some(o=>o.id===state.selectedPrepId))state.selectedPrepId=list[0].id;$('prepOrders').innerHTML=list.map(o=>`<button class="prep-order-btn ${o.id===state.selectedPrepId?'active':''}" data-select-prep="${esc(o.id)}"><strong>${esc(customerFromOrder(o))} · ${esc(titleFromOrder(o))}</strong><small>${n2(qtyFromOrder(o))} ${esc(productUnit(PRODUCTS[productFromOrder(o)]))} · ${esc(fmtDate(orderDay(o)))} ${esc(orderTime(o))}</small></button>`).join('');renderPrepDetail();}
function renderPrepDetail(){const o=state.orders.find(x=>x.id===state.selectedPrepId);if(!o){return;}const recipe=recipeForOrder(o),missing=missingForRecipe(recipe);const p=PRODUCTS[productFromOrder(o)]||{};const rows=Object.entries(recipe).filter(([k,v])=>ITEMS[k]&&Number(v)>0).map(([k,v])=>`<div class="ingredient-row"><span>${esc(ITEMS[k].name||k)}</span><b>${esc(internalUnitText(k,v))}</b></div>`).join('')||'<div class="ingredient-row"><span>Sin ingredientes configurados</span><b>—</b></div>';$('prepDetail').className='prep-detail';$('prepDetail').innerHTML=`<div class="prep-ticket"><div class="prep-ticket-head"><strong>${esc(customerFromOrder(o))} · ${esc(titleFromOrder(o))}</strong><small>${n2(qtyFromOrder(o))} ${esc(productUnit(p))} · ${esc(fmtDate(orderDay(o)))} ${esc(orderTime(o))}</small></div><div class="steps">
<div class="step"><div class="step-no">1</div><div><h4>Revisar pedido</h4><p>Cliente: ${esc(customerFromOrder(o))}. Cantidad: ${n2(qtyFromOrder(o))} ${esc(productUnit(p))}. ${o.notes?`Nota: ${esc(o.notes)}`:'Sin notas especiales.'}</p></div></div>
<div class="step"><div class="step-no">2</div><div><h4>Medir ingredientes</h4><p>Saca exactamente estas cantidades para este pedido.</p><div class="ingredient-rows">${rows}</div></div></div>
<div class="step"><div class="step-no">3</div><div><h4>Preparar el producto</h4><p>Prepara ${esc(titleFromOrder(o))} con las cantidades de la receta de arriba.</p></div></div>
<div class="step"><div class="step-no">4</div><div><h4>Empacar y revisar</h4><p>Confirma cantidad, pedido, cliente y que el empaque esté completo antes de marcarlo listo.</p></div></div>
<div class="step"><div class="step-no">5</div><div><h4>Marcar listo</h4><p>${missing.length?`Falta inventario: ${esc(missing.map(x=>x.name).join(', '))}.`:'Al marcar listo se descuenta del inventario lo usado en este pedido.'}</p></div></div>
</div><div class="prep-final"><button class="primary-btn" data-mark-ready="${esc(o.id)}" ${missing.length?'disabled':''}>✓ Pedido preparado / listo</button></div></div>`;}
async function markOrderReady(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const recipe=recipeForOrder(o);try{await db.runTransaction(async tx=>{const invSnap=await tx.get(inventoryRef);const data=invSnap.exists?invSnap.data():{};const items={...(data.items||{})};const missing=missingForRecipe(recipe,items);if(missing.length)throw new Error('Falta inventario: '+missing.map(x=>x.name).join(', '));Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Math.max(0,Number(items[k]||0)-Number(v||0)));});tx.set(inventoryRef,{items,updatedAt:FV.serverTimestamp()},{merge:true});tx.update(ordersRef.doc(id),{deliveryStatus:'listo',inventoryConsumedAt:FV.serverTimestamp(),prepConsumed:recipe,preparedAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()});});toast('Pedido listo. Inventario descontado.');}catch(e){console.error(e);toast(e.message||'No se pudo marcar listo.');}}

function renderInventory(){const q=normalize($('inventorySearch').value),needs=pendingNeeds();const rows=ITEM_KEYS.map(k=>{const item=ITEMS[k],have=currentQty(k),min=minimumQty(k),need=Number(needs[k]||0),low=have<=min||have<need||have-need<=min;return{k,item,have,min,need,low};}).filter(x=>!q||normalize(x.item.name||x.k).includes(q)).sort((a,b)=>Number(b.low)-Number(a.low)||String(a.item.name).localeCompare(String(b.item.name),'es'));const lowCount=lowRows().length;const value=ITEM_KEYS.reduce((sum,k)=>sum+(currentQty(k)/Number(ITEMS[k].factor||1))*purchasePrice(k),0);$('inventorySummary').innerHTML=`<div class="inv-summary-card"><small>PRODUCTOS</small><b>${ITEM_KEYS.length}</b></div><div class="inv-summary-card"><small>BAJOS</small><b>${lowCount}</b></div><div class="inv-summary-card"><small>VALOR APROX.</small><b>${money(value)}</b></div>`;$('inventoryList').innerHTML=rows.length?rows.map(x=>`<div class="inventory-row ${x.low?'low':''}"><div><strong>${esc(x.item.name||x.k)}</strong><small>${esc(x.item.group||'Insumo')}</small></div><div class="inventory-cell"><label>Disponible</label><b class="${x.low?'stock-low':'stock-good'}">${esc(purchaseQtyText(x.k,x.have))}</b></div><div class="inventory-cell inventory-min"><label>Mínimo</label><b>${esc(purchaseQtyText(x.k,x.min))}</b></div><div class="inventory-cell inventory-price"><label>Precio</label><b>${purchasePrice(x.k)>0?money(purchasePrice(x.k)):'—'}</b></div><button class="stock-edit" data-edit-inventory="${esc(x.k)}">Editar</button></div>`).join(''):'<div class="empty-mini">No hay productos con ese nombre.</div>';}
function fillInventoryItems(){const html=ITEM_KEYS.map(k=>`<option value="${esc(k)}">${esc(ITEMS[k].name||k)}</option>`).join('');$('inventoryItem').innerHTML=html;$('purchaseItem').innerHTML=html;}
function openInventoryModal(key=''){const k=key||$('inventoryItem').value||ITEM_KEYS[0];$('inventoryItem').value=k;syncInventoryForm();$('inventoryModal').hidden=false;}
function syncInventoryForm(){const k=$('inventoryItem').value,item=ITEMS[k]||{},factor=Number(item.factor||1),unit=item.purchaseUnit||item.unit||'';$('inventoryQty').value=String(n2(currentQty(k)/factor));$('inventoryMin').value=String(n2(minimumQty(k)/factor));$('inventoryPrice').value=purchasePrice(k)>0?String(n2(purchasePrice(k))):'';$('inventoryUnit').value=unit;$('inventoryPreview').textContent=`Disponible actual: ${purchaseQtyText(k,currentQty(k))} · unidad de compra: ${unit}`;}
async function saveInventory(){const k=$('inventoryItem').value,item=ITEMS[k]||{},factor=Number(item.factor||1),qty=Math.max(0,Number($('inventoryQty').value||0)),min=Math.max(0,Number($('inventoryMin').value||0)),price=Math.max(0,Number($('inventoryPrice').value||0));try{const items={...(state.inv.items||{}),[k]:r3(qty*factor)},mins={...(state.inv.stockMinimums||{}),[k]:r3(min*factor)},prices={...(state.inv.purchasePrices||{})};if(price>0)prices[k]=price;await inventoryRef.set({items,stockMinimums:mins,purchasePrices:prices,updatedAt:FV.serverTimestamp()},{merge:true});$('inventoryModal').hidden=true;toast('Inventario actualizado.');}catch(e){console.error(e);toast('No se pudo guardar el inventario.');}}

function unitOptionsFor(key){const item=ITEMS[key]||{};const list=[];[item.purchaseUnit,item.unit,...COMMON_UNITS].filter(Boolean).forEach(u=>{if(!list.some(x=>normalize(x)===normalize(u)))list.push(u);});return list;}
function unitsEqual(a,b){const A=normalize(a).replace('piezas','pzas').replace('pieza','pza'),B=normalize(b).replace('piezas','pzas').replace('pieza','pza');if(A===B)return true;if(['pza','pzas'].includes(A)&&['pza','pzas'].includes(B))return true;if(['galon','gal'].includes(A)&&['galon','gal'].includes(B))return true;return false;}
function selectedUnitInternal(key,qty,unit){const item=ITEMS[key]||{},internal=normalize(item.unit||''),purchase=item.purchaseUnit||'',factor=Number(item.factor||1),u=normalize(unit);if(unitsEqual(unit,purchase))return r3(qty*factor);if(unitsEqual(unit,item.unit))return r3(qty);if(internal==='lb'){if(u==='oz')return r3(qty/16);if(u==='lb')return r3(qty);}if(internal==='oz'){if(u==='lb')return r3(qty*16);if(u==='oz')return r3(qty);}if(internal==='fl oz'||internal==='floz'){if(['fl oz','floz'].includes(u))return r3(qty);if(u==='galon')return r3(qty*128);if(u==='litro')return r3(qty*33.814);if(u==='ml')return r3(qty*0.033814);}if(['pza','pzas'].includes(internal)&&['pza','pzas'].includes(u))return r3(qty);return null;}
function syncPurchaseItem(){const k=$('purchaseItem').value,item=ITEMS[k]||{},opts=unitOptionsFor(k);$('purchaseUnit').innerHTML=opts.map(u=>`<option value="${esc(u)}">${esc(u)}</option>`).join('');$('purchaseUnit').value=item.purchaseUnit||item.unit||opts[0]||'';$('purchasePrice').value=purchasePrice(k)>0?String(n2(purchasePrice(k))):'';renderPurchasePreview();}
function renderPurchasePreview(){const k=$('purchaseItem').value,qty=Number($('purchaseQty').value||0),unit=$('purchaseUnit').value,price=Number($('purchasePrice').value||0),internal=selectedUnitInternal(k,qty,unit),btn=$('savePurchaseBtn');if(internal===null){$('purchasePreview').innerHTML=`No tengo conversión automática de <b>${esc(unit)}</b> para este producto. Usa ${esc(ITEMS[k]?.purchaseUnit||ITEMS[k]?.unit||'su unidad configurada')}.`;btn.disabled=true;return;}btn.disabled=!(qty>0&&price>0);$('purchasePreview').innerHTML=`Entrarán al inventario <b>${esc(internalUnitText(k,internal))}</b> · Total de compra: <b>${money(qty*price)}</b>`;}
function openPurchaseModal(key=''){if(key)$('purchaseItem').value=key;else $('purchaseItem').value=ITEM_KEYS[0]||'';$('purchaseQty').value='1';$('purchaseStore').value='';syncPurchaseItem();$('purchaseModal').hidden=false;}
async function savePurchase(){const k=$('purchaseItem').value,item=ITEMS[k]||{},qty=Number($('purchaseQty').value||0),unit=$('purchaseUnit').value,unitPrice=Number($('purchasePrice').value||0),store=$('purchaseStore').value.trim(),added=selectedUnitInternal(k,qty,unit);if(!(qty>0)||!(unitPrice>0)||added===null){toast('Revisa cantidad, unidad y precio.');return;}const total=n2(qty*unitPrice),factor=Number(item.factor||1),internalPerSelected=added/qty,pricePerInternal=unitPrice/internalPerSelected,profilePurchasePrice=n2(pricePerInternal*factor);try{const mov=movementsRef.doc();await db.runTransaction(async tx=>{const snap=await tx.get(inventoryRef),data=snap.exists?snap.data():{};const items={...(data.items||{})},prices={...(data.purchasePrices||{})};items[k]=r3(Number(items[k]||0)+added);if(profilePurchasePrice>0)prices[k]=profilePurchasePrice;tx.set(inventoryRef,{items,purchasePrices:prices,updatedAt:FV.serverTimestamp()},{merge:true});tx.set(mov,{type:'purchase',itemKey:k,itemName:item.name||k,qty,unit,unitPrice,total,store,day:localDay(),createdAt:FV.serverTimestamp(),panelTenant:PROFILE.id});});$('purchaseModal').hidden=true;toast('Compra registrada e inventario actualizado.');}catch(e){console.error(e);toast('No se pudo registrar la compra.');}}
function renderPurchases(){const rows=shoppingRows();$('shoppingList').innerHTML=rows.length?rows.slice(0,12).map(x=>`<div class="compact-row"><div><strong>${esc(x.item.name||x.k)}</strong><small>Disponible ${esc(purchaseQtyText(x.k,x.have))}${x.need>0?` · Necesitas ${esc(purchaseQtyText(x.k,x.need))}`:''}</small></div><button class="text-btn" data-buy-item="${esc(x.k)}">Comprar ${esc(purchaseQtyText(x.k,x.lack))}</button></div>`).join(''):'<div class="empty-mini">No hay faltantes para comprar.</div>';const purchases=state.movements.filter(m=>movementType(m)==='purchase').sort((a,b)=>movementMs(b)-movementMs(a)).slice(0,10);$('purchaseHistory').innerHTML=purchases.length?purchases.map(m=>`<div class="compact-row"><div><strong>${esc(m.itemName||m.name||'Compra')}</strong><small>${esc(m.store||'Sin tienda')} · ${esc(fmtDateTime(m.createdAt)||movementDay(m))}</small></div><div class="right">${money(movementTotal(m))}</div></div>`).join(''):'<div class="empty-mini">Todavía no hay compras registradas.</div>';}

function renderDeliveries(){const day=$('deliveryDate').value||localDay();const list=state.orders.filter(o=>!o.deleted&&!isCancelled(o)&&orderDay(o)===day).sort(sortOrders);const pending=list.filter(o=>!isDelivered(o)&&!isReady(o)).length,ready=list.filter(o=>!isDelivered(o)&&isReady(o)&&deliveryStatus(o)!=='en_ruta').length,route=list.filter(o=>deliveryStatus(o)==='en_ruta').length,done=list.filter(isDelivered).length;$('routeSummary').innerHTML=`<span class="route-pill">Pendientes ${pending}</span><span class="route-pill">Listos ${ready}</span><span class="route-pill">En ruta ${route}</span><span class="route-pill">Entregados ${done}</span>`;$('deliveryList').innerHTML=list.length?list.map(deliveryCard).join(''):'<div class="empty-mini">No hay entregas para este día.</div>';}
function deliveryCard(o){const st=statusInfo(o),phone=phoneFromOrder(o),addr=addressFromOrder(o),ds=deliveryStatus(o);let actions='';if(isDelivered(o))actions='';else if(ds==='en_ruta'||ds==='onroute')actions=`<button class="primary-btn" data-deliver-order="${esc(o.id)}">✓ Entregado</button>`;else if(isReady(o))actions=`<button class="primary-btn" data-route-order="${esc(o.id)}">🛵 Salir a entregar</button>`;else actions=`<button class="warning-btn" data-prep-order="${esc(o.id)}">Preparar primero</button>`;if(addr)actions+=`<a class="secondary-btn" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(addr+' '+zipFromOrder(o))}" target="_blank" rel="noopener">Mapa</a>`;return `<article class="delivery-card"><div class="delivery-time">${esc(orderTime(o)||'Sin hora')}</div><div class="delivery-main"><strong>${esc(customerFromOrder(o))}</strong><p>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${esc(productUnit(PRODUCTS[productFromOrder(o)]))}<br>${esc(addr)} ${esc(zipFromOrder(o))}${phone?`<br>${esc(phone)}`:''}</p><span class="badge ${st.cls}" style="margin-top:8px">${st.label}</span></div><div class="delivery-actions">${actions}</div></article>`;}
async function startRoute(id){try{await ordersRef.doc(id).update({deliveryStatus:'en_ruta',routeStartedAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()});toast('Pedido en ruta.');}catch(e){console.error(e);toast('No se pudo cambiar el estado.');}}
async function markDelivered(id){const o=state.orders.find(x=>x.id===id);if(!o)return;try{const mov=movementsRef.doc();await db.runTransaction(async tx=>{const snap=await tx.get(ordersRef.doc(id));if(!snap.exists)throw new Error('Pedido no encontrado');const data=snap.data();const update={status:'entregado',deliveryStatus:'entregado',deliveredAt:FV.serverTimestamp(),updatedAt:FV.serverTimestamp()};if(!data.saleRecordedAt){update.saleRecordedAt=FV.serverTimestamp();tx.set(mov,{type:'sale',orderId:id,customer:customerFromOrder({...o,...data}),total:Number(data.total||orderTotal(o)||0),day:localDay(),createdAt:FV.serverTimestamp(),panelTenant:PROFILE.id});}tx.update(ordersRef.doc(id),update);});toast('Entrega terminada. Venta registrada.');}catch(e){console.error(e);toast('No se pudo cerrar la entrega.');}}

function periodStart(period){const now=new Date();if(period==='today')return new Date(now.getFullYear(),now.getMonth(),now.getDate());if(period==='all')return null;const d=new Date(now);d.setDate(d.getDate()-(Number(period)-1));d.setHours(0,0,0,0);return d;}
function renderMoney(){const period=$('moneyPeriod').value,start=periodStart(period);const rows=state.movements.filter(m=>{if(!start)return true;const d=stampDate(m.createdAt)||stampDate(m.timestamp);if(d)return d>=start;const day=movementDay(m);return day&&day>=localDay(start);}).sort((a,b)=>movementMs(b)-movementMs(a));const sales=rows.filter(m=>movementType(m)==='sale').reduce((s,m)=>s+movementTotal(m),0),purchases=rows.filter(m=>movementType(m)==='purchase').reduce((s,m)=>s+movementTotal(m),0);$('moneySales').textContent=money(sales);$('moneyPurchases').textContent=money(purchases);$('moneyGross').textContent=money(sales-purchases);$('moneyList').innerHTML=rows.length?rows.slice(0,100).map(m=>{const type=movementType(m),sale=type==='sale',title=sale?`Venta${m.customer?' · '+m.customer:''}`:(m.itemName||m.name||'Compra');return `<div class="money-row"><div><strong>${esc(title)}</strong><small>${sale?'Pedido entregado':esc(m.store||'Compra')} · ${esc(fmtDateTime(m.createdAt)||movementDay(m))}</small></div><div class="money-amount ${sale?'sale':'purchase'}">${sale?'+':'−'}${money(movementTotal(m))}</div></div>`;}).join(''):'<div class="empty-mini">No hay movimientos en este periodo.</div>';}

function renderRecipes(){const q=normalize($('recipeSearch').value);const cards=PRODUCT_KEYS.filter(k=>!q||normalize(PRODUCTS[k].name||k).includes(q)).map(k=>{const p=PRODUCTS[k],qty=Number(p.step||1),recipe=recipeFor(k,qty,'');const rows=Object.entries(recipe).filter(([ik,v])=>ITEMS[ik]&&Number(v)>0).map(([ik,v])=>`<div class="recipe-ingredient"><span>${esc(ITEMS[ik].name||ik)}</span><b>${esc(internalUnitText(ik,v))}</b></div>`).join('')||'<div class="recipe-ingredient"><span>Sin ingredientes configurados</span><b>—</b></div>';return `<article class="recipe-card"><h3>${esc(p.name||k)}</h3><p>Receta base para ${n2(qty)} ${esc(productUnit(p))}</p>${rows}</article>`;});$('recipesList').innerHTML=cards.length?cards.join(''):'<div class="empty-mini">No encontré esa receta.</div>';}

function renderAll(){renderBrand();renderDashboard();renderOrders();renderPreparation();renderInventory();renderPurchases();renderDeliveries();renderMoney();renderRecipes();}

function closeModal(id){$(id).hidden=true;}

$('menuBtn').addEventListener('click',openSidebar);$('sidebarBackdrop').addEventListener('click',closeSidebar);$('mainNav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)setView(b.dataset.view);});document.addEventListener('click',e=>{const g=e.target.closest('[data-go-view]');if(g)setView(g.dataset.goView);const c=e.target.closest('[data-close-modal]');if(c)closeModal(c.dataset.closeModal);const edit=e.target.closest('[data-edit-order]');if(edit)openOrderModal(edit.dataset.editOrder);const cancel=e.target.closest('[data-cancel-order]');if(cancel)cancelOrder(cancel.dataset.cancelOrder);const prep=e.target.closest('[data-prep-order]');if(prep){state.selectedPrepId=prep.dataset.prepOrder;setView('preparacion');renderPreparation();}const select=e.target.closest('[data-select-prep]');if(select){state.selectedPrepId=select.dataset.selectPrep;renderPreparation();}const ready=e.target.closest('[data-mark-ready]');if(ready)markOrderReady(ready.dataset.markReady);const inv=e.target.closest('[data-edit-inventory]');if(inv)openInventoryModal(inv.dataset.editInventory);const buy=e.target.closest('[data-buy-item]');if(buy)openPurchaseModal(buy.dataset.buyItem);const route=e.target.closest('[data-route-order]');if(route)startRoute(route.dataset.routeOrder);const delivered=e.target.closest('[data-deliver-order]');if(delivered)markDelivered(delivered.dataset.deliverOrder);});
$('refreshBtn').addEventListener('click',()=>location.reload());$('newOrderBtn').addEventListener('click',()=>openOrderModal());$('quickNewOrder').addEventListener('click',()=>openOrderModal());$('orderSearch').addEventListener('input',renderOrders);$('orderFilters').addEventListener('click',e=>{const b=e.target.closest('[data-order-filter]');if(!b)return;state.orderFilter=b.dataset.orderFilter;renderOrders();});$('orderProduct').addEventListener('change',()=>applyOrderProduct(true));$('orderQty').addEventListener('input',renderOrderPreview);$('orderPrice').addEventListener('input',renderOrderPreview);$('saveOrderBtn').addEventListener('click',saveOrder);
$('inventorySearch').addEventListener('input',renderInventory);$('inventoryAdjustBtn').addEventListener('click',()=>openInventoryModal());$('inventoryItem').addEventListener('change',syncInventoryForm);$('saveInventoryBtn').addEventListener('click',saveInventory);
$('purchaseBtn').addEventListener('click',()=>openPurchaseModal());$('quickPurchase').addEventListener('click',()=>openPurchaseModal());$('purchaseItem').addEventListener('change',syncPurchaseItem);['purchaseQty','purchaseUnit','purchasePrice'].forEach(id=>$(id).addEventListener('input',renderPurchasePreview));$('savePurchaseBtn').addEventListener('click',savePurchase);
$('deliveryDate').addEventListener('change',renderDeliveries);$('moneyPeriod').addEventListener('change',renderMoney);$('recipeSearch').addEventListener('input',renderRecipes);
$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;}));

fillOrderProducts();fillInventoryItems();setToday();setConnection();

inventoryRef.onSnapshot(snap=>{state.inv=snap.exists?{items:{},purchasePrices:{},stockMinimums:{},business:{},...snap.data()}:{items:{},purchasePrices:{},stockMinimums:{},business:{}};state.sync.inventory=true;setConnection();renderAll();},err=>{console.error('inventario',err);setConnection(true);});
ordersRef.onSnapshot(snap=>{state.orders=snap.docs.map(d=>({id:d.id,...d.data()})).filter(belongs);state.sync.orders=true;setConnection();renderAll();},err=>{console.error('pedidos',err);setConnection(true);});
movementsRef.onSnapshot(snap=>{state.movements=snap.docs.map(d=>({id:d.id,...d.data()})).filter(m=>!m.panelTenant||m.panelTenant===PROFILE.id);state.sync.movements=true;setConnection();renderAll();},err=>{console.error('movimientos',err);setConnection(true);});

})();
