(()=>{
'use strict';
const PROFILE=window.PANEL_PROFILE||{};
if(!PROFILE.id||!PROFILE.items||!PROFILE.products)throw new Error('Falta configuración del negocio');
const firebaseConfig={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466',measurementId:'G-1MZS4J9Y4Z'};
firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();
db.settings({experimentalForceLongPolling:true,useFetchStreams:false});
const inventoryRef=db.collection('inventario').doc(PROFILE.inventoryDoc||`panel-${PROFILE.id}`);
const ordersRef=db.collection('pedidos');
const movementsRef=db.collection('movimientos');
const ITEMS=PROFILE.items,PRODUCTS=PROFILE.products,GROUPS=PROFILE.groups||{general:'Productos'};
const EXTRA_TYPES=PROFILE.extraTypes||Object.keys(PRODUCTS);
const STOCK_DEFAULTS=window.PANEL_STOCK_DEFAULTS||{};
const E=id=>document.getElementById(id);
const n2=n=>Number(Number(n||0).toFixed(2));
const r3=n=>Math.round((Number(n||0)+Number.EPSILON)*1000)/1000;
const money=n=>'$'+Number(n||0).toFixed(2);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#39;'}[c]));
const localDay=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const stampDate=v=>{if(!v)return null;if(v.toDate)return v.toDate();const d=new Date(v);return Number.isNaN(d.getTime())?null:d;};
const formatDate=v=>{const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!m)return v||'';return new Date(+m[1],+m[2]-1,+m[3]).toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short'}).replace(/\./g,'');};
const toast=t=>{const x=E('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__panelToast);window.__panelToast=setTimeout(()=>x.classList.remove('show'),2200);};
const productKeys=Object.keys(PRODUCTS),firstProduct=productKeys[0];
let orders=[],movements=[],orderView='today',editOrderId='',orderKind='delivery';
let inv={items:{},purchasePrices:{},stockMinimums:{},prepExtra:{},preparedStock:{},business:{}};
let pendingLogoData='';
function belongs(o){if(PROFILE.id==='el-cubano')return !o?.panelTenant||o.panelTenant==='el-cubano';return o?.panelTenant===PROFILE.id;}
function nextSaturday(){const d=new Date(),add=(6-d.getDay()+7)%7;d.setDate(d.getDate()+add);return localDay(d);}
function itemQtyDisplay(key,internal){const x=ITEMS[key];if(!x)return String(n2(internal));const q=r3(Number(internal||0)/Number(x.factor||1));return `${n2(q)} ${x.purchaseUnit||x.unit||''}`.trim();}
function stockQtyDisplay(key,internal){const x=ITEMS[key];if(!x)return String(n2(internal));return `${n2(internal)} ${x.unit||x.purchaseUnit||''}`.trim();}
function internalFromPurchase(key,qty){return r3(Number(qty||0)*Number(ITEMS[key]?.factor||1));}
function priceFor(key){return Number(inv.purchasePrices?.[key]||0);}
function minimumFor(key){if(Object.prototype.hasOwnProperty.call(inv.stockMinimums||{},key))return r3(Math.max(0,Number(inv.stockMinimums[key]||0)));return r3(Math.max(0,Number(STOCK_DEFAULTS[key]||0)));}
function add(out,key,value){if(!(Number(value)>0))return;out[key]=r3(Number(out[key]||0)+Number(value));}
function productUnit(p){return p.unit||'pza';}
function qtyStep(p){return Number(p.step||1);}
function normalizeQty(p,raw){const step=qtyStep(p);return Math.max(step,Math.round(Number(raw||0)/step)*step);}
function buildRecipe(pkey,qty,soda=''){if(typeof PROFILE.buildRecipe==='function')return PROFILE.buildRecipe(pkey,Number(qty||0),soda,add,r3)||{};const p=PRODUCTS[pkey],out={};Object.entries(p?.recipe||{}).forEach(([k,v])=>add(out,k,Number(v)*Number(qty||0)));if(soda&&ITEMS[soda])add(out,soda,1);return out;}
function productFromOrder(o){const saved=String(o?.manualProductType||o?.productType||'');if(PRODUCTS[saved])return saved;if(typeof PROFILE.resolveProduct==='function'){const k=PROFILE.resolveProduct(o);if(PRODUCTS[k])return k;}return firstProduct;}
function qtyFromOrder(o){if(Number(o?.quantity)>0)return Number(o.quantity);if(typeof PROFILE.resolveQty==='function'){const q=Number(PROFILE.resolveQty(o));if(q>0)return q;}const item=o?.items?.[0]||{};return Number(item.qty||0);}
function titleFromOrder(o){return o.productName||o.items?.[0]?.name||PRODUCTS[productFromOrder(o)]?.name||'Pedido';}
function recipeForOrder(o){const out={};Object.entries(o?.recipe||{}).forEach(([k,v])=>{if(ITEMS[k])out[k]=r3(Number(v||0));});if(Object.keys(out).length)return out;return buildRecipe(productFromOrder(o),qtyFromOrder(o),o.sodaKey||'');}
function remainingRecipe(o){const base=recipeForOrder(o),used=o?.prepConsumed||{},out={};Object.entries(base).forEach(([k,v])=>{const left=Math.max(0,r3(Number(v)-Number(used[k]||0)));if(left>0)out[k]=left;});return out;}
function pendingProductionOrders(){return orders.filter(o=>!o.deleted&&!o.directSale&&!['entregado','cancelado'].includes(String(o.status||''))&&!['listo','en_ruta'].includes(String(o.deliveryStatus||''))&&!o.inventoryConsumedAt);}
function openDeliveryOrders(){return orders.filter(o=>!o.deleted&&!o.directSale&&!['entregado','cancelado'].includes(String(o.status||'')));}
function pendingNeeds(){const out={};pendingProductionOrders().forEach(o=>Object.entries(remainingRecipe(o)).forEach(([k,v])=>add(out,k,v)));Object.entries(inv.prepExtra||{}).forEach(([pkey,qty])=>{if(Number(qty)>0&&PRODUCTS[pkey])Object.entries(buildRecipe(pkey,qty,'')).forEach(([k,v])=>add(out,k,v));});return out;}
function orderedSummary(){const out={};pendingProductionOrders().forEach(o=>add(out,productFromOrder(o),qtyFromOrder(o)));return out;}
function totalSummary(){const out={...orderedSummary()};Object.entries(inv.prepExtra||{}).forEach(([k,v])=>add(out,k,v));return out;}
function summaryText(sum){const parts=Object.entries(sum||{}).filter(([k,v])=>PRODUCTS[k]&&Number(v)>0).map(([k,v])=>`${PRODUCTS[k].short||PRODUCTS[k].name} ${n2(v)} ${productUnit(PRODUCTS[k])}`);return parts.length?parts.join(' · '):'0';}
function shortages(){const need=pendingNeeds(),rows=[];Object.entries(ITEMS).forEach(([k,item])=>{const have=r3(Number(inv.items?.[k]||0)),required=r3(Number(need[k]||0)),lack=r3(Math.max(0,required-have));if(lack>0)rows.push({k,item,have,required,lack});});return rows;}
function stockAlerts(){const need=pendingNeeds(),rows=[];Object.entries(ITEMS).forEach(([k,item])=>{const have=r3(Number(inv.items?.[k]||0)),required=r3(Number(need[k]||0)),minimum=minimumFor(k),projected=r3(have-required),lack=r3(Math.max(0,required-have));if(lack>0)rows.push({k,item,have,required,minimum,projected,lack,status:'FALTANTE'});else if(minimum>0&&projected<=minimum)rows.push({k,item,have,required,minimum,projected,lack:0,status:'FALTANTE'});});return rows;}
function missingNames(recipe,items){return Object.entries(recipe||{}).filter(([k,v])=>ITEMS[k]&&Number(items?.[k]||0)<Number(v||0)).map(([k])=>ITEMS[k].name).join(', ');}
function recipeCost(recipe){let total=0,complete=true;Object.entries(recipe||{}).forEach(([k,v])=>{const item=ITEMS[k];if(!item)return;const price=priceFor(k);if(!(price>0)){complete=false;return;}total+=(Number(v||0)/Number(item.factor||1))*price;});return {cost:n2(total),complete};}
function setScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go]');if(b)setScreen(b.dataset.go);const c=e.target.closest('[data-close]');if(c){const m=E(c.dataset.close);if(m)m.hidden=true;}});
function renderBrand(){const b=inv.business||{},name=b.name||PROFILE.name||'Mi negocio',logo=b.logoDataUrl||PROFILE.defaultLogo||'';E('businessName').textContent=name;document.title=`Panel · ${name}`;const img=E('businessLogo');if(logo){img.src=logo;img.hidden=false;}else{img.removeAttribute('src');img.hidden=true;}E('settingsName').value=b.name||PROFILE.name||'';E('settingsPhone').value=b.phone||PROFILE.phone||'';const p=E('settingsLogoPreview');if(p){if(logo){p.src=logo;p.hidden=false;}else p.hidden=true;}}
function renderHome(){const s=stockAlerts(),salesToday=movements.filter(m=>m.type==='sale'&&m.day===localDay()).reduce((a,m)=>a+Number(m.total||0),0);E('sumOrders').textContent=String(openDeliveryOrders().length);E('sumPrep').textContent=summaryText(totalSummary());E('sumBuy').textContent=String(s.length);E('sumSales').textContent=money(salesToday);}
function orderMatches(o){const status=String(o.status||'confirmado'),day=String(o.deliveryDate||''),today=localDay();if(orderView==='completed')return status==='entregado';if(orderView==='cancelled')return status==='cancelado';if(status==='entregado'||status==='cancelado')return false;if(orderView==='upcoming')return day>today;return !day||day<=today;}
function renderOrders(){document.querySelectorAll('[data-order-view]').forEach(b=>b.classList.toggle('active',b.dataset.orderView===orderView));const list=orders.filter(o=>!o.deleted&&orderMatches(o));E('ordersList').innerHTML=list.length?list.map(o=>{const p=PRODUCTS[productFromOrder(o)]||{},stage=String(o.deliveryStatus||'por_preparar'),status=String(o.status||'confirmado'),badge=status==='entregado'?'ENTREGADO':status==='cancelado'?'CANCELADO':stage==='listo'?'LISTO':stage==='en_ruta'?'EN RUTA':'CONFIRMADO',canEdit=o.manualOrder&&!o.inventoryConsumedAt&&!['listo','en_ruta','entregado','cancelado'].includes(stage)&&!['entregado','cancelado'].includes(status);return `<article class="order-card"><div class="order-date">${esc(formatDate(o.deliveryDate))}${o.time?` · ${esc(o.time)}`:''}</div><div class="row-head"><div><strong>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${esc(productUnit(p))}</strong><small>${esc(o.customer||'Cliente')}${o.phone?' · '+esc(o.phone):''}<br>${o.address?esc(o.address):''}${o.zip?' · '+esc(o.zip):''}<br>Venta ${money(o.total)}</small></div><span class="badge ${stage==='listo'?'ready':stage==='en_ruta'?'route':status==='entregado'?'done':''}">${badge}</span></div>${canEdit?`<div class="card-actions"><button class="secondary" data-edit-order="${esc(o.id)}">✏️ Editar</button><button class="danger" data-cancel-order="${esc(o.id)}">Cancelar</button></div>`:''}</article>`;}).join(''):'<div class="empty">No hay pedidos aquí.</div>';}
E('orderFilters').addEventListener('click',e=>{const b=e.target.closest('[data-order-view]');if(!b)return;orderView=b.dataset.orderView;renderOrders();});
E('ordersList').addEventListener('click',async e=>{const ed=e.target.closest('[data-edit-order]');if(ed)return openOrder(ed.dataset.editOrder);const ca=e.target.closest('[data-cancel-order]');if(ca){const o=orders.find(x=>x.id===ca.dataset.cancelOrder);if(!o||!confirm(`¿Cancelar el pedido de ${o.customer||'este cliente'}?`))return;await ordersRef.doc(o.id).update({status:'cancelado',deliveryStatus:'cancelado',cancelledAt:firebase.firestore.FieldValue.serverTimestamp()});toast('Pedido cancelado');}});
function fillSelects(){E('orderProduct').innerHTML=Object.entries(PRODUCTS).map(([k,p])=>`<option value="${k}">${esc(p.name)}</option>`).join('');E('inventoryItem').innerHTML=Object.entries(ITEMS).map(([k,x])=>`<option value="${k}">${esc(x.name)}</option>`).join('');E('purchaseItem').innerHTML=E('inventoryItem').innerHTML;const sodas=PROFILE.sodas||[];E('orderSoda').innerHTML=['',...sodas].map(k=>`<option value="${k}">${k?esc(ITEMS[k]?.name||k):'Sin refresco'}</option>`).join('');const times=[];const fmt=m=>{let h=Math.floor(m/60),mi=m%60,p=h>=12?'p. m.':'a. m.';h=h%12||12;return `${h}:${String(mi).padStart(2,'0')} ${p}`;};for(let m=12*60;m<20*60;m+=20)times.push(`${fmt(m)}–${fmt(m+20)}`);E('orderTime').innerHTML=times.map(x=>`<option>${x}</option>`).join('');}
function setOrderKind(k){orderKind=k;document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('active',b.dataset.kind===k));document.querySelectorAll('.delivery-only').forEach(x=>x.style.display=k==='delivery'?'':'none');updateOrderPreview();}
E('orderKindBtns').addEventListener('click',e=>{const b=e.target.closest('[data-kind]');if(b)setOrderKind(b.dataset.kind);});
function syncProductForm(reset=false){const p=PRODUCTS[E('orderProduct').value]||PRODUCTS[firstProduct],step=qtyStep(p);E('orderQty').min=String(step);E('orderQty').step=String(step);if(Number(E('orderQty').value)<step)E('orderQty').value=String(step);if(reset)E('orderPrice').value=p.price||'';E('orderSoda').disabled=!(PROFILE.sodas||[]).length;updateOrderPreview();}
function updateOrderPreview(){const pkey=E('orderProduct').value,p=PRODUCTS[pkey]||PRODUCTS[firstProduct],qty=Number(E('orderQty').value||0),price=Number(E('orderPrice').value||0),c=recipeCost(buildRecipe(pkey,qty,E('orderSoda').value));E('orderPreview').innerHTML=`<b>${esc(p.name)}</b><br>${n2(qty)} ${esc(productUnit(p))} × ${money(price)} = <b>${money(qty*price)}</b><br>${c.complete?`Costo ${money(c.cost)} · Ganancia ${money(qty*price-c.cost)}`:'Agrega precios de compra para calcular la ganancia.'}`;}
['orderProduct','orderQty','orderPrice','orderSoda'].forEach(id=>E(id).addEventListener('input',()=>id==='orderProduct'?syncProductForm(true):updateOrderPreview()));
function openOrder(id=''){editOrderId=id;const o=orders.find(x=>x.id===id),pkey=o?productFromOrder(o):firstProduct,p=PRODUCTS[pkey];E('orderModalTitle').textContent=id?'Editar pedido':'Nuevo pedido';E('orderProduct').value=pkey;E('orderCustomer').value=o?.customer||'';E('orderPhone').value=o?.phone||'';E('orderAddress').value=o?.address||'';E('orderZip').value=o?.zip||'';E('orderDate').value=o?.deliveryDate||nextSaturday();E('orderTime').value=o?.time||E('orderTime').options[0]?.value||'';E('orderQty').value=String(o?qtyFromOrder(o):qtyStep(p));E('orderPrice').value=String(o?.unitPrice??o?.items?.[0]?.unitPrice??p.price??'');E('orderPayment').value=o?.payment||'Al recibir';E('orderSource').value=o?.manualSource||'WhatsApp';E('orderSoda').value=o?.sodaKey||'';E('orderNotes').value=o?.notes&&o.notes!=='Sin notas'?o.notes:'';setOrderKind(o?.directSale?'direct':'delivery');syncProductForm(false);E('orderModal').hidden=false;}
E('newOrderBtn').onclick=()=>openOrder();
E('saveOrderBtn').onclick=async()=>{const pkey=E('orderProduct').value,p=PRODUCTS[pkey],qty=normalizeQty(p,E('orderQty').value),price=Math.max(0,Number(E('orderPrice').value||0)),customer=E('orderCustomer').value.trim()||'Cliente',phone=E('orderPhone').value.trim(),address=E('orderAddress').value.trim(),zip=E('orderZip').value.trim(),deliveryDate=E('orderDate').value,time=E('orderTime').value;if(orderKind==='delivery'&&(!phone||!address||!zip||!deliveryDate||!time))return alert('Faltan teléfono, dirección, ZIP, día u horario.');if(orderKind==='delivery'){const conflict=orders.find(o=>o.id!==editOrderId&&o.status!=='cancelado'&&o.status!=='entregado'&&!o.directSale&&o.deliveryDate===deliveryDate&&o.time===time);if(conflict)return alert('Ese horario ya tiene otra entrega.');}const recipe=buildRecipe(pkey,qty,E('orderSoda').value),calc=recipeCost(recipe),total=n2(qty*price),cost=calc.complete?calc.cost:null,profit=calc.complete?n2(total-calc.cost):null,stamp=firebase.firestore.FieldValue.serverTimestamp(),data={panelTenant:PROFILE.id,customer,phone:orderKind==='direct'?'':phone,address:orderKind==='direct'?'':address,zip:orderKind==='direct'?'':zip,deliveryDate:orderKind==='direct'?localDay():deliveryDate,time:orderKind==='direct'?'Venta directa':time,payment:E('orderPayment').value,notes:E('orderNotes').value.trim()||'Sin notas',source:'app-clientes',manualSource:E('orderSource').value,items:[{productId:p.id||pkey,name:p.name,qty,unitPrice:price,lineTotal:total}],recipe,total,cost,profit,manualOrder:true,manualProductType:pkey,productType:pkey,productName:p.name,quantity:qty,quantityUnit:productUnit(p),unitPrice:price,sodaKey:E('orderSoda').value||''};E('saveOrderBtn').disabled=true;try{if(editOrderId){await ordersRef.doc(editOrderId).update({...data,editedAt:stamp});toast('Pedido actualizado');}else if(orderKind==='direct'){await registerDirectSale(data,pkey,qty);}else{const ref=ordersRef.doc();await ref.set({id:ref.id,...data,status:'confirmado',deliveryStatus:'por_preparar',directSale:false,confirmedAt:stamp,createdAt:stamp,createdAtClient:new Date().toISOString()});toast('Pedido guardado');}E('orderModal').hidden=true;editOrderId='';}catch(err){console.error(err);alert(err.message||'No se pudo guardar.');}finally{E('saveOrderBtn').disabled=false;}};
async function registerDirectSale(data,pkey,qty){const ref=ordersRef.doc(),mr=movementsRef.doc(),stamp=firebase.firestore.FieldValue.serverTimestamp();await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.exists?s.data():{},items={...(d.items||{})},prepared={...(d.preparedStock||{})};if(Number(prepared[pkey]||0)>=qty)prepared[pkey]=r3(Number(prepared[pkey]||0)-qty);else{const missing=missingNames(data.recipe,items);if(missing)throw new Error(`No alcanza lo que tienes. Faltan: ${missing}.`);Object.entries(data.recipe||{}).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v||0));});}tx.set(inventoryRef,{items,preparedStock:prepared,updatedAt:stamp},{merge:true});tx.set(ref,{id:ref.id,...data,status:'entregado',deliveryStatus:'entregado',directSale:true,createdAt:stamp,deliveredAt:stamp,createdAtClient:new Date().toISOString()});tx.set(mr,{panelTenant:PROFILE.id,type:'sale',date:stamp,day:localDay(),name:`Venta directa · ${data.productName}`,orderId:ref.id,total:data.total,cost:data.cost,profit:data.profit,payment:data.payment});});toast('Venta registrada');}
function renderPrepare(){const ordered=orderedSummary(),extra=inv.prepExtra||{},total=totalSummary();E('prepTotals').innerHTML=`<div class="prep-summary-box"><small>PEDIDOS</small><b>${esc(summaryText(ordered))}</b></div><div class="prep-summary-box"><small>EXTRA</small><b>${esc(summaryText(extra))}</b></div><div class="prep-summary-box"><small>TOTAL</small><b>${esc(summaryText(total))}</b></div>`;E('extraInputs').innerHTML=EXTRA_TYPES.map(k=>{const p=PRODUCTS[k];return `<label class="extra-item"><span>${esc(p.short||p.name)}</span><input data-extra-key="${k}" type="number" min="0" step="${qtyStep(p)}" value="${n2(extra[k]||0)}"></label>`;}).join('');const list=pendingProductionOrders();E('prepareOrders').innerHTML=list.length?list.map(o=>{const p=PRODUCTS[productFromOrder(o)]||{};return `<article class="order-card"><div class="row-head"><div><strong>${esc(titleFromOrder(o))} · ${n2(qtyFromOrder(o))} ${esc(productUnit(p))}</strong><small>${esc(o.customer||'Cliente')} · ${esc(formatDate(o.deliveryDate))} ${o.time?`· ${esc(o.time)}`:''}</small></div><span class="badge">CONFIRMADO</span></div><div class="card-actions"><button class="primary" data-prepared-order="${esc(o.id)}">✓ Ya quedó</button></div></article>`;}).join(''):'<div class="empty">No hay nada pendiente de preparar.</div>';}
E('saveExtraBtn').onclick=async()=>{const next={};document.querySelectorAll('[data-extra-key]').forEach(i=>{const p=PRODUCTS[i.dataset.extraKey],raw=Math.max(0,Number(i.value||0)),step=qtyStep(p);next[i.dataset.extraKey]=Math.round(raw/step)*step;});await inventoryRef.set({prepExtra:next,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});toast('Extra guardado');};
E('prepareExtraBtn').onclick=async()=>{const active=Object.entries(inv.prepExtra||{}).filter(([k,v])=>PRODUCTS[k]&&Number(v)>0);if(!active.length)return alert('No tienes extra marcado.');const recipe={};active.forEach(([k,v])=>Object.entries(buildRecipe(k,v,'')).forEach(([ik,iv])=>add(recipe,ik,iv)));try{await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},prepared={...(d.preparedStock||{})},missing=missingNames(recipe,items);if(missing)throw new Error(`Faltan: ${missing}.`);Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v));});active.forEach(([k,v])=>prepared[k]=r3(Number(prepared[k]||0)+Number(v)));const cleared={...(d.prepExtra||{})};active.forEach(([k])=>cleared[k]=0);tx.set(inventoryRef,{items,preparedStock:prepared,prepExtra:cleared,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});});toast('Extra preparado');}catch(err){alert(err.message||'No se pudo registrar.');}};
E('prepareOrders').addEventListener('click',async e=>{const b=e.target.closest('[data-prepared-order]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.preparedOrder);if(!o)return;try{await markOrderPrepared(o);toast('Pedido listo');}catch(err){alert(err.message||'No se pudo preparar.');}});
async function markOrderPrepared(o){await db.runTransaction(async tx=>{const or=ordersRef.doc(o.id),os=await tx.get(or);if(!os.exists)throw new Error('El pedido ya no existe.');const current=os.data();if(current.inventoryConsumedAt||['listo','en_ruta','entregado'].includes(String(current.deliveryStatus||'')))return;const recipe=remainingRecipe({...current,id:o.id}),s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},missing=missingNames(recipe,items);if(missing)throw new Error(`Faltan: ${missing}.`);Object.entries(recipe).forEach(([k,v])=>{if(ITEMS[k])items[k]=r3(Number(items[k]||0)-Number(v));});const stamp=firebase.firestore.FieldValue.serverTimestamp();tx.set(inventoryRef,{items,updatedAt:stamp},{merge:true});tx.update(or,{status:'confirmado',deliveryStatus:'listo',preparedAt:stamp,inventoryConsumedAt:stamp});});}
function renderStockAlerts(){const list=E('stockAlertsList'),count=E('stockAlertCount');if(!list||!count)return;const rows=stockAlerts();count.textContent=String(rows.length);list.innerHTML=rows.length?rows.map(x=>`<div class="shopping-row"><div><strong>${esc(x.item.name)}</strong><small>Cantidad disponible: ${esc(stockQtyDisplay(x.k,x.have))}</small></div><div class="shopping-qty">${esc(x.status)}</div></div>`).join(''):'<div class="empty">✅ No hay faltantes.</div>';}
function renderBuy(){const rows=shortages();E('shortageCount').textContent=String(rows.length);E('shoppingList').innerHTML=rows.length?rows.map(x=>`<div class="shopping-row" data-buy-key="${x.k}"><div><strong>${esc(x.item.name)}</strong><small>Necesitas ${esc(itemQtyDisplay(x.k,x.required))} · Tienes ${esc(itemQtyDisplay(x.k,x.have))}</small></div><div class="shopping-qty">Faltan ${esc(itemQtyDisplay(x.k,x.lack))}</div></div>`).join(''):'<div class="empty">✅ No falta producto para la preparación.</div>';E('inventoryList').innerHTML=Object.entries(GROUPS).map(([g,label])=>{const rows=Object.entries(ITEMS).filter(([,x])=>x.group===g).map(([k,x])=>`<div class="inventory-row" data-inv-key="${k}"><div><strong>${esc(x.name)}</strong><small>${priceFor(k)>0?`Precio ${money(priceFor(k))} / ${esc(x.purchaseUnit||x.unit)}`:'Sin precio'}${minimumFor(k)>0?` · Mínimo ${esc(stockQtyDisplay(k,minimumFor(k)))}`:''}</small></div><b>${esc(stockQtyDisplay(k,inv.items?.[k]||0))}</b></div>`).join('');return rows?`<div class="inventory-group">${esc(label)}</div>${rows}`:'';}).join('');}
E('shoppingList').addEventListener('click',e=>{const r=e.target.closest('[data-buy-key]');if(r)openPurchase(r.dataset.buyKey);});E('inventoryList').addEventListener('click',e=>{const r=e.target.closest('[data-inv-key]');if(r)openInventory(r.dataset.invKey);});E('reviewInventoryBtn').onclick=()=>openInventory(Object.keys(ITEMS)[0]);E('registerPurchaseBtn').onclick=()=>openPurchase(shortages()[0]?.k||Object.keys(ITEMS)[0]);
function openInventory(key){E('inventoryItem').value=key;syncInventoryModal();E('inventoryModal').hidden=false;}
function syncInventoryModal(){const k=E('inventoryItem').value,x=ITEMS[k],internal=Number(inv.items?.[k]||0),minimum=minimumFor(k);E('inventoryQty').value=String(n2(internal));E('inventoryPrice').value=priceFor(k)||'';E('inventoryUnitHint').textContent=`(${x.unit||x.purchaseUnit})`;if(E('inventoryMin'))E('inventoryMin').value=String(n2(minimum));if(E('inventoryMinUnitHint'))E('inventoryMinUnitHint').textContent=`(${x.unit||x.purchaseUnit})`;E('inventoryPreview').innerHTML=`Cantidad disponible <b>${esc(stockQtyDisplay(k,internal))}</b>${minimum>0?` · Stock mínimo <b>${esc(stockQtyDisplay(k,minimum))}</b>`:''} · Precio por <b>${esc(x.purchaseUnit||x.unit)}</b>.`;}
E('inventoryItem').addEventListener('change',syncInventoryModal);E('saveInventoryBtn').onclick=async()=>{const k=E('inventoryItem').value,qty=Math.max(0,Number(E('inventoryQty').value||0)),price=Math.max(0,Number(E('inventoryPrice').value||0)),minimum=E('inventoryMin')?Math.max(0,Number(E('inventoryMin').value||0)):minimumFor(k),updates={};updates[`items.${k}`]=r3(qty);updates[`purchasePrices.${k}`]=price;updates[`stockMinimums.${k}`]=r3(minimum);updates.updatedAt=firebase.firestore.FieldValue.serverTimestamp();await inventoryRef.set(updates,{merge:true});E('inventoryModal').hidden=true;toast('Guardado');};
function openPurchase(key){E('purchaseItem').value=key;E('purchaseQty').value='1';E('purchaseCost').value='';E('purchaseStore').value='';syncPurchaseModal();E('purchaseModal').hidden=false;}
function syncPurchaseModal(){const k=E('purchaseItem').value,x=ITEMS[k],q=Number(E('purchaseQty').value||0),c=Number(E('purchaseCost').value||0);E('purchaseUnit').value=x.purchaseUnit||x.unit;E('purchasePreview').innerHTML=`Se agregarán <b>${esc(stockQtyDisplay(k,internalFromPurchase(k,q)))}</b>${c>0?` · ${money(c)} total`:''}.`;}
['purchaseItem','purchaseQty','purchaseCost'].forEach(id=>E(id).addEventListener('input',syncPurchaseModal));E('savePurchaseBtn').onclick=async()=>{const k=E('purchaseItem').value,x=ITEMS[k],qty=Number(E('purchaseQty').value||0),cost=Math.max(0,Number(E('purchaseCost').value||0)),store=E('purchaseStore').value.trim()||'Sin tienda';if(!(qty>0))return alert('Escribe cuánto compraste.');await db.runTransaction(async tx=>{const s=await tx.get(inventoryRef),d=s.data()||{},items={...(d.items||{})},prices={...(d.purchasePrices||{})},mr=movementsRef.doc(),stamp=firebase.firestore.FieldValue.serverTimestamp(),internal=internalFromPurchase(k,qty);items[k]=r3(Number(items[k]||0)+internal);if(cost>0)prices[k]=n2(cost/qty);tx.set(inventoryRef,{items,purchasePrices:prices,updatedAt:stamp},{merge:true});tx.set(mr,{panelTenant:PROFILE.id,type:'purchase',date:stamp,day:localDay(),name:x.name,itemKey:k,qty,unit:x.purchaseUnit||x.unit,internalQty:internal,cost,store});});E('purchaseModal').hidden=true;toast('Compra guardada');};
function timeMinutes(v){const m=String(v||'').toLowerCase().match(/(\d{1,2}):(\d{2})\s*(a\.?\s*m\.?|p\.?\s*m\.?)?/);if(!m)return 9999;let h=+m[1],mi=m%60,p=(m[3]||'').replace(/\s|\./g,'');if(p==='pm'&&h<12)h+=12;if(p==='am'&&h===12)h=0;return h*60+mi;}
function renderDeliveries(){const day=E('deliveryDate').value||localDay();E('deliveryDate').value=day;const list=orders.filter(o=>!o.deleted&&!o.directSale&&o.deliveryDate===day&&o.status!=='cancelado').sort((a,b)=>timeMinutes(a.time)-timeMinutes(b.time));E('deliveryList').innerHTML=list.length?list.map(o=>{const stage=o.status==='entregado'?'entregado':String(o.deliveryStatus||'por_preparar'),action=stage==='listo'?`<button class="primary" data-delivery-action="en_ruta" data-id="${o.id}">🛵 En ruta</button>`:stage==='en_ruta'?`<button class="primary" data-delivery-action="entregado" data-id="${o.id}">✅ Entregado</button>`:stage==='entregado'?'<span class="badge done">FINALIZADO</span>':'<span class="badge">FALTA PREPARAR</span>';return `<article class="delivery-card"><div class="delivery-time">${esc(o.time||'Sin horario')}</div><div class="row-head"><div><strong>${esc(o.customer||'Cliente')} · ${esc(titleFromOrder(o))}</strong><small>${esc(o.address||'')}${o.zip?' · '+esc(o.zip):''}<br>${esc(o.phone||'')}</small></div></div><div class="card-actions"><button class="secondary" data-map="${esc(o.address||'')}">📍 Mapa</button>${action}</div></article>`;}).join(''):'<div class="empty">No hay entregas para este día.</div>';}
E('deliveryDate').addEventListener('change',renderDeliveries);E('deliveryList').addEventListener('click',async e=>{const map=e.target.closest('[data-map]');if(map){window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(map.dataset.map)}`,'_blank');return;}const b=e.target.closest('[data-delivery-action]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.id);if(!o)return;if(b.dataset.deliveryAction==='en_ruta'){await ordersRef.doc(o.id).update({deliveryStatus:'en_ruta',routeUpdatedAt:firebase.firestore.FieldValue.serverTimestamp()});toast('En ruta');}else await markDelivered(o);});
async function markDelivered(o){const existing=movements.find(m=>m.type==='sale'&&m.orderId===o.id),mr=existing?null:movementsRef.doc(),stamp=firebase.firestore.FieldValue.serverTimestamp();let cost=o.cost,profit=o.profit;if(cost==null){const c=recipeCost(recipeForOrder(o));if(c.complete){cost=c.cost;profit=n2(Number(o.total||0)-cost);}}await db.runTransaction(async tx=>{const or=ordersRef.doc(o.id),os=await tx.get(or);if(!os.exists)throw new Error('El pedido ya no existe.');tx.update(or,{status:'entregado',deliveryStatus:'entregado',deliveredAt:stamp});if(mr)tx.set(mr,{panelTenant:PROFILE.id,type:'sale',date:stamp,day:localDay(),name:titleFromOrder(o),orderId:o.id,total:Number(o.total||0),cost:cost??null,profit:profit??null,payment:o.payment||''});});toast('Entrega finalizada');}
function renderMoney(){const today=localDay(),sales=movements.filter(m=>m.type==='sale'&&m.day===today),purchases=movements.filter(m=>m.type==='purchase'&&m.day===today),salesToday=sales.reduce((a,m)=>a+Number(m.total||0),0),purchasesToday=purchases.reduce((a,m)=>a+Number(m.cost||0),0),profits=sales.filter(m=>m.profit!==null&&m.profit!==undefined&&Number.isFinite(Number(m.profit))),profitKnown=profits.length===sales.length,profitToday=profits.reduce((a,m)=>a+Number(m.profit||0),0),balance=salesToday-purchasesToday;E('moneyMetrics').innerHTML=`<div class="money-box"><small>Ventas hoy</small><b>${money(salesToday)}</b></div><div class="money-box"><small>Compras hoy</small><b>${money(purchasesToday)}</b></div><div class="money-box"><small>Ganancia hoy</small><b>${profitKnown?money(profitToday):'—'}</b></div><div class="money-box"><small>Saldo hoy</small><b>${money(balance)}</b></div>`;E('moneyList').innerHTML=movements.slice(0,50).map(m=>{const d=stampDate(m.date),when=d?d.toLocaleString('es-MX',{dateStyle:'short',timeStyle:'short'}):m.day||'';return m.type==='sale'?`<div class="movement-row sale"><div><strong>Venta · ${esc(m.name||'Pedido')}</strong><small>${esc(when)}</small></div><div class="amount">${money(m.total)}</div></div>`:`<div class="movement-row purchase"><div><strong>Compra · ${esc(m.name||'Producto')}</strong><small>${esc(m.store||'')} · ${esc(when)}</small></div><div class="amount">-${money(m.cost)}</div></div>`;}).join('')||'<div class="empty">Todavía no hay movimientos.</div>';}
async function imageToDataUrl(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=512,scale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);resolve(c.toDataURL('image/webp',.86));};img.onerror=reject;img.src=r.result;};r.onerror=reject;r.readAsDataURL(file);});}
E('settingsLogoFile').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{pendingLogoData=await imageToDataUrl(f);E('settingsLogoPreview').src=pendingLogoData;E('settingsLogoPreview').hidden=false;}catch{alert('No pude leer esa imagen.');}});
E('saveBusinessBtn').onclick=async()=>{const business={...(inv.business||{}),name:E('settingsName').value.trim()||PROFILE.name||'Mi negocio',phone:E('settingsPhone').value.trim()};if(pendingLogoData)business.logoDataUrl=pendingLogoData;await inventoryRef.set({business,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});pendingLogoData='';toast('Negocio guardado');setScreen('home');};
E('removeLogoBtn').onclick=async()=>{const business={...(inv.business||{}),logoDataUrl:''};await inventoryRef.set({business,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});pendingLogoData='';toast('Logo quitado');};
function renderAll(){renderBrand();renderHome();renderOrders();renderPrepare();renderStockAlerts();renderBuy();renderDeliveries();renderMoney();}
function init(){fillSelects();E('todayPill').textContent=new Date().toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short',year:'numeric'});E('deliveryDate').value=localDay();syncProductForm(true);renderAll();}
init();
inventoryRef.onSnapshot(async s=>{if(!s.exists){await inventoryRef.set({items:{},purchasePrices:{},stockMinimums:{},prepExtra:{},preparedStock:{},business:{name:PROFILE.name||'Mi negocio'},updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});return;}const d=s.data()||{};inv={items:{...(d.items||{})},purchasePrices:{...(d.purchasePrices||{})},stockMinimums:{...(d.stockMinimums||{})},prepExtra:{...(d.prepExtra||{})},preparedStock:{...(d.preparedStock||{})},business:{...(d.business||{})}};E('syncBadge').textContent='En vivo';E('syncBadge').classList.add('ok');renderAll();},err=>{console.error(err);E('syncBadge').textContent='Sin conexión';});
ordersRef.onSnapshot(s=>{orders=s.docs.map(d=>({id:d.id,...d.data()})).filter(belongs).sort((a,b)=>{const da=stampDate(a.createdAt)||new Date(a.createdAtClient||0),dbb=stampDate(b.createdAt)||new Date(b.createdAtClient||0);return dbb-da;});renderAll();},console.error);
movementsRef.orderBy('date','desc').limit(400).onSnapshot(s=>{movements=s.docs.map(d=>({id:d.id,...d.data()})).filter(belongs);renderAll();},err=>{console.error(err);movements=[];renderAll();});
})();
