let initializeApp,getFirestore,doc,getDoc,setDoc,onSnapshot,serverTimestamp,collection,updateDoc,getDocs;
let firestore=null,firebaseLoading=null,cloudConnecting=false,cloudRetryTimer=null;

const firebaseConfig={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466',measurementId:'G-1MZS4J9Y4Z'};
const $=s=>document.querySelector(s),LOCAL_KEY='chava-panel-v3',CLOUD_DOC=['panel_v2','principal_v3'],DEVICE_ID_KEY='chava-panel-device-v3',VERSION=4,BASE_RECIPE_ID='base-mixto-1lb',RECIPE_REV=3;
const UNITS=['oz','lb','fl oz','ml','g','kg','pza','bolsa','paquete','botella','manojo','charola','caja','otro'];
const BASE_ITEMS=[
 ['fish','Pescado','oz','Ingredientes'],['shrimp','Camarón','oz','Ingredientes'],['tomato','Tomate','oz','Ingredientes'],['onion','Cebolla','oz','Ingredientes'],['cucumber','Pepino','oz','Ingredientes'],['cilantro','Cilantro','oz','Ingredientes'],
 ['lemonJuice','Jugo de limón','fl oz','Salsas y líquidos'],['clamato','Clamato','fl oz','Salsas y líquidos'],['blackSauce','Salsa negra','fl oz','Salsas y líquidos'],['hotSauce','Salsa picante','fl oz','Salsas y líquidos'],
 ['tostadas','Tostadas','pza','Empaque y desechables'],['container16','Contenedor 16 oz','pza','Empaque y desechables'],['lid16','Tapa 16 oz','pza','Empaque y desechables'],['container12','Contenedor 12 oz','pza','Empaque y desechables'],['lid12','Tapa 12 oz','pza','Empaque y desechables'],['spoon','Cuchara','pza','Empaque y desechables'],['napkins','Servilleta','pza','Empaque y desechables'],['saltPacket','Sal','pza','Empaque y desechables'],['bag10x20','Bolsa 10 × 20 cm','pza','Empaque y desechables'],['tshirtBagSmall','Bolsa camiseta chica','pza','Empaque y desechables'],['tshirtBagMedium','Bolsa camiseta mediana','pza','Empaque y desechables']
];
const APP_KEYS=[...BASE_ITEMS.map(x=>x[0]),'octopus','lime','habaneroSauce','coca','cokezero','sprite','drpepper','bigred','fanta'];
const BASE_Q={fish:4,shrimp:3,tomato:3,onion:.75,cucumber:2,cilantro:.5,lemonJuice:1,clamato:1.333,blackSauce:1,hotSauce:1};
const MIXED_COVERED=new Set([...Object.keys(BASE_Q),'tostadas','container16','lid16','container12','lid12','spoon','napkins','saltPacket','bag10x20']);
const OPTIONAL_KEYS=['blackSauce','hotSauce','bag10x20','tshirtBagSmall','tshirtBagMedium','container12','lid12','container16','lid16','spoon','napkins','tostadas'];

let deviceId=localStorage.getItem(DEVICE_ID_KEY);if(!deviceId){deviceId=crypto.randomUUID();localStorage.setItem(DEVICE_ID_KEY,deviceId)}
const blank=()=>({version:VERSION,inventory:[],recipes:[],orders:[],purchases:[],sales:[],expenses:[],productionPlans:[],prepared:[],shoppingRecipeRevision:0,updatedAt:0});
function normalize(data){const b=blank();if(!data||typeof data!=='object')return b;return {...b,...data,version:VERSION,inventory:Array.isArray(data.inventory)?data.inventory:[],recipes:Array.isArray(data.recipes)?data.recipes:[],orders:Array.isArray(data.orders)?data.orders:[],purchases:Array.isArray(data.purchases)?data.purchases:[],sales:Array.isArray(data.sales)?data.sales:[],expenses:Array.isArray(data.expenses)?data.expenses:[],productionPlans:Array.isArray(data.productionPlans)?data.productionPlans:[],prepared:Array.isArray(data.prepared)?data.prepared:[],updatedAt:Number(data.updatedAt||0)}}
function loadLocal(){try{return normalize(JSON.parse(localStorage.getItem(LOCAL_KEY)||'null'))}catch{return blank()}}
let dbState=loadLocal(),publicOrders=[],current='home',editing=null,cloudReady=false,applyingRemote=false,syncTimer=null;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0)),qty=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:3}),today=()=>new Date().toLocaleDateString('en-CA'),tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toLocaleDateString('en-CA')},nowTime=()=>new Date().toTimeString().slice(0,5),id=()=>crypto.randomUUID(),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),byId=(arr,value)=>arr.find(x=>x.id===value),sorted=arr=>[...arr].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'es')),empty=text=>`<div class="empty">${esc(text)}</div>`;

function invByKey(key){return dbState.inventory.find(i=>i.appKey===key)||dbState.inventory.find(i=>i.id===`base-${key}`)}
function seedBaseData(){let changed=false;for(const [key,name,unit,category] of BASE_ITEMS){let row=invByKey(key)||dbState.inventory.find(i=>String(i.name||'').trim().toLowerCase()===name.toLowerCase());if(!row){row={id:`base-${key}`,name,unit,stock:0,minimum:0,costPerUnit:0,appKey:key,category};dbState.inventory.push(row);changed=true}else{if(!row.appKey){row.appKey=key;changed=true}if(!row.category){row.category=category;changed=true}}}
 if(Number(dbState.shoppingRecipeRevision||0)<2){for(const key of ['fish','shrimp']){const row=invByKey(key);if(row&&String(row.unit).toLowerCase()==='lb'){row.stock=Number(row.stock||0)*16;row.minimum=Number(row.minimum||0)*16;if(Number(row.costPerUnit||0)>0)row.costPerUnit=Number(row.costPerUnit)/16;row.unit='oz';for(const p of dbState.purchases){if(p.inventoryId===row.id&&String(p.unit||'').toLowerCase()==='lb'){p.qty=Number(p.qty||0)*16;p.unit='oz'}}changed=true}}}
 let r=dbState.recipes.find(x=>x.id===BASE_RECIPE_ID)||dbState.recipes.find(x=>String(x.name||'').trim().toLowerCase()==='ceviche mixto');if(!r){r={id:BASE_RECIPE_ID,name:'Ceviche mixto',yieldLb:1,price:17,ingredients:[]};dbState.recipes.push(r);changed=true}
 if(Number(dbState.shoppingRecipeRevision||0)<RECIPE_REV){r.id=BASE_RECIPE_ID;r.name='Ceviche mixto';r.yieldLb=1;r.price=Number(r.price||17);r.ingredients=Object.entries(BASE_Q).map(([key,n])=>({inventoryId:invByKey(key).id,qty:n}));dbState.shoppingRecipeRevision=RECIPE_REV;changed=true}
 if(changed){dbState.updatedAt=Date.now();localStorage.setItem(LOCAL_KEY,JSON.stringify(dbState))}}
seedBaseData();

function setCloud(text,kind=''){const el=$('#cloudState');if(!el)return;el.textContent=text;el.className=`pill ${kind}`.trim()}
function withTimeout(promise,ms=8000,label='Operación'){let timer;return Promise.race([Promise.resolve(promise).finally(()=>clearTimeout(timer)),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`${label} timeout`)),ms)})])}
function scheduleCloudRetry(ms=20000){clearTimeout(cloudRetryTimer);cloudRetryTimer=setTimeout(()=>{if(!cloudReady&&!cloudConnecting&&navigator.onLine!==false)initCloud()},ms)}
function saveLocal({sync=true}={}){dbState.updatedAt=Date.now();localStorage.setItem(LOCAL_KEY,JSON.stringify(dbState));renderCurrent();if(sync&&!applyingRemote)queueCloudSave()}
function toast(text,ms=1800){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),ms)}
function queueCloudSave(){if(!cloudReady||!firestore)return;clearTimeout(syncTimer);syncTimer=setTimeout(pushCloud,450)}
async function pushCloud(){if(!cloudReady||!firestore)return;try{setCloud('Guardando…','syncing');await withTimeout(setDoc(doc(firestore,...CLOUD_DOC),{...dbState,sourceDevice:deviceId,serverUpdatedAt:serverTimestamp()},{merge:false}),8000,'Guardar en nube');setCloud('Nube ✓','ok')}catch(e){console.error(e);cloudReady=false;setCloud('Local','warn');scheduleCloudRetry()}}
async function importWithTimeout(url,ms=7000){return withTimeout(import(url),ms,'Firebase')}
async function loadFirebase(){if(firestore)return true;if(firebaseLoading)return firebaseLoading;firebaseLoading=(async()=>{try{const [appMod,fireMod]=await Promise.all([importWithTimeout('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),importWithTimeout('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);initializeApp=appMod.initializeApp;({getFirestore,doc,getDoc,setDoc,onSnapshot,serverTimestamp,collection,updateDoc,getDocs}=fireMod);firestore=getFirestore(initializeApp(firebaseConfig));return true}catch(e){console.error('Firebase no disponible; panel sigue en modo Local',e);setCloud('Local','warn');scheduleCloudRetry();return false}finally{firebaseLoading=null}})();return firebaseLoading}

const modules=[['orders','📋','Pedidos','mod-orders'],['prep','👨‍🍳','Preparación','mod-prep'],['delivery','🚗','Entregas','mod-delivery'],['inventory','📦','Inventario','mod-inventory'],['recipes','🧾','Recetas','mod-recipes'],['purchases','🛒','Compras','mod-purchases'],['sales','💵','Venta','mod-sales'],['money','💰','Dinero','mod-money']];
function normalizeStatus(s){return ({nuevo:'pending',pendiente:'pending',preparando:'preparing',listo:'ready',entrega:'delivery',en_entrega:'delivery',entregado:'delivered',cancelado:'cancelled'}[s]||s||'pending')}
function statusLabel(s){return ({pending:'Pendiente',preparing:'Preparando',ready:'Listo',delivery:'En entrega',delivered:'Entregado',cancelled:'Cancelado'}[normalizeStatus(s)]||s)}
function mapPublicOrder(snap){const d=snap.data()||{};return {id:snap.id,public:true,customer:d.customer||d.name||'Cliente',phone:d.phone||'',address:d.address||'',zip:d.zip||'',date:d.deliveryDate||d.date||'',time:d.time||'',total:Number(d.total||0),status:normalizeStatus(d.status),items:Array.isArray(d.items)?d.items:[],publicRecipe:d.recipe&&typeof d.recipe==='object'?d.recipe:{},payment:d.payment||'',notes:d.notes||'',inventoryApplied:!!d.inventoryApplied,product:(Array.isArray(d.items)?d.items.map(x=>`${x.name||'Producto'}${x.qty>1?` × ${x.qty}`:''}`).join(', '):'Pedido app')}}
function allOrders(){return [...publicOrders,...dbState.orders]}
function recipeName(recipeId){return byId(dbState.recipes,recipeId)?.name||''}function inventoryName(inventoryId){return byId(dbState.inventory,inventoryId)?.name||''}
function orderProductText(o){if(o.public&&o.items?.length)return o.items.map(x=>`${x.name||'Producto'}${x.qty>1?` × ${x.qty}`:''}`).join(', ');return recipeName(o.recipeId)||o.product||'Pedido'}
function itemLb(it){const txt=`${it?.name||''} ${it?.detail||''}`.toLowerCase(),q=Number(it?.qty||1);if(txt.includes('1 libra')||txt.includes('1 lb'))return q;if(txt.includes('1/2')||txt.includes('½')||txt.includes('media libra'))return .5*q;return 0}
function orderPounds(o){if(Number(o.pounds)>0)return Number(o.pounds);if(!o.public)return Number(o.qty||1);const n=(o.items||[]).reduce((a,it)=>a+itemLb(it),0);return n||Number(o.qty||1)}
function mixedPublic(o){return (o.items||[]).some(it=>String(it.name||'').toLowerCase().includes('ceviche mixto'))}
function mixedLb(o){if(!o.public)return orderPounds(o);return (o.items||[]).filter(it=>String(it.name||'').toLowerCase().includes('ceviche mixto')).reduce((a,it)=>a+itemLb(it),0)}
function isMixedRecipe(recipeId){const r=byId(dbState.recipes,recipeId);return recipeId===BASE_RECIPE_ID||String(r?.name||'').trim().toLowerCase()==='ceviche mixto'}
function addNeed(map,inventoryId,n){if(!inventoryId||!Number(n))return;map.set(inventoryId,(map.get(inventoryId)||0)+Number(n))}
function publicAmount(key,n){const inv=invByKey(key),q=Number(n||0);if(inv&&['fish','shrimp','octopus'].includes(key)&&String(inv.unit||'').toLowerCase()==='oz')return q*16;return q}
function addPublicExtras(needs,o){for(const [key,n] of Object.entries(o.publicRecipe||{})){if(MIXED_COVERED.has(key))continue;const inv=invByKey(key);if(inv)addNeed(needs,inv.id,publicAmount(key,n))}}
function addMixedNeeds(needs,lb){lb=Number(lb||0);if(lb<=0)return;for(const [key,n] of Object.entries(BASE_Q)){const inv=invByKey(key);if(inv)addNeed(needs,inv.id,n*lb)}const full=Math.floor(lb+1e-6),half=(lb-full)>=.49?1:0,servings=full+half;const packs={tostadas:full*4+half*2,container16:full,lid16:full,container12:half,lid12:half,spoon:servings,napkins:servings*2,saltPacket:servings,bag10x20:servings*2};for(const [key,n] of Object.entries(packs)){const inv=invByKey(key);if(inv)addNeed(needs,inv.id,n)}}
function needsForOrder(o){const needs=new Map();if(o.public&&mixedPublic(o)){addMixedNeeds(needs,mixedLb(o));addPublicExtras(needs,o);return needs}if(o.public){for(const [key,n] of Object.entries(o.publicRecipe||{})){const inv=invByKey(key);if(inv)addNeed(needs,inv.id,publicAmount(key,n))}return needs}const r=byId(dbState.recipes,o.recipeId);if(!r)return needs;const mult=orderPounds(o)/Number(r.yieldLb||1);for(const line of r.ingredients||[])addNeed(needs,line.inventoryId,Number(line.qty||0)*mult);if(isMixedRecipe(r.id)){const lb=orderPounds(o),full=Math.floor(lb+1e-6),half=(lb-full)>=.49?1:0,servings=full+half;const packs={tostadas:full*4+half*2,container16:full,lid16:full,container12:half,lid12:half,spoon:servings,napkins:servings*2,saltPacket:servings,bag10x20:servings*2};for(const [key,n] of Object.entries(packs)){const inv=invByKey(key);if(inv)addNeed(needs,inv.id,n)}}return needs}
function applyNeeds(needs,sign=-1){for(const [inventoryId,n] of needs){const inv=byId(dbState.inventory,inventoryId);if(inv)inv.stock=Number(inv.stock||0)+sign*Number(n||0)}}

function goHome(){current='home';$('#home').classList.add('active');$('#screen').classList.remove('active');renderHome()}function openModule(name){current=name;$('#home').classList.remove('active');$('#screen').classList.add('active');renderModule()}function renderCurrent(){current==='home'?renderHome():renderModule()}
function renderHome(){$('#modules').innerHTML=modules.map(([key,icon,label,cls])=>`<button class="card ${cls}" type="button" data-module="${key}"><span>${icon}</span><strong>${label}</strong></button>`).join('');const orders=allOrders(),active=orders.filter(o=>!['delivered','cancelled'].includes(normalizeStatus(o.status))).length,todayOrders=orders.filter(o=>o.date===today()&&!['cancelled'].includes(normalizeStatus(o.status))).length,tomorrowOrders=orders.filter(o=>o.date===tomorrow()&&!['cancelled'].includes(normalizeStatus(o.status))).length,low=dbState.inventory.filter(i=>Number(i.minimum||0)>0&&Number(i.stock||0)<=Number(i.minimum||0)).length;$('#summary').innerHTML=`<div class="summary-title">Producción</div><div class="stats"><div><strong>${todayOrders}</strong><span>Pedidos hoy</span></div><div><strong>${tomorrowOrders}</strong><span>Pedidos mañana</span></div><div><strong>${active}</strong><span>Activos</span></div><div><strong>${low}</strong><span>Inventario bajo</span></div></div><button type="button" class="secondary full" data-export>Respaldar datos</button>`}
function renderModule(){const cfg={orders:['Pedidos','＋ Pedido'],prep:['Preparación','＋ Plan'],delivery:['Entregas',''],inventory:['Inventario','＋ Ingrediente'],recipes:['Recetas','＋ Receta'],purchases:['Compras','＋ Compra'],sales:['Venta','＋ Venta'],money:['Dinero','＋ Gasto']}[current];$('#screenTitle').textContent=cfg[0];$('#primaryBtn').textContent=cfg[1];$('#primaryBtn').hidden=!cfg[1];({orders:renderOrders,prep:renderPrep,delivery:renderDelivery,inventory:renderInventory,recipes:renderRecipes,purchases:renderPurchases,sales:renderSales,money:renderMoney}[current])()}
function dayChip(date){if(date===today())return '<span class="day-chip today">HOY</span>';if(date===tomorrow())return '<span class="day-chip tomorrow">MAÑANA</span>';return `<span class="day-chip">${esc(date||'Sin fecha')}</span>`}
function renderOrders(){const rows=allOrders().sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`));$('#content').innerHTML=rows.length?`<div class="list">${rows.map(o=>`<article class="row order-row"><div class="row-head"><div>${dayChip(o.date)}<h3>${esc(o.customer||'Cliente')}</h3><div class="muted">${esc(o.date||'')} ${esc(o.time||'')}</div></div><strong>${money(o.total)}</strong></div><div class="product-line">${esc(orderProductText(o))}</div><div class="muted">${qty(orderPounds(o))} lb</div><div class="status ${esc(normalizeStatus(o.status))}">${esc(statusLabel(o.status))}</div>${o.address?`<div class="address">${esc(o.address)}</div>`:''}<div class="actions">${!o.public&&!['delivered','cancelled'].includes(normalizeStatus(o.status))?`<button type="button" data-order-edit="${o.id}">Editar</button>`:''}${!['delivered','cancelled'].includes(normalizeStatus(o.status))?`<button type="button" class="danger" data-order-status="${o.id}" data-public="${o.public?'1':'0'}" data-status="cancelled">Cancelar</button>`:''}</div></article>`).join('')}</div>`:empty('No hay pedidos.')}
function renderPrep(){const plans=[...dbState.productionPlans].filter(p=>p.status!=='done').sort((a,b)=>String(a.date).localeCompare(String(b.date)));const rows=allOrders().filter(o=>['pending','preparing'].includes(normalizeStatus(o.status))).sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`)),grouped={};for(const o of rows){const k=o.date||'Sin fecha';(grouped[k]??=[]).push(o)}const planHtml=plans.length?plans.map(renderPlanCard).join(''):`<div class="planner-note">Crea un plan para juntar pedidos + libras extra y calcular exactamente qué comprar.</div>`;const prepHtml=rows.length?Object.entries(grouped).map(([date,items])=>`<section class="day-section"><div class="day-title">${dayChip(date)} <strong>${qty(items.reduce((s,o)=>s+orderPounds(o),0))} lb</strong></div><div class="list">${items.map(o=>`<article class="row prep-row"><div class="row-head"><div><h3>${esc(orderProductText(o))}</h3><div class="muted">${esc(o.customer||'')} · ${esc(o.time||'')}</div></div><strong>${qty(orderPounds(o))} lb</strong></div><div class="actions">${normalizeStatus(o.status)==='pending'?`<button class="primary-inline" type="button" data-order-status="${o.id}" data-public="${o.public?'1':'0'}" data-status="preparing">Preparar</button>`:`<button class="primary-inline" type="button" data-order-status="${o.id}" data-public="${o.public?'1':'0'}" data-status="ready">Listo</button>`}</div></article>`).join('')}</div></section>`).join(''):empty('Nada por preparar.');$('#content').innerHTML=`${planHtml}<div class="section-head"><h3>Pedidos por preparar</h3></div>${prepHtml}`}
function renderPlanCard(p){const calc=calcPlan(p),r=byId(dbState.recipes,p.recipeId);return `<section class="purchase-day"><div class="purchase-head"><div>${dayChip(p.date)}<h3>${esc(r?.name||'Producción')} · ${qty(calc.totalLb)} lb</h3><span>${qty(calc.orderLb)} lb pedidos + ${qty(p.extraLb||0)} lb extra</span></div></div><div class="actions"><button type="button" data-plan-buy="${p.id}">🛒 Calcular compra</button><button type="button" data-plan-edit="${p.id}">Editar</button><button class="primary-inline" type="button" data-plan-finish="${p.id}">Terminar producción</button></div></section>`}
function renderDelivery(){const rows=allOrders().filter(o=>['ready','delivery'].includes(normalizeStatus(o.status))).sort((a,b)=>`${a.date||''} ${a.time||''}`.localeCompare(`${b.date||''} ${b.time||''}`));$('#content').innerHTML=rows.length?`<div class="list">${rows.map(o=>`<article class="row"><div class="row-head"><div>${dayChip(o.date)}<h3>${esc(o.customer||'Cliente')}</h3></div><strong>${esc(o.time||'')}</strong></div><div>${esc(orderProductText(o))} · ${qty(orderPounds(o))} lb</div><div class="address">${esc(o.address||'Sin dirección')}</div><div class="actions">${normalizeStatus(o.status)==='ready'?`<button class="primary-inline" type="button" data-order-status="${o.id}" data-public="${o.public?'1':'0'}" data-status="delivery">Salir a entregar</button>`:`<button class="primary-inline" type="button" data-order-status="${o.id}" data-public="${o.public?'1':'0'}" data-status="delivered">Entregado</button>`}</div></article>`).join('')}</div>`:empty('No hay entregas.')}
function renderInventory(){const rows=sorted(dbState.inventory);$('#content').innerHTML=rows.length?`<div class="list">${rows.map(i=>{const low=Number(i.minimum||0)>0&&Number(i.stock||0)<=Number(i.minimum||0);return `<article class="row ${low?'low':''}"><div class="row-head"><div><h3>${esc(i.name)}</h3><div class="muted">${low?'⚠ Inventario bajo':'Existencia'}${i.category?` · ${esc(i.category)}`:''}</div></div><strong>${qty(i.stock)} ${esc(i.unit)}</strong></div><div class="muted">Mínimo ${qty(i.minimum)} ${esc(i.unit)} · Costo ${money(i.costPerUnit)}/${esc(i.unit)}</div><div class="actions"><button type="button" data-inventory-edit="${i.id}">Editar</button><button type="button" class="danger" data-delete="inventory" data-id="${i.id}">Eliminar</button></div></article>`}).join('')}</div>`:empty('Inventario vacío.')}
function recipeCost(r){return (r.ingredients||[]).reduce((sum,x)=>{const inv=byId(dbState.inventory,x.inventoryId);return sum+(inv?Number(inv.costPerUnit||0)*Number(x.qty||0):0)},0)}
function renderRecipes(){const rows=sorted(dbState.recipes);$('#content').innerHTML=rows.length?`<div class="list">${rows.map(r=>{const cost=recipeCost(r);return `<article class="row"><div class="row-head"><div><h3>${esc(r.name)}</h3><div class="muted">Rinde ${qty(r.yieldLb||1)} lb · ${(r.ingredients||[]).length} ingredientes</div></div><strong>${money(r.price)}</strong></div><div class="muted">Costo estimado ${money(cost)} · Margen ${money(Number(r.price||0)-cost)}</div><div class="recipe-lines">${(r.ingredients||[]).map(x=>{const inv=byId(dbState.inventory,x.inventoryId);return inv?`<span>${esc(inv.name)}: ${qty(x.qty)} ${esc(inv.unit)}</span>`:''}).join('')}</div><div class="actions"><button type="button" data-recipe-edit="${r.id}">Editar</button>${r.id!==BASE_RECIPE_ID?`<button type="button" class="danger" data-delete="recipes" data-id="${r.id}">Eliminar</button>`:''}</div></article>`}).join('')}</div>`:empty('No hay recetas.')}
function needMapForDate(date){const needs=new Map(),orders=allOrders().filter(o=>o.date===date&&!o.inventoryApplied&&!['cancelled','delivered'].includes(normalizeStatus(o.status)));for(const o of orders){for(const [inventoryId,n] of needsForOrder(o))addNeed(needs,inventoryId,n)}return {needs,orders}}
function purchaseRows(date){const {needs,orders}=needMapForDate(date),rows=[];for(const [inventoryId,required] of needs){const inv=byId(dbState.inventory,inventoryId);if(!inv)continue;const stock=Number(inv.stock||0);rows.push({inv,required,stock,buy:Math.max(0,required-stock)})}return {rows,orders}}
function renderPurchases(){const plans=[...dbState.productionPlans].filter(p=>p.status!=='done').sort((a,b)=>String(a.date).localeCompare(String(b.date))),d1=today(),d2=tomorrow(),a=purchaseRows(d1),b=purchaseRows(d2);$('#content').innerHTML=`${plans.length?`<div class="section-head"><h3>Planes de producción</h3></div>${plans.map(renderPlanCard).join('')}`:''}<div class="planner-note">La compra sugerida resta lo que ya tienes. La cantidad real comprada la decides tú; el sobrante se queda en inventario.</div>${renderPurchaseDay(d1,a)}${renderPurchaseDay(d2,b)}<div class="section-head"><h3>Compras realizadas</h3><button type="button" class="secondary" data-manual-purchase>＋ Registrar compra</button></div>${dbState.purchases.length?`<div class="list">${[...dbState.purchases].sort((x,y)=>String(y.date||'').localeCompare(String(x.date||''))).slice(0,30).map(p=>`<article class="row compact"><div class="row-head"><h3>${esc(inventoryName(p.inventoryId)||p.name||'Compra')}</h3><strong>${money(p.total)}</strong></div><div class="muted">${esc(p.date||'')} · ${qty(p.qty)} ${esc(p.unit||'')}${p.purchasedUnit&&p.purchasedUnit!==p.unit?` · comprado como ${qty(p.purchasedQty)} ${esc(p.purchasedUnit)}`:''}</div></article>`).join('')}</div>`:empty('Todavía no hay compras registradas.')}`}
function renderPurchaseDay(date,data){const totalLb=data.orders.reduce((s,o)=>s+orderPounds(o),0),unlinked=data.orders.filter(o=>!o.public&&!o.recipeId).length;return `<section class="purchase-day"><div class="purchase-head"><div>${dayChip(date)}<h3>${qty(totalLb)} lb pedidas</h3><span>${data.orders.length} pedido(s)</span></div></div>${unlinked?`<div class="warning">⚠ ${unlinked} pedido(s) no tienen receta vinculada.</div>`:''}${data.rows.length?`<div class="shopping-list">${data.rows.map(x=>`<div class="shop-item ${x.buy>0?'buy':'ok'}"><div><strong>${esc(x.inv.name)}</strong><span>Necesitas ${qty(x.required)} ${esc(x.inv.unit)} · Tienes ${qty(x.stock)}</span></div><b>${x.buy>0?`COMPRAR ${qty(x.buy)} ${esc(x.inv.unit)}`:'YA HAY'}</b></div>`).join('')}</div>`:empty(data.orders.length?'Falta receta para calcular compras.':'No hay pedidos para esta fecha.')}</section>`}
function renderSales(){const prepared=dbState.prepared.filter(x=>Number(x.qty||0)>0),rows=[...dbState.sales].sort((a,b)=>`${b.date||''} ${b.time||''}`.localeCompare(`${a.date||''} ${a.time||''}`));$('#content').innerHTML=`${prepared.length?`<div class="prepared-box"><strong>Preparado extra</strong><div class="prepared-grid">${prepared.map(p=>`<div class="prepared-chip"><strong>${esc(recipeName(p.recipeId)||'Producto')}</strong><span>${qty(p.qty)} lb disponibles</span></div>`).join('')}</div></div>`:''}${rows.length?`<div class="list">${rows.map(s=>`<article class="row"><div class="row-head"><h3>${esc(recipeName(s.recipeId)||s.product||'Venta')}</h3><strong>${money(s.total)}</strong></div><div class="muted">${esc(s.date||'')} ${esc(s.time||'')} · ${qty(s.qty||1)} lb</div></article>`).join('')}</div>`:empty('No hay ventas directas.')}`}
function renderMoney(){const direct=dbState.sales.reduce((s,x)=>s+Number(x.total||0),0),delivered=allOrders().filter(o=>normalizeStatus(o.status)==='delivered').reduce((s,o)=>s+Number(o.total||0),0),purchases=dbState.purchases.reduce((s,x)=>s+Number(x.total||0),0),expenses=dbState.expenses.reduce((s,x)=>s+Number(x.amount||0),0),balance=direct+delivered-purchases-expenses;$('#content').innerHTML=`<div class="money-grid"><div><span>Ventas</span><strong>${money(direct+delivered)}</strong></div><div><span>Compras</span><strong>${money(purchases)}</strong></div><div><span>Gastos</span><strong>${money(expenses)}</strong></div><div class="balance"><span>Balance</span><strong>${money(balance)}</strong></div></div>${dbState.expenses.length?`<div class="list">${dbState.expenses.map(e=>`<article class="row"><div class="row-head"><h3>${esc(e.name||'Gasto')}</h3><strong>${money(e.amount)}</strong></div><div class="muted">${esc(e.date||'')}</div></article>`).join('')}</div>`:empty('No hay gastos extras.')}`}

function showModal(title,html,onSubmit){editing={onSubmit};$('#formTitle').textContent=title;$('#formFields').innerHTML=`<div class="fields">${html}</div>`;$('#modal').hidden=false}function closeModal(){editing=null;$('#modal').hidden=true;$('#form').reset()}function input(name,label,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}function select(name,label,options,value=''){return `<label>${esc(label)}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`}
function openOrderForm(existing=null){const recipeOptions=[['','Sin receta / capturar producto'],...sorted(dbState.recipes).map(r=>[r.id,r.name])];showModal(existing?'Editar pedido':'Nuevo pedido',`${input('customer','Cliente',existing?.customer||'')}${select('recipeId','Receta / producto',recipeOptions,existing?.recipeId||BASE_RECIPE_ID)}${input('product','Producto libre',existing?.product||'')}${input('pounds','Libras',existing?.pounds||existing?.qty||1,'number','min="0.25" step="0.25" required')}${input('total','Total $',existing?.total||'','number','min="0" step="0.01"')}${input('date','Fecha de entrega',existing?.date||today(),'date','required')}${input('time','Hora de entrega',existing?.time||nowTime(),'time','required')}${input('address','Dirección',existing?.address||'')}`,fd=>{const obj={id:existing?.id||id(),customer:fd.get('customer').trim(),recipeId:fd.get('recipeId'),product:fd.get('product').trim(),pounds:Number(fd.get('pounds')||0),qty:Number(fd.get('pounds')||0),total:Number(fd.get('total')||0),date:fd.get('date'),time:fd.get('time'),address:fd.get('address').trim(),status:existing?.status||'pending',inventoryApplied:existing?.inventoryApplied||false};if(existing)dbState.orders=dbState.orders.map(x=>x.id===existing.id?obj:x);else dbState.orders.push(obj);saveLocal();closeModal();toast('Pedido guardado')})}
function openInventoryForm(existing=null){const appOpts=[['','Sin vínculo con app'],...APP_KEYS.map(k=>[k,k])];showModal(existing?'Editar ingrediente':'Nuevo ingrediente',`${input('name','Ingrediente',existing?.name||'','','required')}${select('unit','Unidad',UNITS.map(x=>[x,x]),existing?.unit||'oz')}${input('stock','Existencia actual',existing?.stock||0,'number','step="0.001" min="0"')}${input('minimum','Mínimo',existing?.minimum||0,'number','step="0.001" min="0"')}${input('costPerUnit','Costo por unidad $',existing?.costPerUnit||0,'number','step="0.0001" min="0"')}${select('appKey','Vínculo interno',appOpts,existing?.appKey||'')}`,fd=>{const obj={id:existing?.id||id(),name:fd.get('name').trim(),unit:fd.get('unit'),stock:Number(fd.get('stock')||0),minimum:Number(fd.get('minimum')||0),costPerUnit:Number(fd.get('costPerUnit')||0),appKey:fd.get('appKey'),category:existing?.category||''};if(existing)dbState.inventory=dbState.inventory.map(x=>x.id===existing.id?obj:x);else dbState.inventory.push(obj);saveLocal();closeModal();toast('Ingrediente guardado')})}
function ingredientRow(line={}){return `<div class="ingredient-row"><select name="ingredientId">${sorted(dbState.inventory).map(i=>`<option value="${i.id}" ${i.id===line.inventoryId?'selected':''}>${esc(i.name)} (${esc(i.unit)})</option>`).join('')}</select><input name="ingredientQty" type="number" min="0" step="0.001" value="${esc(line.qty||'')}" placeholder="Cantidad"><button type="button" class="icon mini" data-remove-line>×</button></div>`}
function openRecipeForm(existing=null){if(!dbState.inventory.length){toast('Primero registra ingredientes',2600);return}showModal(existing?'Editar receta':'Nueva receta',`${input('name','Nombre / presentación',existing?.name||'','','required')}${input('yieldLb','Rinde (lb)',existing?.yieldLb||1,'number','min="0.25" step="0.25" required')}${input('price','Precio de venta $',existing?.price||0,'number','min="0" step="0.01"')}<div class="section-head"><strong>Ingredientes</strong><button type="button" class="secondary" data-add-line>＋ Ingrediente</button></div><div id="ingredientLines">${(existing?.ingredients?.length?existing.ingredients:[{}]).map(ingredientRow).join('')}</div>`,fd=>{const ids=fd.getAll('ingredientId'),qs=fd.getAll('ingredientQty'),ingredients=ids.map((inventoryId,i)=>({inventoryId,qty:Number(qs[i]||0)})).filter(x=>x.inventoryId&&x.qty>0),obj={id:existing?.id||id(),name:fd.get('name').trim(),yieldLb:Number(fd.get('yieldLb')||1),price:Number(fd.get('price')||0),ingredients};if(existing)dbState.recipes=dbState.recipes.map(x=>x.id===existing.id?obj:x);else dbState.recipes.push(obj);saveLocal();closeModal();toast('Receta guardada')})}
function compatibleUnits(base){if(base==='oz')return [['oz','oz'],['lb','lb']];if(base==='lb')return [['lb','lb'],['oz','oz']];if(base==='fl oz')return [['fl oz','fl oz'],['ml','ml']];if(base==='ml')return [['ml','ml'],['fl oz','fl oz']];if(base==='g')return [['g','g'],['kg','kg']];if(base==='kg')return [['kg','kg'],['g','g']];return [[base,base]]}
function toBaseQty(q,from,to){q=Number(q||0);if(from===to)return q;if(from==='lb'&&to==='oz')return q*16;if(from==='oz'&&to==='lb')return q/16;if(from==='ml'&&to==='fl oz')return q/29.5735;if(from==='fl oz'&&to==='ml')return q*29.5735;if(from==='kg'&&to==='g')return q*1000;if(from==='g'&&to==='kg')return q/1000;return q}
function openPurchaseForm(){if(!dbState.inventory.length){toast('Primero registra ingredientes',2200);return}const first=sorted(dbState.inventory)[0];showModal('Registrar compra',`${select('inventoryId','Ingrediente',sorted(dbState.inventory).map(i=>[i.id,`${i.name} (${i.unit})`]))}${input('qty','Cantidad comprada','','number','min="0.001" step="0.001" required')}<label>Unidad de compra<select name="purchaseUnit" id="purchaseUnit">${compatibleUnits(first?.unit||'pza').map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select></label>${input('total','Total pagado $','','number','min="0" step="0.01" required')}${input('date','Fecha',today(),'date','required')}`,fd=>{const inventoryId=fd.get('inventoryId'),raw=Number(fd.get('qty')||0),purchaseUnit=fd.get('purchaseUnit'),total=Number(fd.get('total')||0),inv=byId(dbState.inventory,inventoryId);if(!inv)return;const baseQty=toBaseQty(raw,purchaseUnit,inv.unit);inv.stock=Number(inv.stock||0)+baseQty;if(baseQty>0)inv.costPerUnit=total/baseQty;dbState.purchases.push({id:id(),inventoryId,qty:baseQty,total,date:fd.get('date'),unit:inv.unit,purchasedQty:raw,purchasedUnit:purchaseUnit});saveLocal();closeModal();toast('Compra registrada')});setTimeout(()=>{const s=$('select[name="inventoryId"]'),u=$('#purchaseUnit');if(s&&u)s.addEventListener('change',()=>{const inv=byId(dbState.inventory,s.value);u.innerHTML=compatibleUnits(inv?.unit||'pza').map(([v,t])=>`<option value="${v}">${t}</option>`).join('')})},0)}
function openPlanForm(existing=null){const recipes=sorted(dbState.recipes);showModal(existing?'Editar plan':'Nuevo plan',`${select('recipeId','Producto',recipes.map(r=>[r.id,r.name]),existing?.recipeId||BASE_RECIPE_ID)}${input('date','Fecha de producción',existing?.date||tomorrow(),'date','required')}${input('extraLb','Libras extra',existing?.extraLb||0,'number','min="0" step="0.5" required')}`,fd=>{const obj={id:existing?.id||id(),recipeId:fd.get('recipeId'),date:fd.get('date'),extraLb:Number(fd.get('extraLb')||0),status:existing?.status||'planned',createdAt:existing?.createdAt||Date.now()};if(existing)dbState.productionPlans=dbState.productionPlans.map(x=>x.id===existing.id?obj:x);else dbState.productionPlans.push(obj);saveLocal();closeModal();toast('Plan guardado')})}
function planOrders(p){const r=byId(dbState.recipes,p.recipeId),name=String(r?.name||'').trim().toLowerCase();const local=dbState.orders.filter(o=>!o.inventoryApplied&&o.date===p.date&&!['cancelled','delivered'].includes(normalizeStatus(o.status))&&(o.recipeId===p.recipeId||(!o.recipeId&&name&&String(o.product||'').toLowerCase().includes(name))));const pub=publicOrders.filter(o=>!o.inventoryApplied&&o.date===p.date&&!['cancelled','delivered'].includes(normalizeStatus(o.status))&&(isMixedRecipe(p.recipeId)?mixedPublic(o):String((o.items||[]).map(i=>i.name).join(' ')).toLowerCase().includes(name)));return [...local,...pub]}
function calcPlan(p){const needs=new Map(),orders=planOrders(p),mixed=isMixedRecipe(p.recipeId),r=byId(dbState.recipes,p.recipeId);for(const o of orders){const n=needsForOrder(o);for(const [iid,qv] of n)addNeed(needs,iid,qv)}if(Number(p.extraLb)>0){if(mixed)addMixedNeeds(needs,p.extraLb);else if(r){const mult=Number(p.extraLb)/Number(r.yieldLb||1);for(const x of r.ingredients||[])addNeed(needs,x.inventoryId,Number(x.qty||0)*mult)}}const orderLb=orders.reduce((a,o)=>a+(mixed&&o.public?mixedLb(o):orderPounds(o)),0);return {needs,orders,orderLb,totalLb:orderLb+Number(p.extraLb||0)}}
function openPlanShopping(planId){const p=dbState.productionPlans.find(x=>x.id===planId);if(!p)return;const {needs,totalLb}=calcPlan(p),rows=[...needs].map(([iid,n])=>{const inv=byId(dbState.inventory,iid);return inv?{inv,required:n,buy:Math.max(0,Number(n||0)-Number(inv.stock||0))}:null}).filter(Boolean);for(const key of OPTIONAL_KEYS){const inv=invByKey(key);if(inv&&!rows.some(x=>x.inv.id===inv.id))rows.push({inv,required:0,buy:0})}showModal(`Compra para ${qty(totalLb)} lb`,`${rows.map(x=>`<div class="ingredient-row"><div><strong>${esc(x.inv.name)}</strong><div class="muted">Necesitas ${qty(x.required)} ${esc(x.inv.unit)} · Tienes ${qty(x.inv.stock)} ${esc(x.inv.unit)}</div></div><input name="q_${x.inv.id}" type="number" min="0" step="0.001" value="${Number(x.buy.toFixed(3))}" placeholder="Comprar"><select name="u_${x.inv.id}">${compatibleUnits(x.inv.unit).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><input name="c_${x.inv.id}" type="number" min="0" step="0.01" placeholder="Costo $"></div>`).join('')}${input('date','Fecha',today(),'date','required')}`,fd=>{for(const x of rows){const raw=Number(fd.get(`q_${x.inv.id}`)||0),purchaseUnit=fd.get(`u_${x.inv.id}`)||x.inv.unit,total=Number(fd.get(`c_${x.inv.id}`)||0);if(raw<=0)continue;const inv=byId(dbState.inventory,x.inv.id),baseQty=toBaseQty(raw,purchaseUnit,inv.unit);inv.stock=Number(inv.stock||0)+baseQty;if(total>0&&baseQty>0)inv.costPerUnit=total/baseQty;dbState.purchases.push({id:id(),planId,inventoryId:inv.id,qty:baseQty,total,date:fd.get('date'),unit:inv.unit,purchasedQty:raw,purchasedUnit:purchaseUnit})}saveLocal();closeModal();toast('Compra registrada')})}
async function finishPlan(planId){const p=dbState.productionPlans.find(x=>x.id===planId);if(!p||p.status==='done')return;const {needs,orders}=calcPlan(p);applyNeeds(needs,-1);if(Number(p.extraLb)>0){let row=dbState.prepared.find(x=>x.recipeId===p.recipeId);if(!row){row={recipeId:p.recipeId,qty:0};dbState.prepared.push(row)}row.qty=Number(row.qty||0)+Number(p.extraLb)}for(const o of orders){if(o.public){o.inventoryApplied=true;if(firestore){try{await withTimeout(updateDoc(doc(firestore,'pedidos',o.id),{inventoryApplied:true}),8000,'Marcar inventario')}catch(e){console.error(e)}}}else{const lo=byId(dbState.orders,o.id);if(lo)lo.inventoryApplied=true}}p.status='done';p.doneAt=Date.now();saveLocal();toast('Producción terminada')}
function openSaleForm(){if(!dbState.recipes.length){toast('Primero crea una receta',2200);return}showModal('Nueva venta',`${select('recipeId','Producto',sorted(dbState.recipes).map(r=>[r.id,r.name]),BASE_RECIPE_ID)}${input('qty','Libras',1,'number','min="0.25" step="0.25" required')}${input('total','Total $','','number','min="0" step="0.01" required')}${input('date','Fecha',today(),'date','required')}${input('time','Hora',nowTime(),'time','required')}`,fd=>{const recipeId=fd.get('recipeId'),q=Number(fd.get('qty')||1),r=byId(dbState.recipes,recipeId),prepared=dbState.prepared.find(x=>x.recipeId===recipeId);let shortage=q;if(prepared&&Number(prepared.qty)>0){const used=Math.min(Number(prepared.qty),q);prepared.qty=Number(prepared.qty)-used;shortage-=used}if(shortage>0){if(isMixedRecipe(recipeId)){const n=new Map();addMixedNeeds(n,shortage);applyNeeds(n,-1)}else if(r){const mult=shortage/Number(r.yieldLb||1);for(const line of r.ingredients||[]){const inv=byId(dbState.inventory,line.inventoryId);if(inv)inv.stock=Number(inv.stock||0)-Number(line.qty||0)*mult}}}dbState.sales.push({id:id(),recipeId,qty:q,total:Number(fd.get('total')||0),date:fd.get('date'),time:fd.get('time')});saveLocal();closeModal();toast('Venta registrada')})}
function openExpenseForm(){showModal('Nuevo gasto',`${input('name','Concepto','','','required')}${input('amount','Monto $','','number','min="0" step="0.01" required')}${input('date','Fecha',today(),'date','required')}`,fd=>{dbState.expenses.unshift({id:id(),name:fd.get('name').trim(),amount:Number(fd.get('amount')||0),date:fd.get('date')});saveLocal();closeModal();toast('Gasto guardado')})}

async function changeOrderStatus(orderId,status,isPublic){const o=isPublic?publicOrders.find(x=>x.id===orderId):byId(dbState.orders,orderId);if(!o)return;if(status==='ready'&&!o.inventoryApplied){const needs=needsForOrder(o);applyNeeds(needs,-1);o.inventoryApplied=true;if(!isPublic){const lo=byId(dbState.orders,orderId);if(lo)lo.inventoryApplied=true}}
 if(isPublic){if(!firestore){toast('Pedido preparado localmente; falta sincronizar estado',2600);saveLocal();return}const firestoreStatus={pending:'nuevo',preparing:'preparando',ready:'listo',delivery:'en_entrega',delivered:'entregado',cancelled:'cancelado'}[status]||status;try{await withTimeout(updateDoc(doc(firestore,'pedidos',orderId),{status:firestoreStatus,...(o.inventoryApplied?{inventoryApplied:true}:{})}),8000,'Actualizar pedido');o.status=status;saveLocal({sync:false});toast('Pedido actualizado')}catch(e){console.error(e);toast('No se pudo actualizar',2500)}return}o.status=status;saveLocal();toast('Pedido actualizado')}
function deleteItem(type,itemId){if(type==='inventory'){const used=dbState.recipes.some(r=>(r.ingredients||[]).some(x=>x.inventoryId===itemId));if(used){toast('Ese ingrediente está usado en una receta',2600);return}dbState.inventory=dbState.inventory.filter(x=>x.id!==itemId)}if(type==='recipes'){if(itemId===BASE_RECIPE_ID){toast('La receta base no se elimina',2200);return}const used=dbState.orders.some(o=>o.recipeId===itemId&&!['delivered','cancelled'].includes(normalizeStatus(o.status)));if(used){toast('Esa receta tiene pedidos activos',2500);return}dbState.recipes=dbState.recipes.filter(x=>x.id!==itemId)}saveLocal()}
function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),data:dbState},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`panel-el-chava-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}

$('#homeBtn').addEventListener('click',goHome);$('#backBtn').addEventListener('click',goHome);$('#closeModal').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#primaryBtn').addEventListener('click',()=>({orders:()=>openOrderForm(),prep:()=>openPlanForm(),inventory:()=>openInventoryForm(),recipes:()=>openRecipeForm(),purchases:()=>openPurchaseForm(),sales:()=>openSaleForm(),money:()=>openExpenseForm()}[current]?.()));$('#form').addEventListener('submit',e=>{e.preventDefault();if(editing?.onSubmit)editing.onSubmit(new FormData(e.currentTarget))});
document.addEventListener('click',e=>{const m=e.target.closest('[data-module]');if(m){openModule(m.dataset.module);return}if(e.target.closest('[data-export]')){exportData();return}if(e.target.closest('[data-manual-purchase]')){openPurchaseForm();return}const ie=e.target.closest('[data-inventory-edit]');if(ie){openInventoryForm(byId(dbState.inventory,ie.dataset.inventoryEdit));return}const re=e.target.closest('[data-recipe-edit]');if(re){openRecipeForm(byId(dbState.recipes,re.dataset.recipeEdit));return}const oe=e.target.closest('[data-order-edit]');if(oe){openOrderForm(byId(dbState.orders,oe.dataset.orderEdit));return}const os=e.target.closest('[data-order-status]');if(os){changeOrderStatus(os.dataset.orderStatus,os.dataset.status,os.dataset.public==='1');return}const pb=e.target.closest('[data-plan-buy]');if(pb){openPlanShopping(pb.dataset.planBuy);return}const pe=e.target.closest('[data-plan-edit]');if(pe){openPlanForm(dbState.productionPlans.find(x=>x.id===pe.dataset.planEdit));return}const pf=e.target.closest('[data-plan-finish]');if(pf){finishPlan(pf.dataset.planFinish);return}const del=e.target.closest('[data-delete]');if(del){deleteItem(del.dataset.delete,del.dataset.id);return}if(e.target.closest('[data-add-line]')){$('#ingredientLines').insertAdjacentHTML('beforeend',ingredientRow());return}const rm=e.target.closest('[data-remove-line]');if(rm)rm.closest('.ingredient-row')?.remove()});

async function initCloud(){if(cloudReady||cloudConnecting)return;cloudConnecting=true;setCloud('Conectando…','syncing');try{const loaded=await loadFirebase();if(!loaded)return;const ref=doc(firestore,...CLOUD_DOC),snap=await withTimeout(getDoc(ref),8000,'Conexión Firestore');if(snap.exists()){const remote=normalize(snap.data());if(remote.updatedAt>dbState.updatedAt){dbState=remote;seedBaseData();localStorage.setItem(LOCAL_KEY,JSON.stringify(dbState));renderCurrent()}}else if(dbState.updatedAt){await withTimeout(setDoc(ref,{...dbState,sourceDevice:deviceId,serverUpdatedAt:serverTimestamp()}),8000,'Inicializar nube')}cloudReady=true;clearTimeout(cloudRetryTimer);setCloud('Nube ✓','ok');onSnapshot(ref,s=>{if(!s.exists())return;const data=normalize(s.data());if(s.data().sourceDevice===deviceId||data.updatedAt<=dbState.updatedAt)return;applyingRemote=true;dbState=data;seedBaseData();localStorage.setItem(LOCAL_KEY,JSON.stringify(dbState));renderCurrent();applyingRemote=false},e=>{console.error(e);cloudReady=false;setCloud('Local','warn');scheduleCloudRetry()});onSnapshot(collection(firestore,'pedidos'),snapshot=>{publicOrders=snapshot.docs.map(mapPublicOrder);renderCurrent()},e=>console.error(e))}catch(e){console.error(e);cloudReady=false;setCloud('Local','warn');scheduleCloudRetry()}finally{cloudConnecting=false}}

goHome();initCloud();window.addEventListener('online',()=>{clearTimeout(cloudRetryTimer);if(!cloudReady)initCloud()});window.addEventListener('offline',()=>{setCloud('Local','warn')});
