import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getFirestore, doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const cfg={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466'};
const app=getApps().find(a=>a.name==='inventory-v5')||initializeApp(cfg,'inventory-v5');
const db=getFirestore(app),KEY='chava-panel-v3';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const qty=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:3});
const today=()=>new Date().toLocaleDateString('en-CA');
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const uid=()=>crypto.randomUUID();
async function save(s){s.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(s));try{await setDoc(doc(db,'panel_v2','principal_v3'),{...s,sourceDevice:localStorage.getItem('chava-panel-device-v3')||'inventory-v5',serverUpdatedAt:serverTimestamp()},{merge:false})}catch(e){console.error(e)}}

const extraItems=[
 ['container12','Contenedor 12 oz','pza','Empaque y desechables'],
 ['lid12','Tapa 12 oz','pza','Empaque y desechables'],
 ['container16','Contenedor 16 oz','pza','Empaque y desechables'],
 ['lid16','Tapa 16 oz','pza','Empaque y desechables'],
 ['spoon','Cuchara','pza','Empaque y desechables'],
 ['bag10x20','Bolsa 10 × 20 cm','pza','Empaque y desechables'],
 ['tshirtBagSmall','Bolsa camiseta chica','pza','Empaque y desechables'],
 ['tshirtBagMedium','Bolsa camiseta mediana','pza','Empaque y desechables'],
 ['blackSauce','Salsa negra','fl oz','Salsas y líquidos'],
 ['hotSauce','Salsa picante','fl oz','Salsas y líquidos']
];
async function seedMissing(){const s=read();s.inventory=Array.isArray(s.inventory)?s.inventory:[];let changed=false;for(const [key,name,unit,category] of extraItems){let row=s.inventory.find(i=>i.appKey===key)||s.inventory.find(i=>String(i.name||'').toLowerCase()===name.toLowerCase());if(!row){s.inventory.push({id:`base-${key}`,name,unit,stock:0,minimum:0,costPerUnit:0,appKey:key,category});changed=true}else if(!row.category){row.category=category;changed=true}}if(changed)await save(s)}

const style=document.createElement('style');style.textContent=`
.inv5-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}.inv5-toolbar button{border:0;border-radius:12px;padding:10px 13px;font-weight:900}.inv5-buy{background:#ef6c00;color:#fff}.inv5-add{background:#087f5b;color:#fff}.inv5-group{background:#fff;border-radius:15px;margin:0 0 10px;box-shadow:0 4px 14px #00000010;overflow:hidden}.inv5-head{width:100%;border:0;background:#fff;display:flex;align-items:center;justify-content:space-between;padding:14px 15px;font-weight:1000;font-size:17px}.inv5-head span:last-child{font-size:21px}.inv5-body{display:none;padding:0 12px 12px}.inv5-group.open .inv5-body{display:block}.inv5-row{padding:11px 0;border-top:1px solid #eee}.inv5-row:first-child{border-top:0}.inv5-top{display:flex;justify-content:space-between;gap:12px}.inv5-top strong:last-child{white-space:nowrap}.inv5-meta{font-size:13px;color:#687079;margin-top:3px}.inv5-actions{display:flex;gap:7px;margin-top:8px}.inv5-actions button{border:0;border-radius:9px;padding:7px 10px;font-weight:800}.inv5-edit{background:#edf1f4}.inv5-del{background:#f8dddd;color:#9b1c1c}.expense5{background:#fff;border-radius:15px;padding:13px;margin:0 0 12px;box-shadow:0 4px 14px #00000010}.expense5 h3{margin:0 0 9px}.expense5-actions{display:flex;gap:8px;flex-wrap:wrap}.expense5-actions button{border:0;border-radius:11px;padding:10px 12px;font-weight:900}.ice5{background:#1769aa;color:#fff}.other5{background:#eee}.inv5-note{font-size:13px;color:#687079;margin:0 0 10px}
`;document.head.appendChild(style);

function categoryOf(i){if(i.category)return i.category;const k=String(i.appKey||'');if(['container12','lid12','container16','lid16','spoon','napkins','saltPacket','tostadas','bag10x20','tshirtBagSmall','tshirtBagMedium'].includes(k))return 'Empaque y desechables';if(['lemonJuice','lime','clamato','habaneroSauce','blackSauce','hotSauce'].includes(k))return 'Salsas y líquidos';return 'Ingredientes';}
function renderInventoryDropdown(){const title=document.querySelector('#screenTitle')?.textContent?.trim();if(title!=='Inventario')return;const host=document.querySelector('#content');if(!host||host.dataset.inv5==='1')return;const s=read(),groups={'Ingredientes':[],'Salsas y líquidos':[],'Empaque y desechables':[]};for(const i of s.inventory||[])(groups[categoryOf(i)]??= []).push(i);const order=['Ingredientes','Salsas y líquidos','Empaque y desechables'];host.dataset.inv5='1';host.innerHTML=`<div class="inv5-toolbar"><button class="inv5-buy" type="button" data-manual-purchase>🛒 Registrar compra</button><button class="inv5-add" type="button" id="inv5Add">＋ Agregar insumo</button></div><div class="inv5-note">Toca una categoría para desplegarla.</div>${order.map((name,idx)=>`<section class="inv5-group ${idx===2?'open':''}"><button type="button" class="inv5-head"><span>${esc(name)} · ${groups[name].length}</span><span>⌄</span></button><div class="inv5-body">${groups[name].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'es')).map(i=>`<div class="inv5-row"><div class="inv5-top"><strong>${esc(i.name)}</strong><strong>${qty(i.stock)} ${esc(i.unit)}</strong></div><div class="inv5-meta">Costo ${Number(i.costPerUnit||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}/${esc(i.unit)}</div><div class="inv5-actions"><button type="button" class="inv5-edit" data-inventory-edit="${esc(i.id)}">Editar</button><button type="button" class="inv5-del" data-delete="inventory" data-id="${esc(i.id)}">Eliminar</button></div></div>`).join('')||'<div class="inv5-row">Sin artículos</div>'}</div></section>`).join('')}`;host.querySelectorAll('.inv5-head').forEach(b=>b.onclick=()=>b.closest('.inv5-group').classList.toggle('open'));host.querySelector('#inv5Add')?.addEventListener('click',()=>document.querySelector('#primaryBtn')?.click())}

function fixLowCount(){if(!document.querySelector('#home.active'))return;const s=read(),low=(s.inventory||[]).filter(i=>Number(i.minimum||0)>0&&Number(i.stock||0)<=Number(i.minimum||0)).length;document.querySelectorAll('#summary .stats>div').forEach(d=>{if(d.textContent.includes('Inventario bajo')){const strong=d.querySelector('strong');if(strong)strong.textContent=String(low)}})}
function renderExpenseQuick(){const title=document.querySelector('#screenTitle')?.textContent?.trim();if(title!=='Dinero')return;const host=document.querySelector('#content');if(!host||host.querySelector('.expense5'))return;const box=document.createElement('section');box.className='expense5';box.innerHTML=`<h3>Gastos diarios</h3><div class="expense5-actions"><button type="button" class="ice5">🧊 Hielo $2</button><button type="button" class="other5">＋ Otro gasto</button></div>`;host.prepend(box);box.querySelector('.ice5').onclick=async()=>{const s=read();s.expenses=Array.isArray(s.expenses)?s.expenses:[];s.expenses.unshift({id:uid(),name:'Hielo',amount:2,date:today()});await save(s);location.reload()};box.querySelector('.other5').onclick=()=>document.querySelector('#primaryBtn')?.click()}
function run(){renderInventoryDropdown();renderExpenseQuick();fixLowCount()}
await seedMissing();run();new MutationObserver(()=>{const host=document.querySelector('#content');if(document.querySelector('#screenTitle')?.textContent?.trim()!=='Inventario'&&host)delete host.dataset.inv5;run()}).observe(document.body,{childList:true,subtree:true,characterData:true});