import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getFirestore, doc, setDoc, serverTimestamp, collection, getDocs, updateDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466'};
const app=getApps().find(a=>a.name==='panel-v4')||initializeApp(firebaseConfig,'panel-v4');
const db=getFirestore(app),LOCAL_KEY='chava-panel-v3',BASE='base-mixto-1lb';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qty=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:3});
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toLocaleDateString('en-CA')};
const read=()=>{try{return JSON.parse(localStorage.getItem(LOCAL_KEY)||'{}')}catch{return {}}};
const uid=()=>crypto.randomUUID();
function invByKey(s,key){return (s.inventory||[]).find(i=>i.appKey===key)}
function recipeById(s,id){return (s.recipes||[]).find(r=>r.id===id)}
function orderLb(o){if(Number(o.pounds)>0)return Number(o.pounds);if(!o.public)return Number(o.qty||1);let n=0;for(const it of o.items||[]){const t=`${it.name||''} ${it.detail||''}`.toLowerCase(),q=Number(it.qty||1);if(t.includes('1 libra')||t.includes('1 lb'))n+=q;else if(t.includes('½')||t.includes('1/2')||t.includes('media libra'))n+=.5*q}return n||Number(o.qty||1)}
function status(s){return ({nuevo:'pending',pendiente:'pending',preparando:'preparing',listo:'ready',entrega:'delivery',en_entrega:'delivery',entregado:'delivered',cancelado:'cancelled'}[s]||s||'pending')}
async function save(s){s.updatedAt=Date.now();localStorage.setItem(LOCAL_KEY,JSON.stringify(s));try{await setDoc(doc(db,'panel_v2','principal_v3'),{...s,sourceDevice:localStorage.getItem('chava-panel-device-v3')||'panel-v4',serverUpdatedAt:serverTimestamp()},{merge:false})}catch(e){console.error(e)}}
function seed(){const s=read();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.recipes=Array.isArray(s.recipes)?s.recipes:[];s.productionPlans=Array.isArray(s.productionPlans)?s.productionPlans:[];const items=[['fish','Pescado','lb'],['shrimp','Camarón','lb'],['tomato','Tomate','oz'],['onion','Cebolla','oz'],['cucumber','Pepino','oz'],['cilantro','Cilantro','oz'],['lemonJuice','Jugo de limón','fl oz'],['lime','Limón','pza'],['clamato','Clamato','fl oz'],['tostadas','Tostadas','pza'],['container16','Contenedor 16 oz','pza'],['lid16','Tapa 16 oz','pza'],['container12','Contenedor 12 oz','pza'],['lid12','Tapa 12 oz','pza'],['spoon','Cuchara','pza'],['napkins','Servilleta','pza'],['saltPacket','Sal','pza'],['habaneroSauce','Salsa habanero','pza']];let changed=false;for(const [k,n,u] of items)if(!invByKey(s,k)){s.inventory.push({id:`base-${k}`,name:n,unit:u,stock:0,minimum:0,costPerUnit:0,appKey:k});changed=true}if(!s.recipes.some(r=>r.id===BASE||String(r.name||'').toLowerCase()==='ceviche mixto')){const b={fish:.25,shrimp:.25,tomato:1.76,onion:1.06,cucumber:1.06,cilantro:.35,lemonJuice:1.01,lime:1,clamato:1.01,tostadas:4,container16:1,lid16:1,spoon:1,napkins:2,saltPacket:1,habaneroSauce:2};s.recipes.push({id:BASE,name:'Ceviche mixto',yieldLb:1,price:17,ingredients:Object.entries(b).map(([k,q])=>({inventoryId:invByKey(s,k).id,qty:q}))});changed=true}if(changed){s.panelV4Seeded=true;save(s).then(()=>location.reload())}}
seed();

let publicCache=[];
async function loadPublic(){try{const snap=await getDocs(collection(db,'pedidos'));publicCache=snap.docs.map(x=>({id:x.id,public:true,...x.data()}))}catch(e){console.error(e);publicCache=[]}}
loadPublic();
function mixedPublic(o){const r=o.recipe||o.publicRecipe||{};return Number(r.fish||0)>0&&Number(r.shrimp||0)>0&&!Number(r.octopus||0)}
function isMixedRecipe(s,id){const r=recipeById(s,id);return id===BASE||String(r?.name||'').trim().toLowerCase()==='ceviche mixto'}
function planOrders(s,p){const recipeName=String(recipeById(s,p.recipeId)?.name||'').trim().toLowerCase();const local=(s.orders||[]).filter(o=>{if(o.date!==p.date||['cancelled','delivered'].includes(status(o.status)))return false;if(o.recipeId===p.recipeId)return true;const txt=String(o.product||'').trim().toLowerCase();return recipeName&&txt.includes(recipeName)});const pub=publicCache.filter(o=>(o.deliveryDate||o.date)===p.date&&!['cancelled','delivered'].includes(status(o.status))&&(isMixedRecipe(s,p.recipeId)?mixedPublic(o):String((o.items||[]).map(i=>i.name).join(' ')).toLowerCase().includes(recipeName)));return [...local,...pub]}
function addNeed(m,id,n){if(!id||!Number(n))return;m.set(id,(m.get(id)||0)+Number(n))}
function calcPlan(s,p){const r=recipeById(s,p.recipeId),orders=planOrders(s,p),needs=new Map();for(const o of orders){if(o.public){for(const [k,v] of Object.entries(o.recipe||o.publicRecipe||{})){const inv=invByKey(s,k);if(inv)addNeed(needs,inv.id,v)}}else if(r){const mult=orderLb(o)/Number(r.yieldLb||1);for(const x of r.ingredients||[])addNeed(needs,x.inventoryId,Number(x.qty||0)*mult)}}if(r&&Number(p.extraLb)>0){const mult=Number(p.extraLb)/Number(r.yieldLb||1);for(const x of r.ingredients||[])addNeed(needs,x.inventoryId,Number(x.qty||0)*mult)}p.orderLb=orders.reduce((a,o)=>a+orderLb(o),0);p.totalLb=Number(p.orderLb||0)+Number(p.extraLb||0);return {orders,needs}}

const style=document.createElement('style');style.textContent=`.v4-box{background:#fff;border-radius:16px;padding:14px;margin:0 0 14px;box-shadow:0 5px 15px #00000012}.v4-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.v4-head h3{margin:0}.v4-plan{border-top:1px solid #ece6d8;padding:12px 0}.v4-plan:first-of-type{border-top:0}.v4-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.v4-actions button,.v4-btn{border:0;border-radius:11px;padding:10px 12px;font-weight:900}.v4-buy{background:#ef6c00;color:white}.v4-done{background:#168a46;color:white}.v4-del{background:#f4dddd;color:#8c1818}.v4-modal{position:fixed;inset:0;background:#0008;z-index:100;display:grid;place-items:end center}.v4-sheet{background:#fff;width:min(680px,100%);max-height:90vh;overflow:auto;border-radius:22px 22px 0 0;padding:16px}.v4-sheet h2{margin:0 0 12px}.v4-field{display:block;margin:10px 0;font-weight:800}.v4-field input,.v4-field select{margin-top:5px}.v4-choices{display:flex;flex-wrap:wrap;gap:7px;margin:7px 0}.v4-choices button{border:1px solid #ccc;background:#fff;border-radius:10px;padding:8px 10px}.v4-choices button.on{background:#168a46;color:#fff;border-color:#168a46}.v4-row{display:grid;grid-template-columns:1fr 110px 100px;gap:7px;align-items:end;padding:9px 0;border-top:1px solid #eee}.v4-row small{display:block;color:#666}.v4-row label{font-size:12px;font-weight:800}.v4-row input{padding:8px}.v4-save{width:100%;margin-top:14px;border:0;border-radius:12px;background:#168a46;color:#fff;padding:13px;font-weight:1000}.v4-close{float:right;border:0;background:#eee;border-radius:50%;width:36px;height:36px;font-size:22px}@media(max-width:520px){.v4-row{grid-template-columns:1fr 92px 82px}}`;document.head.appendChild(style);
function modal(title,body,onSave){const wrap=document.createElement('div');wrap.className='v4-modal';wrap.innerHTML=`<form class="v4-sheet"><button type="button" class="v4-close">×</button><h2>${esc(title)}</h2>${body}<button class="v4-save" type="submit">Guardar</button></form>`;document.body.appendChild(wrap);wrap.querySelector('.v4-close').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();await onSave(new FormData(e.currentTarget));wrap.remove()}}
function planModal(){const s=read(),recipes=s.recipes||[],defaultId=recipes.find(r=>r.id===BASE)?.id||recipes.find(r=>String(r.name||'').trim().toLowerCase()==='ceviche mixto')?.id||recipes[0]?.id||'',opts=recipes.map(r=>`<option value="${esc(r.id)}" ${r.id===defaultId?'selected':''}>${esc(r.name)}</option>`).join(''),buttons=[0,.5,1,1.5,2,2.5,3,4,5,6,7,8,10].map(x=>`<button type="button" data-x="${x}" class="${x===0?'on':''}">${x} lb</button>`).join('');modal('Planear producción',`<label class="v4-field">Producto<select name="recipeId">${opts}</select></label><label class="v4-field">Día<input name="date" type="date" value="${tomorrow()}" required></label><div class="v4-field">Libras extras<div class="v4-choices">${buttons}</div><input name="extraLb" type="hidden" value="0"></div>`,async fd=>{const s=read(),rid=fd.get('recipeId'),date=fd.get('date'),extra=Number(fd.get('extraLb')||0);s.productionPlans=Array.isArray(s.productionPlans)?s.productionPlans:[];let p=s.productionPlans.find(x=>x.date===date&&x.recipeId===rid&&x.status!=='done');if(!p){p={id:uid(),recipeId:rid,date,extraLb:extra,status:'planned'};s.productionPlans.push(p)}else p.extraLb=extra;calcPlan(s,p);await save(s);location.reload()});setTimeout(()=>{const w=document.querySelector('.v4-modal:last-child');w?.querySelectorAll('[data-x]').forEach(b=>b.onclick=()=>{w.querySelectorAll('[data-x]').forEach(x=>x.classList.remove('on'));b.classList.add('on');w.querySelector('[name=extraLb]').value=b.dataset.x})})}
function purchaseModal(planId){const s=read(),p=(s.productionPlans||[]).find(x=>x.id===planId);if(!p)return;const {needs}=calcPlan(s,p),rows=[...needs].map(([id,n])=>({inv:(s.inventory||[]).find(i=>i.id===id),n})).filter(x=>x.inv);modal(`Compra para ${qty(p.totalLb)} lb`,`<p>Estas son las cantidades calculadas. <b>Puedes cambiar cualquier cantidad</b> si quieres comprar más o menos.</p>${rows.map(x=>`<div class="v4-row"><div><b>${esc(x.inv.name)}</b><small>${esc(x.inv.unit)}</small></div><label>Comprar<input name="q_${esc(x.inv.id)}" type="number" min="0" step="0.001" value="${Number(x.n.toFixed(3))}"></label><label>Costo $<input name="c_${esc(x.inv.id)}" type="number" min="0" step="0.01"></label></div>`).join('')}<label class="v4-field">Fecha<input name="date" type="date" value="${new Date().toLocaleDateString('en-CA')}"></label>`,async fd=>{const s=read();s.purchases=Array.isArray(s.purchases)?s.purchases:[];for(const x of rows){const inv=(s.inventory||[]).find(i=>i.id===x.inv.id),q=Number(fd.get(`q_${x.inv.id}`)||0),cost=Number(fd.get(`c_${x.inv.id}`)||0);if(!inv||q<=0)continue;inv.stock=Number(inv.stock||0)+q;if(cost>0)inv.costPerUnit=cost/q;s.purchases.push({id:uid(),planId,inventoryId:inv.id,qty:q,total:cost,date:fd.get('date'),unit:inv.unit})}await save(s);location.reload()})}
function manualPurchaseModal(){const s=read(),items=[...(s.inventory||[])].sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'es'));if(!items.length)return;const opts=items.map(i=>`<option value="${esc(i.id)}">${esc(i.name)} (${esc(i.unit)})</option>`).join('');modal('Registrar compra',`<label class="v4-field">Insumo<select name="inventoryId">${opts}</select></label><label class="v4-field">Cantidad<input name="qty" type="number" min="0.001" step="0.001" required></label><label class="v4-field">Costo $<input name="cost" type="number" min="0" step="0.01"></label><label class="v4-field">Fecha<input name="date" type="date" value="${new Date().toLocaleDateString('en-CA')}" required></label>`,async fd=>{const s=read(),inv=(s.inventory||[]).find(i=>i.id===fd.get('inventoryId')),q=Number(fd.get('qty')||0),cost=Number(fd.get('cost')||0);if(!inv||q<=0)return;inv.stock=Number(inv.stock||0)+q;if(cost>0)inv.costPerUnit=cost/q;s.purchases=Array.isArray(s.purchases)?s.purchases:[];s.purchases.push({id:uid(),inventoryId:inv.id,qty:q,total:cost,date:fd.get('date'),unit:inv.unit});await save(s);location.reload()})}
async function finishPlan(planId){const s=read(),p=(s.productionPlans||[]).find(x=>x.id===planId);if(!p||p.status==='done')return;await loadPublic();const {needs,orders}=calcPlan(s,p);for(const [id,n] of needs){const inv=(s.inventory||[]).find(i=>i.id===id);if(inv)inv.stock=Number(inv.stock||0)-Number(n||0)}s.prepared=Array.isArray(s.prepared)?s.prepared:[];if(Number(p.extraLb)>0){let row=s.prepared.find(x=>x.recipeId===p.recipeId);if(!row){row={recipeId:p.recipeId,qty:0};s.prepared.push(row)}row.qty=Number(row.qty||0)+Number(p.extraLb)}for(const o of orders){if(o.public){try{await updateDoc(doc(db,'pedidos',o.id),{inventoryApplied:true})}catch(e){console.error(e)}}else{const lo=(s.orders||[]).find(x=>x.id===o.id);if(lo)lo.inventoryApplied=true}}p.status='done';p.doneAt=Date.now();await save(s);location.reload()}

function enhance(){document.querySelector('[data-module="purchases"]')?.remove();const title=$('#screenTitle')?.textContent||'',content=$('#content');if(!content)return;if(title==='Preparación'){content.querySelector('[data-extra-prep]')?.setAttribute('hidden','');}if(title==='Preparación'&&!content.querySelector('.v4-box')){const s=read();for(const p of s.productionPlans||[])if(p.status!=='done')calcPlan(s,p);const plans=(s.productionPlans||[]).filter(p=>p.status!=='cancelled');const box=document.createElement('section');box.className='v4-box';box.innerHTML=`<div class="v4-head"><div><h3>Plan de producción</h3><small>Pedidos + libras extras</small></div><button class="v4-btn v4-done" data-v4-new>＋ Planear</button></div>${plans.length?plans.map(p=>`<div class="v4-plan"><b>${esc(recipeById(s,p.recipeId)?.name||'Producto')} · ${esc(p.date)}</b><div>Pedidos ${qty(p.orderLb)} lb + Extras ${qty(p.extraLb)} lb = <b>${qty(p.totalLb)} lb</b></div><div class="v4-actions">${p.status==='done'?'<b>✓ Producción lista</b>':`<button class="v4-buy" data-v4-buy="${p.id}">🛒 Compra</button><button class="v4-done" data-v4-done="${p.id}">✓ Producción lista</button>`}<button class="v4-del" data-v4-del="${p.id}">Eliminar</button></div></div>`).join(''):'<p>Todavía no has planeado producción.</p>'}`;content.prepend(box)}if(title==='Inventario'&&!content.querySelector('[data-v4-manual]')){const bar=document.createElement('div');bar.className='v4-box';bar.innerHTML='<div class="v4-head"><div><h3>Inventario y compras</h3><small>Las compras suman; la producción descuenta.</small></div><button class="v4-btn v4-buy" data-v4-manual>＋ Compra</button></div>';content.prepend(bar)}}
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});setTimeout(enhance,300);
document.addEventListener('click',e=>{if(e.target.closest('[data-v4-new]'))return planModal();if(e.target.closest('[data-v4-manual]'))return manualPurchaseModal();const b=e.target.closest('[data-v4-buy]');if(b)return purchaseModal(b.dataset.v4Buy);const d=e.target.closest('[data-v4-done]');if(d)return finishPlan(d.dataset.v4Done);const x=e.target.closest('[data-v4-del]');if(x){const s=read();s.productionPlans=(s.productionPlans||[]).filter(p=>p.id!==x.dataset.v4Del);save(s).then(()=>location.reload())}});
