import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import { getFirestore, doc, setDoc, serverTimestamp, collection, getDocs, updateDoc } from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';

const cfg={apiKey:'AIzaSyBbOIXTr2Tvz1FvoTk5GZgP2jx24jpjlL4',authDomain:'ceviches-y-cocteles-el-chava.firebaseapp.com',projectId:'ceviches-y-cocteles-el-chava',storageBucket:'ceviches-y-cocteles-el-chava.firebasestorage.app',messagingSenderId:'227568387475',appId:'1:227568387475:web:6ccd3e67e62d1bf4b0d466'};
const app=getApps().find(a=>a.name==='shopping-v6')||initializeApp(cfg,'shopping-v6');
const db=getFirestore(app),KEY='chava-panel-v3',BASE='base-mixto-1lb',REV=2;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const qty=n=>Number(n||0).toLocaleString('en-US',{maximumFractionDigits:3});
const today=()=>new Date().toLocaleDateString('en-CA');
const uid=()=>crypto.randomUUID();
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
async function save(s){s.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(s));try{await setDoc(doc(db,'panel_v2','principal_v3'),{...s,sourceDevice:localStorage.getItem('chava-panel-device-v3')||'shopping-v6',serverUpdatedAt:serverTimestamp()},{merge:false})}catch(e){console.error(e)}}
function invByKey(s,key){return (s.inventory||[]).find(i=>i.appKey===key)}
function recipeById(s,id){return (s.recipes||[]).find(r=>r.id===id)}
function isMixedRecipe(s,id){const r=recipeById(s,id);return id===BASE||String(r?.name||'').trim().toLowerCase()==='ceviche mixto'}
function status(v){return ({nuevo:'pending',pendiente:'pending',preparando:'preparing',listo:'ready',entrega:'delivery',en_entrega:'delivery',entregado:'delivered',cancelado:'cancelled'}[v]||v||'pending')}
function orderLb(o){if(Number(o.pounds)>0)return Number(o.pounds);if(!o.public)return Number(o.qty||1);let n=0;for(const it of o.items||[]){const t=`${it.name||''} ${it.detail||''}`.toLowerCase(),q=Number(it.qty||1);if(t.includes('1 libra')||t.includes('1 lb'))n+=q;else if(t.includes('½')||t.includes('1/2')||t.includes('media libra'))n+=.5*q}return n||Number(o.qty||1)}
function addNeed(m,id,n){if(!id||!Number(n))return;m.set(id,(m.get(id)||0)+Number(n))}

const items=[
 ['fish','Pescado','oz','Ingredientes'],['shrimp','Camarón','oz','Ingredientes'],['tomato','Tomate','oz','Ingredientes'],['onion','Cebolla','oz','Ingredientes'],['cucumber','Pepino','oz','Ingredientes'],['cilantro','Cilantro','oz','Ingredientes'],
 ['lemonJuice','Jugo de limón','fl oz','Salsas y líquidos'],['clamato','Clamato','fl oz','Salsas y líquidos'],['blackSauce','Salsa negra','fl oz','Salsas y líquidos'],['hotSauce','Salsa picante','fl oz','Salsas y líquidos'],
 ['tostadas','Tostadas','pza','Empaque y desechables'],['container16','Contenedor 16 oz','pza','Empaque y desechables'],['lid16','Tapa 16 oz','pza','Empaque y desechables'],['container12','Contenedor 12 oz','pza','Empaque y desechables'],['lid12','Tapa 12 oz','pza','Empaque y desechables'],['spoon','Cuchara','pza','Empaque y desechables'],['napkins','Servilleta','pza','Empaque y desechables'],['saltPacket','Sal','pza','Empaque y desechables'],['bag10x20','Bolsa 10 × 20 cm','pza','Empaque y desechables'],['tshirtBagSmall','Bolsa camiseta chica','pza','Empaque y desechables'],['tshirtBagMedium','Bolsa camiseta mediana','pza','Empaque y desechables']
];
const BASE_Q={fish:4,shrimp:3,tomato:3,onion:.75,cucumber:2,cilantro:.5,lemonJuice:1,clamato:1.333,tostadas:4,container16:1,lid16:1,spoon:1,napkins:2,saltPacket:1};
async function seed(){const s=read();s.inventory=Array.isArray(s.inventory)?s.inventory:[];s.recipes=Array.isArray(s.recipes)?s.recipes:[];s.purchases=Array.isArray(s.purchases)?s.purchases:[];let changed=false;
 for(const [key,name,unit,category] of items){let row=invByKey(s,key)||s.inventory.find(i=>i.id===`base-${key}`)||s.inventory.find(i=>String(i.name||'').trim().toLowerCase()===name.toLowerCase());if(!row){row={id:`base-${key}`,name,unit,stock:0,minimum:0,costPerUnit:0,appKey:key,category};s.inventory.push(row);changed=true}else{if(!row.appKey){row.appKey=key;changed=true}if(!row.category){row.category=category;changed=true}}}
 if(Number(s.shoppingV6RecipeRevision||0)<2){for(const key of ['fish','shrimp']){const row=invByKey(s,key);if(row&&row.unit==='lb'){row.stock=Number(row.stock||0)*16;row.minimum=Number(row.minimum||0)*16;if(Number(row.costPerUnit||0)>0)row.costPerUnit=Number(row.costPerUnit)/16;row.unit='oz';for(const p of s.purchases){if(p.inventoryId===row.id&&String(p.unit||'').toLowerCase()==='lb'){p.qty=Number(p.qty||0)*16;p.unit='oz'}}changed=true}}}
 let r=s.recipes.find(x=>x.id===BASE)||s.recipes.find(x=>String(x.name||'').trim().toLowerCase()==='ceviche mixto');if(!r){r={id:BASE,name:'Ceviche mixto',yieldLb:1,price:17,ingredients:[]};s.recipes.push(r);changed=true}if(Number(s.shoppingV6RecipeRevision||0)<REV){r.name='Ceviche mixto';r.yieldLb=1;r.price=17;r.ingredients=Object.entries(BASE_Q).map(([key,n])=>({inventoryId:invByKey(s,key).id,qty:n}));s.shoppingV6RecipeRevision=REV;changed=true}if(changed){await save(s);location.reload()}}
await seed();

let publicOrders=[];
async function loadPublic(){try{const snap=await getDocs(collection(db,'pedidos'));publicOrders=snap.docs.map(x=>({id:x.id,public:true,...x.data()}))}catch(e){console.error(e);publicOrders=[]}}
function mixedPublic(o){const r=o.recipe||o.publicRecipe||{};return Number(r.fish||0)>0&&Number(r.shrimp||0)>0&&!Number(r.octopus||0)}
function planOrders(s,p){const recipeName=String(recipeById(s,p.recipeId)?.name||'').trim().toLowerCase();const local=(s.orders||[]).filter(o=>{if(o.inventoryApplied||o.date!==p.date||['cancelled','delivered'].includes(status(o.status)))return false;if(o.recipeId===p.recipeId)return true;const txt=String(o.product||'').trim().toLowerCase();return recipeName&&txt.includes(recipeName)});const pub=publicOrders.filter(o=>!o.inventoryApplied&&(o.deliveryDate||o.date)===p.date&&!['cancelled','delivered'].includes(status(o.status))&&(isMixedRecipe(s,p.recipeId)?mixedPublic(o):String((o.items||[]).map(i=>i.name).join(' ')).toLowerCase().includes(recipeName)));return [...local,...pub]}
function addMixed(s,needs,lb){lb=Number(lb||0);if(lb<=0)return;for(const key of ['fish','shrimp','tomato','onion','cucumber','cilantro','lemonJuice','clamato']){const inv=invByKey(s,key);if(inv)addNeed(needs,inv.id,BASE_Q[key]*lb)}const full=Math.floor(lb+1e-6),half=(lb-full)>=.49?1:0,servings=full+half;const packs={tostadas:full*4+half*2,container16:full,lid16:full,container12:half,lid12:half,spoon:servings,napkins:servings*2,saltPacket:servings};for(const [key,n] of Object.entries(packs)){const inv=invByKey(s,key);if(inv)addNeed(needs,inv.id,n)}}
function calc(s,p){const needs=new Map(),orders=planOrders(s,p),r=recipeById(s,p.recipeId),mixed=isMixedRecipe(s,p.recipeId);for(const o of orders){if(mixed){addMixed(s,needs,orderLb(o));continue}if(o.public){for(const [key,n] of Object.entries(o.recipe||o.publicRecipe||{})){const inv=invByKey(s,key);if(inv)addNeed(needs,inv.id,n)}}else if(r){const mult=orderLb(o)/Number(r.yieldLb||1);for(const x of r.ingredients||[])addNeed(needs,x.inventoryId,Number(x.qty||0)*mult)}}if(Number(p.extraLb)>0){if(mixed)addMixed(s,needs,p.extraLb);else if(r){const mult=Number(p.extraLb)/Number(r.yieldLb||1);for(const x of r.ingredients||[])addNeed(needs,x.inventoryId,Number(x.qty||0)*mult)}}p.orderLb=orders.reduce((a,o)=>a+orderLb(o),0);p.totalLb=Number(p.orderLb||0)+Number(p.extraLb||0);return {needs,orders}}

const OPTIONAL=['blackSauce','hotSauce','bag10x20','tshirtBagSmall','tshirtBagMedium','container12','lid12','container16','lid16','spoon','napkins','tostadas'];
function shopModal(planId){const s=read(),p=(s.productionPlans||[]).find(x=>x.id===planId);if(!p)return;loadPublic().then(()=>{const st=read(),plan=(st.productionPlans||[]).find(x=>x.id===planId);if(!plan)return;const {needs}=calc(st,plan),rows=[...needs].map(([id,n])=>{const inv=(st.inventory||[]).find(i=>i.id===id);return {inv,n:inv?Math.max(0,Number(n||0)-Number(inv.stock||0)):Number(n||0),required:true}}).filter(x=>x.inv);for(const key of OPTIONAL){const inv=invByKey(st,key);if(inv&&!rows.some(x=>x.inv.id===inv.id))rows.push({inv,n:0,required:false})}const wrap=document.createElement('div');wrap.className='v4-modal';wrap.innerHTML=`<form class="v4-sheet"><button type="button" class="v4-close">×</button><h2>Compra para ${qty(plan.totalLb)} lb</h2><p><b>Comprar</b> ya viene calculado para esta producción. Puedes subir cualquier cantidad si quieres llevar más.</p>${rows.map(x=>`<div class="v4-row"><div><b>${esc(x.inv.name)}</b><small>${x.required?'':'Stock opcional · '}${esc(x.inv.unit)}</small></div><label>Comprar<input name="q_${esc(x.inv.id)}" type="number" min="0" step="0.001" value="${Number(x.n.toFixed(3))}"></label><label>Costo $<input name="c_${esc(x.inv.id)}" type="number" min="0" step="0.01"></label></div>`).join('')}<label class="v4-field">Fecha<input name="date" type="date" value="${today()}"></label><button class="v4-save" type="submit">Registrar compra</button></form>`;document.body.appendChild(wrap);wrap.querySelector('.v4-close').onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=e.submitter;if(submit)submit.disabled=true;const fd=new FormData(e.currentTarget),state=read();state.purchases=Array.isArray(state.purchases)?state.purchases:[];for(const x of rows){const inv=(state.inventory||[]).find(i=>i.id===x.inv.id),q=Number(fd.get(`q_${x.inv.id}`)||0),cost=Number(fd.get(`c_${x.inv.id}`)||0);if(!inv||q<=0)continue;inv.stock=Number(inv.stock||0)+q;if(cost>0)inv.costPerUnit=cost/q;state.purchases.push({id:uid(),planId,inventoryId:inv.id,qty:q,total:cost,date:fd.get('date'),unit:inv.unit})}await save(state);wrap.remove();location.reload()}})}
async function finish(planId){const s=read(),p=(s.productionPlans||[]).find(x=>x.id===planId);if(!p||p.status==='done')return;await loadPublic();const {needs,orders}=calc(s,p);for(const [id,n] of needs){const inv=(s.inventory||[]).find(i=>i.id===id);if(inv)inv.stock=Number(inv.stock||0)-Number(n||0)}s.prepared=Array.isArray(s.prepared)?s.prepared:[];if(Number(p.extraLb)>0){let row=s.prepared.find(x=>x.recipeId===p.recipeId);if(!row){row={recipeId:p.recipeId,qty:0};s.prepared.push(row)}row.qty=Number(row.qty||0)+Number(p.extraLb)}for(const o of orders){if(o.public){try{await updateDoc(doc(db,'pedidos',o.id),{inventoryApplied:true})}catch(e){console.error(e)}}else{const lo=(s.orders||[]).find(x=>x.id===o.id);if(lo)lo.inventoryApplied=true}}p.status='done';p.doneAt=Date.now();await save(s);location.reload()}

document.addEventListener('click',e=>{const buy=e.target.closest('[data-v4-buy]');if(buy){e.preventDefault();e.stopImmediatePropagation();shopModal(buy.dataset.v4Buy);return}const done=e.target.closest('[data-v4-done]');if(done){e.preventDefault();e.stopImmediatePropagation();finish(done.dataset.v4Done)}},true);
